
const GESUNDHEIT = [
    {
        nr: 1,
        user: "AIDS Hilfe Wien",
        Adresse: "Mariahilfer Gürtel 4, 1060 Wien",
        Mail: "office@aids-hilfe-wien.at",
        Öffnungszeiten: "",
        intro: "Test- und Beratungszentrum",
        about: "Die Aids Hilfe Wien hat ihren Sitz seit 1997 – also seit mittlerweile über 20 Jahren – im Aids Hilfe Haus am Mariahilfer Gürtel 4, 1060 Wien. Von hier aus betreuen wir unsere Angebote in Wien, Niederösterreich und dem Burgenland. In dieser Zeit hat sich die Aids Hilfe Wien zu einer der bekanntesten Anlaufstellen für sexuelle Gesundheit  entwickelt. Heute findet man Expertise zu HIV/AIDS und anderen sexuell übertragbaren Krankheiten, inklusive aller Testmöglichkeiten, unter einem Dach vereint mit psychologischer Beratung und Betreuung im Aids Hilfe Haus. Das heißt, wir mussten und konnten unser Angebot schrittweise ausweiten, von der Fokussierung auf HIV-bezogene Angebote (Test, Beratung, Therapievermittlung, Betreuung usw.) hin zu Testungen auf alle großen sexuell übertragbaren Krankheiten (STDs): HIV, Syphilis, Tripper, Chlamydien und virale Hepatitis („Big five“). Quelle: https://aids.at/ueber-uns/",
        weblink: "http://www.aids.at/",
        lat: 48.19128312611382, 
        lng: 16.338536663428904, 
    },
    {
        nr: 2,
        user: "Samariterbund",
        Adresse: "Hollergasse 2-6, 1150 Wien",
        Mail: "info@samariterbund.net",
        Öffnungszeiten: "",
        intro: "Arbeiter - Samariter - Bund Österreichs",
        about: "Seit der Gründung vor 90 Jahren ist der Arbeiter-Samariter-Bund Österreichs seiner obersten Verpflichtung treu geblieben: Die haupt- und ehrenamtlichen MitarbeiterInnen der Non-Profit-Organisation leisten für ältere Menschen, Kranke, Verletzte und in Not Geratene Hilfe von Mensch zu Mensch – unabhängig von deren ethnischer Zugehörigkeit, Religion und Weltanschauung. Das Aufgabengebiet des Samariterbundes hat sich in den vergangenen Jahren enorm erweitert – vom klassischen Rettungs- und Krankentransport hin zu Gesundheits- und sozialen Diensten wie etwa Pflege, Aslywerber- und Obdachlosenbetreuung, sowie Entwicklungszusammenarbeit, Katastrophenhilfsdienst und Jugendarbeit. Quelle: https://www.samariterbund.net/ueber-uns/",
        weblink: "https://www.samariterbund.net/",
        lat: 48.18492431149642, 
        lng: 16.32628935548441,

    },
    {
        nr: 4,
        user: "Ernährungsrat Wien",
        Adresse: "nicht angegeben",
        Mail: "kontakt@ernaehrungsrat-wien.at",
        Öffnungszeiten: "",
        intro: "vernetzen - verstehen - verändern",
        about: "Wir sind ein zivilgesellschaftlicher Zusammenschluss von, derzeit ca. 30, engagierten Menschen aus den verschiedensten Bereichen des Wiener Ernährungssystems: Gastronomie und Forschung, urbane Landwirtschaft und zivilgesellschaftliche Organisationen, Beratung und Interessensvertretung, Gemeinschaftsverpflegung und Food Coops. Diese Hintergründe und die Auseinandersetzung mit der eigenen Ernährung und deren Auswirkungen - der persönliche Bezug zu den Themen Lebensmittel und Ernährung hat unsere Gruppe zusammengeführt. Uns verbindet das gemeinsame Ziel, durch den Ernährungsrat Wien zu einem ökologisch zukunftsfähigen und sozial gerechten Ernährungssystem in der Wiener Stadt-Region beizutragen. Jedes (neue) Mitglied bereichert den Ernährungsrat Wien mit neuen Perspektiven. Geben wir der Zivilgesellschaft gemeinsam eine starke Stimme für ein demokratisches, sozial gerechtes und ökologisch zukunftsfähiges Ernährungssystem! Quelle: https://ernaehrungsrat-wien.at/ueber-uns/wir/",
        weblink: "https://ernaehrungsrat-wien.at/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
        nr: 5,
        user: "European Centre for Social Welfare Policy and Research",
        Adresse: "Berggasse 17, 1090 Wien",
        Mail: "ec@euro.centre.org",
        Öffnungszeiten: "",
        intro: "Intergovernmental organisation affiliated to the United Nations",
        about: "The European Centre for Social Welfare Policy and Research (the European Centre) is an intergovernmental organisation affiliated to the United Nations. Its purpose is to foster the collaboration in social welfare between governments and organisations by providing applied social science and comparative empirical research; forging the evidence-base for social policy making and mutual learning; initiating future-oriented public policy debates by networking. Quelle: https://www.euro.centre.org/aboutus",
        weblink: "https://www.euro.centre.org/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
        nr: 6,
        user: "Lebensart",
        Adresse: "Wiener Straße 35, 3100 St. Pölten",
        Mail: "service@lebensart.at",
        Öffnungszeiten: "",
        intro: "Verlags GmbH",
        about: "nachhaltig.gut.leben. Das ist unsere Vision. Alle Menschen sollen heute und in Zukunft ein gutes Leben führen können. Deshalb haben wir den Lebensart Verlag gegründet. Wir berichten über nachhaltige Trends und bringen Hintergrundinformationen damit Sie eine gute Entscheidung treffen können. Vor allem zeigen wir Lösungsansätze von kreativen Menschen, wie ein gutes Leben aussehen kann und erzählen Geschichten, die inspirieren und zu eigenem Handeln anregen. Das alles lesen Sie in den Print und Online-Magazinen LEBENSART, BUSINESSART und über die Reiseplattform lebensart-reisen.at. Wir veranstalten jährlich die Wahl der Nachhaltigen GestalterInnen Österreichs, sind Mitveranstalter des CSR-Circle, kooperieren mit engagierten Menschen und Organisationen und unterstützen Partner in ihrer nachhaltigen Kommunikation. Quelle: https://www.lebensart-verlag.at/was-wir-tun-werte-vision-und-mission",
        weblink: "https://www.lebensart.at/",
        lat: 48.21892335496585,   
        lng: 15.660709850085858,
    },
    {
        nr: 7,
        user: "Land schafft Leben",
        Adresse: "Erzherzog-Johann-Str. 248b, 8970 Schladming",
        Mail: "post@landschafftleben.at",
        Öffnungszeiten: "",
        intro: "ist österreichischen Lebensmitteln auf der Spur!",
        about: "Wir zeigen den Konsumentinnen und Konsumenten transparent und ohne zu werten, wie in Österreich Lebensmittel produziert werden, wie die Produktion vor Ort im Bauernhof erfolgt, wie die Verarbeitung funktioniert und wie das fertige Produkt schließlich im Lebensmittelhandel landet. Für die Konsumentinnen und Konsumenten ergibt sich durch die leicht nachvollziehbar und ausführlich aufbereiteten Informationen ein neues Verständnis für die Zusammenhänge innerhalb der Lebensmittelproduktion und damit ein höheres Wert-Bewusstsein für österreichische Lebensmittel. Quelle: https://www.landschafftleben.at/service-aktuelles/organisation/verein",
        weblink: "https://www.landschafftleben.at/",
        lat: 47.393776442137025,  
        lng: 13.687645470807377,
    },
    {
        nr: 7,
        user: "Land schafft Leben",
        Adresse: "Schwarzenbergstraße 8/1, 1010 Wien",
        Mail: "post@landschafftleben.at",
        Öffnungszeiten: "",
        intro: "ist österreichischen Lebensmitteln auf der Spur!",
        about: "Wir zeigen den Konsumentinnen und Konsumenten transparent und ohne zu werten, wie in Österreich Lebensmittel produziert werden, wie die Produktion vor Ort im Bauernhof erfolgt, wie die Verarbeitung funktioniert und wie das fertige Produkt schließlich im Lebensmittelhandel landet. Für die Konsumentinnen und Konsumenten ergibt sich durch die leicht nachvollziehbar und ausführlich aufbereiteten Informationen ein neues Verständnis für die Zusammenhänge innerhalb der Lebensmittelproduktion und damit ein höheres Wert-Bewusstsein für österreichische Lebensmittel. Quelle: https://www.landschafftleben.at/service-aktuelles/organisation/verein",
        weblink: "https://www.landschafftleben.at/",
        lat: 48.20249394560691,   
        lng: 16.37390564808664,
    },
    {
        nr: 8,
        user: "MATISSEK Innovation Consulting",
        Adresse: "Schönbrunner Straße 178/2,, 1120 Wien",
        Mail: "office@matissek.at",
        Öffnungszeiten: "",
        intro: "Michael Matissek, MSc",
        about: "MATISSEK Innovation Consulting bietet ihnen Service und Beratung im Bereich Forschungs- und Innovationsberatung. Meine Kernkompetenz ist die interdisziplinäre – wissenschaftliche, wirtschaftliche und nachhaltige – Betreuung ihres Projektes. Quelle: https://firmen.wko.at/michael-matissek%2c-msc-matissek-innovation-consulting/wien/?firmaid=017e38dd-b16b-4087-bcef-d618a98e7d68&name=michael+matissek,+msc&standort=wien+(bundesland)",
        weblink: "https://firmen.wko.at/michael-matissek%2c-msc-matissek-innovation-consulting/wien/?firmaid=017e38dd-b16b-4087-bcef-d618a98e7d68&name=michael+matissek,+msc&standort=wien+(bundesland)",
        lat: 48.18610794055923,    
        lng: 16.338176340687966,
    },
    {
        nr: 9,
        user: "Rote Nasen Clowndoctors Austria",
        Adresse: "Wattgasse 48, 1170 Wien",
        Mail: "office@rotenasen.at",
        Öffnungszeiten: "",
        intro: "Partner of RED NOSES International",
        about: "Seit 1994 bringen ROTE NASEN Clowndoctors ein Lachen dorthin, wo es vielleicht nicht vermutet, aber dringend gebraucht wird: Zu kleinen Patient*innen auf Stationen der Kinderchirurgie, der Kardiologie und auf Onkologie- und Intensivstationen, zu Kindern und Jugendlichen in sonder- und heilpädagogischen Einrichtungen und auch zu Erwachsenen und Senior*innen in Pflege- und Rehabilitationszentren. ROTE NASEN Clowndoctors sind überall, wo Menschen auch seelische Unterstützung brauchen, um wieder gesund zu werden und neue Lebensfreude zu finden. Quelle: https://www.rotenasen.at/clownbesuche/was-wir-tun/",
        weblink: "https://www.rotenasen.at/",
        lat: 48.217990405674854,     
        lng: 16.32065989041571,
    },
    {
        nr: 10,
        user: "RED NOSES Clowndoctors International",
        Adresse: "Wattgasse 48, 1170 Wien",
        Mail: "office@rotenasen.at",
        Öffnungszeiten: "",
        intro: "Partner of RED NOSES International",
        about: "Die Idee und der Erfolg von ROTE NASEN in Österreich sprachen sich auch bald international herum. Andere Länder wie Ungarn und die Tschechische Republik wollten ROTE NASEN ebenfalls etablieren. Das Interesse wurde immer größer und immer mehr Partnerorganisationen kamen hinzu. Die gemeinnützige Privatstiftung RED NOSES Clowndoctors International wurde 2003 von ROTE NASEN Österreich ins Leben gerufen. RED NOSES International umfasst neben Österreich Partnerorganisationen in Ungarn, der Tschechischen Republik, der Slowakei, Deutschland, Slowenien, Kroatien, Polen, Litauen, Palästina und Jordanien. Quelle: https://www.rotenasen.at/ueber-uns/geschichte/",
        weblink: "https://www.rotenasen.at/",
        lat: 48.217990405674854,     
        lng: 16.32065989041571,
    },
    {
        nr: 11,
        user: "Umblick",
        Adresse: "Hartlgasse 9/13, 1200 Wien",
        Mail: "buero@umblick.at",
        Öffnungszeiten: "",
        intro: "Umweltbildung - Umwelt, Abfall, Energie, Nachhaltigkeit, Mobilität",
        about: "Umblick steht für umfassende Weiterentwicklung im Hinblick auf Themengebiete der Umwelt und Nachhaltigkeit. Wir konzentrieren uns darauf, Menschen und Organisationen bei der Mitgestaltung einer nachhaltigen Zukunft zu unterstützen. Durch unser interdisziplinäres Team erreichen wir Ihre Ziele effizient unter Einbeziehung unterschiedlicher Blickwinkel und kombinierter Ansätze.  Wir schließen die Lücke von reinem Wissen hin zum effektiven Umsetzen. Um­blick hat sich zum Ziel gesetzt Men­schen dabei zu er­mutigen ihre Selbst­­wirk­sam­keit zu be­grei­fen und ihre Hand­lun­gen als wich­tigen Bei­trag für das ge­mein­same Ge­stal­ten einer nach­hal­tig­eren Welt zu er­le­ben. Um diese Mis­sion­en zu er­fül­len be­gin­nen wir be­reits bei den Jüng­sten im Kinder­garten und bieten Umweltbildung wie z.B. Umweltworkshops bis hin zum Pen­sions­al­ter an. Quelle: https://umblick.at/bildung/ueber-uns/",
        weblink: "https://umblick.at/",
        lat: 48.23160827990701,     
        lng: 16.373425396510783 ,
    },
    {
        nr: 12,
        user: "Verband der Akademikerinnen Österreichs",
        Adresse: "Reitschulgasse 2, 1010 Wien",
        Mail: "office.vaoe@aon.at",
        Öffnungszeiten: "",
        intro: "Austrian Federation of University Women",
        about: "Der Verband der Akademikerinnen Österreichs eröffnet qualifizierten und engagierten Frauen internationale und interdisziplinäre Beziehungen und ermutigt zu Qualität, Verantwortung, Respekt und Selbstvertrauen. Der VAÖ, Verband der Akademikerinnen Österreichs, mit Verbandssitz in Wien besteht seit dem Jahr 1922. Er ist die  größte Vereinigung von akademisch gebildeten Frauen Österreichs, mit 6 Landesverbänden (NÖ und Burgenland ist dem LV Wien angegliedert, Vorarlberg ist mit dem LV Tirol vernetzt). Quelle: https://www.vaoe.at/",
        weblink: "https://www.vaoe.at/",
        lat: 48.207431780638956,      
        lng: 16.367350430894483,
    },
    {
        nr: 13,
        user: "iamgood",
        Adresse: "Hirschengasse 16/2/7, 1060 Wien",
        Mail: "say@iamgood.cc",
        Öffnungszeiten: "",
        intro: "Plattform für Persönlichkeitsentwicklung",
        about: "Education & creation of a broader awareness for environmental protection. iamgood is an event series and a community for all curious minds, who want to live a more meaningful life. Once every two months, we organize iamgood events. We invite two different speakers to give inspirational talks and actionable insights on a broad range of personal development topics. Also, we love music, that’s why we invite great musicians to our events.  Each iamgood event takes place at a new location in Vienna and is free of charge. Quelle: https://iamgood.cc/",
        weblink: "hhttps://iamgood.cc/",
        lat: 48.19468386474175,      
        lng: 16.34782394068816,
    },
    {
        nr: 14,
        user: "plan:g",
        Adresse: "Belruptstraße 21, 6900 Bregenz",
        Mail: "impressum@plan-g.at",
        Öffnungszeiten: "",
        intro: "Partnerschaft für globale Gesundheit",
        about: "plan:g entstand 1958 als Leprahilfswerk. Wir sind eine Stiftung kirchlichen Rechts. Durch Hinterlegung der Errichtungsurkunde haben wir im staatlichen Bereich Rechtspersönlichkeit als Körperschaft öffentlichen Rechts (KöR). Wir verstehen uns als Menschenrechtswerk der katholischen Kirche im Gesundheitssektor und arbeiten in der Entwicklungszusammenarbeit. Quelle: https://plan-g.at/ueber-uns/wer-wir-sind",
        weblink: "https://plan-g.at/",
        lat: 47.50392033003685,      
        lng: 9.750940949918776,
    },
    {
        nr: 15,
        user: "pro mente austria",
        Adresse: "Lonstorferplatz 1, 4020 Linz",
        Mail: "office@promenteaustria.at",
        Öffnungszeiten: "",
        intro: "Österreichischer Dachverband für Vereine und Gesellschaften für psychische und soziale Gesundheit.",
        about: "Wir vertreten die gemeinsamen Ziele unserer Mitglieder sowohl in Österreich als auch im Ausland und bieten eine Plattform für den unkomplizierten Informationsaustausch. Nach außen stehen wir als Ansprechpartner für alle Stakeholder im Bereich der psychischen und sozialen Gesundheit zur Verfügung. Unser Ziel ist es, die Stellung von Menschen mit psychischen oder psycho-sozialen Problemen in der Gesellschaft zu verbessern und ihrem sozialen Umfeld beizustehen. Dafür unterstützen wir auch andere Organisationen. Ein besonderes Ziel ist die Einhaltung der Menschenrechte und im Besonderen der UN-Konvention über die Rechte von Menschen mit Behinderungen und des europäischen Mental Health Pacts. Daher fördern und fordern wir unparteilich und überkonfessionell die Inklusion und Partizipation aller Menschen und begrüßen ihre Vielfalt. Quelle: https://www.promenteaustria.at/de/pro-mente-austria/leitbild/",
        weblink: "https://www.promenteaustria.at/de/home/",
        lat: 48.29376381590077,     
        lng: 14.3140221806237,
    },
    {
        nr: 16,
        user: "AGU",
        Adresse: "Große Mohrengasse 39/6, 1020 Wien",
        Mail: "info@aegu.net",
        Öffnungszeiten: "",
        intro: "Ärztinnen und Ärzte für eine gesunde Umwelt",
        about: "Als österreichische Sektion der ISDE (International Society of Doctors for the Environment) sind wir eine parteipolitisch unabhängige Organisation von Ärztinnen und Ärzten, die sich für Belange des Umweltschutzes aus ärztlicher Sicht einsetzen. Quelle: https://www.aegu.net/uber-uns.html",
        weblink: "https://www.aegu.net/",
        lat: 48.21859534694276,      
        lng: 16.384384972677523,
    },
    {
        nr: 17,
        user: "Österreichisches Rotes Kreuz",
        Adresse: "Wiedner Hauptstraße 32, 1041 Wien",
        Mail: "service@roteskreuz.at",
        Öffnungszeiten: "",
        intro: "Partner of RED NOSES International",
        about: "Das Rote Kreuz ist die größte humanitäre Nonprofit-Organisation in Österreich: wir sind für Sie da. Aus Liebe zum Menschen. Quelle: https://www.roteskreuz.at/home",
        weblink: "https://www.roteskreuz.at/home/",
        lat: 48.19564257268525,     
        lng: 16.36704546342908,
    },
];
