const STADTENTWICKLUNG = [
    {
      nr: 1,
      user: "Das Gramm",
      Adresse: "Neutorgasse 7, 8010 Graz",
      Mail: "hallo@dasgramm.at",
      Öffnungszeiten: "Mo - Fr: 9:00 - 19:00, Sa: 10:00 - 17:00",
      intro: "Regionale Bio-Greisslerei",
      about: "Das Gramm, unsere regionale Greißlerei, wurde im April 2016 in der Neutorgasse eröffnet. Seither liegt unser Fokus auf regionalen Spezialitäten, unverpackten Lebensmitteln aus kontrolliert biologischem Anbau und einer kleinen, aber feinen Auswahl an Zero Waste Artikeln in den Bereichen Haushalt und Körperpflege. Produkte, die eine Verpackung brauchen, sind in Pfandgläsern oder Papiersackerln erhältlich, um so besonders Einwegplastik bestmöglich zu vermeiden. Bei uns kannst du genau diese Menge kaufen, die du auch wirklich brauchst – so gehen wir auch bei dir zuhause gegen Lebensmittelverschwendung vor. Unser “kleines Gramm” ist mehr als nur eine Greißlerei; es ist ein Ort zum Ankommen und Wohlfühlen, an dem du dich mit unserem Experten:innen-Team austauschen oder auch einfach in Ruhe die Atmosphäre auf dich wirken lassen kannst. Quelle: https://www.dasgramm.at/das-sind-wir/#wiewir",
      weblink: "https://www.dasgramm.at/",
      lat: 47.070688574948505, 
      lng: 15.436974564704707,
    },
    {
        nr: 2,
        user: "Ernährungsrat Wien",
        Adresse: "nicht angegeben",
        Mail: "kontakt@ernaehrungsrat-wien.at",
        Öffnungszeiten: "",
        intro: "vernetzen - verstehen - verändern",
        about: "Wir sind ein zivilgesellschaftlicher Zusammenschluss von, derzeit ca. 30, engagierten Menschen aus den verschiedensten Bereichen des Wiener Ernährungssystems: Gastronomie und Forschung, urbane Landwirtschaft und zivilgesellschaftliche Organisationen, Beratung und Interessensvertretung, Gemeinschaftsverpflegung und Food Coops. Diese Hintergründe und die Auseinandersetzung mit der eigenen Ernährung und deren Auswirkungen - der persönliche Bezug zu den Themen Lebensmittel und Ernährung hat unsere Gruppe zusammengeführt. Uns verbindet das gemeinsame Ziel, durch den Ernährungsrat Wien zu einem ökologisch zukunftsfähigen und sozial gerechten Ernährungssystem in der Wiener Stadt-Region beizutragen. Jedes (neue) Mitglied bereichert den Ernährungsrat Wien mit neuen Perspektiven. Geben wir der Zivilgesellschaft gemeinsam eine starke Stimme für ein demokratisches, sozial gerechtes und ökologisch zukunftsfähiges Ernährungssystem! Quelle: https://ernaehrungsrat-wien.at/ueber-uns/wir/",
        weblink: "https://ernaehrungsrat-wien.at/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
        nr: 3,
        user: "Initiative gemeinsam bauen & wohnen",
        Adresse: "Bloch-Bauer-Promenade 28/2/15, 1100 Wien",
        Mail: "kontakt@inigbw.org",
        Öffnungszeiten: "",
        intro: "Verein, um gemeinschaftliches Bauen und Wohnen in Wien und in ganz Österreich in Schwung zu bringen",
        about: "Die Initiative bietet die Plattform, um all diejenigen zusammen zu führen, die das Thema des gemeinschaftlichen Bauens und Wohnens weiter voran bringen wollen. Sie richtet sich dabei sowohl an Professionist*innen wie Architekt*innen, Bauträger*innen und Politiker*innen als auch an Private, die das Bauen und Wohnen in Gemeinschaft für sich in Betracht ziehen. Ziel ist, die Entstehungsbedingungen für gemeinschaftliche Wohnformen zu verbessern und die Umsetzung konkreter Projekte zu unterstützen. Dazu bedarf es insbesondere politischer Entscheidungen und des Engagements durch die öffentliche Hand. Quelle: https://www.inigbw.org/die-initiative",
        weblink: "https://www.inigbw.org/",
        lat: 48.17857206159186,   
        lng: 16.387274156030298,
    },
    {
        nr: 4,
        user: "Schwendermarkt",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "initiative-schwendermarkt@gmx.at",
        Öffnungszeiten: "",
        intro: "Initiative zur Erhaltung und Belebung des Schwendermarktes",
        about: "Der Schwendermarkt ist der kleinste Markt in Wien. Interessante Geschäfte mit Bio und regionalen Produkten von bauern aus der Umgebung von Wien und dem weinviertel. gemütliche Atmosphäre in Markt Cafés, sehr gutes Essen inkl einer Vietnamesin, die super kocht, Marktstände mit Gemüse, Käse, Obst. tolles großes Café in hippem Blumenladen,.... Quelle: https://www.facebook.com/Schwendermarkt/reviews/?ref=page_internal Review of: Karin N. York",
        weblink: "http://www.schwendermarkt.at/",
        lat: 48.19097235033396, 
        lng: 16.326267103155473,
    },
    {
        nr: 5,
        user: "Institut für ökologische Stadtentwicklung",
        Adresse: "Seidengasse 13 / 3, 1070 Wien",
        Mail: "office@oekostadt.at",
        Öffnungszeiten: "",
        intro: "Ökostadt - Lebenswerte Stadt",
        about: "Im Institut für ökologische Stadtentwicklung hat sich ein interdisziplinäres Team von mehr als 20 Fachleuten mit dem Ziel der Errichtung sowie fachlichen Unterstützung der Planung und Errichtung von nachhaltigen und ökologischen Modellsiedlungen („Ökostadt“) zusammengefunden. Durch Integration ökologischer Einzelmaßnahmen für alle Sektoren wie Raumordnung und Siedlungsplanung, Verkehr, Energie, Wasserversorgung und Abwasserbehandlung, Abfallwirtschaft, Landschaftsplanung oder Produktion und Handel von Gütern wird eine flächensparende städtische Bauweise und eine umwelt- und sozialverträgliche Gestaltung der technischen und wirtschaftlichen Einrichtungen erreicht. Kompakte Siedlungseinheiten mit ausgewogener Nutzungsmischung ermöglichen kurze Wege für Fußgänger und erleichtern damit den Verzicht auf individuelle motorisierte Verkehrsmittel (Kfz). Niedrigenergiebauweise oder Passivhausstandard ist durch weitgehende Südorientierung der Gebäude erreichbar. Die Anordnung der Siedlungseinheiten entlang von Achsen begünstigt die Erschließung durch Linien des öffentlichen Verkehrs.Die „Ökostadt“ bietet eine Alternative zu dem durch Umweltbelastungen vielfach beeinträchtigten Stadtleben, dient aber auch als Vorbild für die Umgestaltung bestehender Städte. Da wie dort erhöht sich die Lebensqualität. Quelle: http://www.oekostadt.at/de/info.htm",
        weblink: "http://www.oekostadt.at/",
        lat: 48.200430955975506,    
        lng: 16.345775136443077,
    },
    {
        nr: 6,
        user: "K4DP",
        Adresse: "Gersthofer Strasse 162, 1180 Wien",
        Mail: "info@k4dp.org",
        Öffnungszeiten: "",
        intro: "Knowledge for Development Parthnership",
        about: "The Knowledge for Development Partnership, which was founded under Austrian law at the Palais des Nations, Geneva, on 3 April 2017 during the “Knowledge for Development: Global Partnership Conference”. We are a non-profit organisation (NGO) promoting the global advancement of peaceful, wealthy, sustainable, and inclusive knowledge societies, fostering global knowledge partnerships for achieving the Sustainable Development Goals of the United Nations and implementing the Agenda 2030. With partners from all over the world, K4DP aims to localize and implement the global Agenda Knowledge for Development. Quelle: https://www.k4dp.org/",
        weblink: "https://www.k4dp.org/",
        lat: 48.23876941918626,     
        lng: 16.320031740143154,
    },
    {
        nr: 7,
        user: "Landentwicklung Steiermark",
        Adresse: "Hans-Sachs-Gasse 5, 8010 Graz",
        Mail: "office@landentwicklung-steiermark.at",
        Öffnungszeiten: "",
        intro: "BETEILIGUNG ALS MOTOR FÜR EINE STARKE GEMEINSCHAFT",
        about: "Eine Gemeinde. Eine Region. Das sind keine Flächen, das sind immer Menschen. Was Gemeinden und Regionen brauchen, um zukunftsfähig zu sein, ist eine wertschätzende Beziehungskultur. Eine Kultur, in der jeder spürt, dass er gebraucht wird, dass alle voneinander lernen und miteinander wachsen können. Die Landentwicklung Steiermark schafft Beteiligung, und damit ein „Wir“ für die Zukunft. Quelle: https://www.landentwicklung-steiermark.at/",
        weblink: "https://www.landentwicklung-steiermark.at/",
        lat: 47.06921522378337,     
        lng: 15.442635180346967 ,
    },
    {
        nr: 8,
        user: "OKIDROM",
        Adresse: "Lindengasse 32/10, 1070 Wien",
        Mail: "richard.pfeifer@oikodrom.org",
        Öffnungszeiten: "",
        intro: "the Vienna Institute for Urban Sustainability",
        about: "We are a private research institute following our goal to open spaces and opportunities in creating a sustainable future. We empower human actors through participatory processes, starting from local real-life situations. In a multicultural research network we use trans- and interdisciplinary approaches to generate theses and theories and connect scientific and non scientific knowledge. Quelle: https://oikodrom.org/",
        weblink: "http://www.oikodrom.org/",
        lat: 48.20026388356145,      
        lng: 16.35043715603093,
    },
    {
        nr: 9,
        user: "Passivhaus Austria",
        Adresse: "Anichstraße 29/54, 6020 Innsbruck",
        Mail: "office@passivhaus-austria.org",
        Öffnungszeiten: "",
        intro: "Alle Informationen rund ums Passivhaus",
        about: "Das Passivhaus-Experten-Netzwerk setzt sich aus Architekten, Planern, Bauphysikern, Haustechnikplanern, Bauträgern, Bauherren, Bauausführenden, Komponentenherstellern, Baustoffindustrie, Energieberatern, Weiterbildungsinstitutionen, Universitäten und Kommunen zusammen und wird aktiv vom Passivhaus Institut unterstützt. Quelle: https://passivhaus-austria.org/content/passivhaus-austria",
        weblink: "https://passivhaus-austria.org/",
        lat: 47.26400420409408,      
        lng: 11.390211605734585,
    },
    {
        nr: 10,
        user: "SDG Botschaftr:innen",
        Adresse: "8010 Graz",
        Mail: "info@sdg-botschafterinnen.at",
        Öffnungszeiten: "",
        intro: "Verein für nachhaltige Entwicklung und zur Umsetzung der Agenda 2030",
        about: "Wir sind eine Gruppe junger und engagierter Erwachsener, die sich seit 2018 für die Sustainable Development Goals (SDGs) der Vereinten Nationen einsetzt. Wir wollen das Wissen um die Agenda 2030 und die 17 Ziele für nachhaltige Entwicklung in die Welt tragen und einen Beitrag zu ihrer Erreichung leisten! Seit Sommer 2019 werden wir vom Europäischen Solidaritätskorps gefördert und können uns damit noch besser für unser Anliegen einsetzen. Quelle: https://sdg-botschafterinnen.at/",
        weblink: "https://sdg-botschafterinnen.at/",
        lat: 47.077815439093854,      
        lng: 15.449824505730058,
    },
    {
        nr: 11,
        user: "SPES",
        Adresse: "Panoramaweg 1, 4553 Schlierbach",
        Mail: "hotel@spes.co.at",
        Öffnungszeiten: "",
        intro: "Zukunftsakademie",
        about: "Die SPES Zukunftsakademie ist eine überparteiliche Bildungseinrichtung, die vom gemeinnützigen SPES Verein und mehr als 100 privaten Teilhaber/inne/n getragen wird. Die Aktivitäten dienen dem Gemeinwohl gegenwärtiger und künftiger Generationen und sind nicht auf Gewinn ausgerichtet. Quelle: https://www.spes.co.at/das-ist-spes/",
        weblink: "https://www.spes.co.at/",
        lat: 47.932847657702126,      
        lng: 14.125984801505963,
    },
    {
        nr: 12,
        user: "Stadt Labor",
        Adresse: "Griesgasse 40, 8020 Graz",
        Mail: "office@stadtlaborgraz.at",
        Öffnungszeiten: "",
        intro: "Stadt gemeinsam entwickeln",
        about: "Das StadtLABOR ist ein Innovationslabor für nachhaltige und lebenswerte Städte und Gemeinden. Wir verstehen die Transformation von Stadtteilen, Quartieren und Standorten als offenen und kooperativen Entwicklungsprozess, der Räume für Inspiration, Kreativität, gemeinsames Lernen und Innovation schafft. Quelle: https://www.stadtlaborgraz.at/de/ueber-uns",
        weblink: "https://www.stadtlaborgraz.at/de",
        lat: 47.06801624167627,      
        lng: 15.43396770093853,
    },
    {
        nr: 13,
        user: "STRATECO",
        Adresse: "Ruckerlberggasse 13, 8020 Graz",
        Mail: "office@strat.eco",
        Öffnungszeiten: "",
        intro: "Information über Prozessoptimierung und Ökologische Bewertung",
        about: "Wir wollen die Welt ein Stückchen nachhaltiger machen – und glauben daran, dass wir gemeinsam mit Ihnen Ihre Produkte, Dienstleistungen, Prozesse und Ressourcennutzung ökologisch und oft auch ökonomisch nachhaltiger gestalten können, um dadurch Ihr Unternehmen und die regionale Wertschöpfung zu stärken. Das bedeutet für uns: Wir unterstützen Wirtschafts- und Lebensweisen in ihrem Ziel, allen eine stabile Zukunft zu bescheren. Quelle: https://www.strat.eco/",
        weblink: "https://www.strat.eco/",
        lat: 47.06880837066728,       
        lng: 15.464438743813336,
    },
    {
        nr: 14,
        user: "Transition Austria",
        Adresse: "Burgring 6/2, 8010 Graz",
        Mail: "office@transition.at",
        Öffnungszeiten: "",
        intro: "Wandelinitiativen: Überblicken – Verstehen – Mitmachen.",
        about: "Transition Austria ist eine Plattform und Vernetzung von und für Initiativen des Wandels in Österreich.  Diese Initiativen sind von der Idee der Transition Bewegung inspiriert.  Sie wurden von Einzelpersonen, Gruppen, Initiativen, NGO’s oder Wirtschaftsbetrieben initiiert. Sie suchen Lösungen im Alltag und neue Formen des Zusammenslebens auf kommunaler Ebene. Sie agieren nach dem Motto “Global Denken, Lokal handeln”. Quelle: https://transition.at/transition-austria/",
        weblink: "https://tourismusklimafit.at/",
        lat: 47.07180036574457,      
        lng: 15.444181955456818,
    },
    {
        nr: 15,
        user: "Urban Forum",
        Adresse: "Neunkirchner Straße 15/7, 2700 Wiener Neustadt",
        Mail: "office@urbanforum.at",
        Öffnungszeiten: "",
        intro: "Egon Matzner-Institut für Stadtforschung",
        about: "Nach wie vor steht die zentrale Forderung nach einem aufgabenorientierten Finanzausgleich im Raum, wurde bis dato aber noch immer nicht erfüllt. Aus diesem Grund befinden sich zahlreiche große Kommunen im finanziellen Abseits, müssen auf einen drastischen Sparkurs setzen und können kaum noch Investitionen tätigen. Es kann aber nicht angehen, dass Gelder die nach EU Definition in den ländlichen Raum fließen sollen, in Österreich fast ausschließlich dem Landwirtschaftssektor zu Gute kommen. Insbesondere auch die kleineren urbanen Zentren in den Regionen sollen von diesen Förderungen profitieren. Darüber hinaus wird es aber auch wichtig sein, die großen Ballungsräume mit ihren Herausforderungen des Bevölkerungszuwachses und der Integration von Zuwanderern nicht alleine zu lassen. Diesem bedeutenden Thema will sich unser neu gegründeter, überparteilicher Verein Urban Forum verstärkt widmen. Zudem gilt es, Bewusstsein zu schaffen für stadtpolitische Anliegen und die Notwendigkeit von Strukturreformen. Wir wollen grundsätzlich als Interessensvertretung für Städte auftreten und dem urbanen Raum ein funktionierendes Netzwerk bieten. Weiters werden wir mit regelmäßigen Veranstaltungen zu Urbanitätsthemen und der Herausgabe von Fachpublikationen aufhorchen lassen. Quelle: https://www.urbanforum.at/index.php",
        weblink: "https://www.urbanforum.at/",
        lat: 47.811765487523424,       
        lng: 16.243947140678504,
    },
    {
        nr: 16,
        user: "Verband der Akademikerinnen Österreichs",
        Adresse: "Reitschulgasse 2, 1010 Wien",
        Mail: "office.vaoe@aon.at",
        Öffnungszeiten: "",
        intro: "Austrian Federation of University Women",
        about: "Der Verband der Akademikerinnen Österreichs eröffnet qualifizierten und engagierten Frauen internationale und interdisziplinäre Beziehungen und ermutigt zu Qualität, Verantwortung, Respekt und Selbstvertrauen. Der VAÖ, Verband der Akademikerinnen Österreichs, mit Verbandssitz in Wien besteht seit dem Jahr 1922. Er ist die  größte Vereinigung von akademisch gebildeten Frauen Österreichs, mit 6 Landesverbänden (NÖ und Burgenland ist dem LV Wien angegliedert, Vorarlberg ist mit dem LV Tirol vernetzt). Quelle: https://www.vaoe.at/",
        weblink: "https://www.vaoe.at/",
        lat: 48.207431780638956,      
        lng: 16.367350430894483,
    },
    {
        nr: 17,
        user: "virtual vehicle",
        Adresse: "Inffeldgasse 21a, 8010 Graz",
        Mail: "info@v2c2.at",
        Öffnungszeiten: "",
        intro: "Leidenschaft für elekrifizierte, autonome und vernetzte Fahrzeuge",
        about: "Virtual Vehicle ist ein führendes internationales F&E Zentrum für die Automobil-und Bahnindustrie. Das Zentrum konzentriert sich auf die konsequente Virtualisierung der Fahrzeugentwicklung. Diese Verknüpfung von numerischen Simulationen und Hardware-Tests führt zu einem umfassenden Hardware-Software-System-Design. Quelle: https://www.v2c2.at/deu/",
        weblink: "https://www.v2c2.at/deu/",
        lat: 47.058310296863084,       
        lng: 15.463768138264388,
    },
    {
        nr: 18,
        user: "Ökosoziales Formun Wien",
        Adresse: "Stadiongasse 6-8, 1010 Wien",
        Mail: "wien@oekosozial.at",
        Öffnungszeiten: "",
        intro: "Für die Menschen in unserer Stadt und unsere städtische Umwelt – für eine lebenswerte Gegenwart und Zukunft!",
        about: "Mit unseren Projekten und Aktivitäten fördern wir einen respektvollen Umgang mit der Natur unserer Lebensgrundlage und ein friedliches und solidarisches Miteinander der Menschen in unserer Stadt. Wir beziehen uns dabei auf die Agenda 2030 und ihre 17 Ziele für Nachhaltige Entwicklung (Sustainable Development Goals, kurz: „SDGs“) – den weltweiten UNO-Aktionsplan für Nachhaltige Entwicklung. Quelle: https://oekosozial.at/wien/was-wir-tun/",
        weblink: "https://oekosozial.at/wien/",
        lat: 48.20940797658662,       
        lng: 16.356514269524183,
    },
   ];

const UMWELT = [
    {
        nr: 1,
        user: "ARGE Abfallvermeidung",
        Adresse: "Puchstraße 41, 8010 Graz",
        Mail: "office@arge.at",
        Öffnungszeiten: "",
        intro: "Umweltschutzunternehmen",
        about: "Die ARGE konzipiert und implementiert Projekte in den Bereichen Abfallvermeidung, Ressourcenschonung und nachhaltige Entwicklung. Die ARGE ist eine Non-Profit Organisation, die im Jahr 1982 gegründet wurde. Wir konzipieren und organisieren regionale, nationale und internationale Projekte im Bereich nachhaltige Entwicklung und kommunale Abfallwirtschaft. Unsere erste Priorität ist -wie unser Name schon sagt- die Abfallvermeidung. Der schonende Umgang mit Ressourcen und der Schutz unserer Umwelt ist Fokus unserer Arbeit. Wir betrachten die Abfall- und Ressourcenwirtschaft im sozialen, ökologischen und ökonomischen Kontext. Ein wesentlicher Teil unserer Aktivitäten ist daher die Kooperation mit sozialwirtschaftlichen Einrichtungen und die Schaffung von Arbeitsplätzen im Umweltbereich. Quelle: https://www.facebook.com/ArgeAbfallvermeidung/",
        weblink: "https://www.arge.at/",
        lat:  47.05001107528067, 
        lng: 15.436887611278067,
    },
    {
        nr: 2,
        user: "ARGE Schöpfungsveranstaltung",
        Adresse: "Petersplatz 1, 1010 Wien",
        Mail: "office@argeschoepfung.at",
        Öffnungszeiten: "",
        intro: "Kirchliche Umweltarbeit",
        about: "Seit über 25 Jahren ist die ARGE Schöpfungsverantwortung in Kirche und Gesellschaft aktiv. Sie ist Initiator der kirchlichen Umweltarbeit in Österreich und Mitbegründer des EUROPEAN CHRISTIAN ENVIRONMENTAL NETWORKS (ECEN). Im Rahmen der Initiative zur Einführung der SCHÖPFUNGSZEIT agiert sie international. Die Umsetzung erfolgt projektbezogen mit einem Team von engagierten Mitarbeitern, Experten aus Natur- und Geisteswissenschaften. Mit einem laufenden Bildungsprogramm und ökosozialen Handlungsmodellen begleitet und unterstützt sie engagierte Personen und Institutionen sowie einschlägige Netzwerke. Als Gründungsmitglied des EUROPÄISCHEN CHRISTLICHEN UMWELTNETZWERKES (ECEN) bietet sie Partizipation am internationalen kirchlichen Umweltgeschehen. Zahlreiche Initiativen erfolgen in Kooperation mit Umwelt- und Entwicklungsorganisationen. Für Ihre Tätigkeit wurde die ARGE Schöpfungsverantwortung mit dem Staatspreis der Republik Österreich, dem Konrad-Lorenz-Preis ausgezeichnet und erhielt für die Wahrnehmung der Trias des „Konziliaren Prozesses für Gerechtigkeit – Frieden – Bewahrung der Schöpfung“ die Europäische Friedensrose Waldhausen. Quelle: https://www.argeschoepfung.at/ueber-uns/ueberblick.html",
        weblink: "https://www.argeschoepfung.at/",
        lat: 48.209195875185195, 
        lng: 16.370094671021324

    },
    {
        nr: 3,
        user: "ARCHE NOAH",
        Adresse: "Obere Straße 40, 3553 Schiltern",
        Mail: "info@arche-noah.at",
        Öffnungszeiten: "",
        intro: "Verein für Erhalt und Entwicklung der Kulturpflanzenvielfalt",
        about: "Seit über 30 Jahren setzen sich Menschen im Verein ARCHE NOAH für den Erhalt und die Entwicklung der Kulturpflanzenvielfalt ein. Der Verein ARCHE NOAH entstand 1989 (Geschichte des Vereins) auf Initiative von GärtnerInnen, BäuerInnen und JournalistInnen, die das Saatgut als Grundlage der Ernährung buchstäblich wieder in die eigenen Hände nehmen wollten. Denn: Seit 1900 ist die Vielfalt unserer Kulturpflanzen durch die Industrialisierung der Landwirtschaft weltweit dramatisch – um 75% – zurückgegangen (Details zum Verlust der Vielfalt)! Heute gefährden Gentechnik, Saatgut-Monopole, Klimawandel und Kriege dieses kostbare Erbe. ARCHE NOAH hält dem eine positive Vision (Leitbild des Vereins) und zahlreiche Aktivitäten entgegen: ARCHE NOAH bewahrt und pflegt tausende gefährdete Gemüse-, Obst- und Getreidesorten. Erfolgreich arbeiten wir daran, traditionelle und seltene Sorten wieder in die Gärten und auf den Markt zu bringen – dank der Unterstützung von über 17.000 engagierten Mitgliedern und Förderern. Quelle: https://www.arche-noah.at/ueber-uns",
        weblink: "https://www.arche-noah.at/",
        lat: 48.51896771558353, 
        lng: 15.618738735905062,

    },
    {
    
        nr: 4,
        user: "BirdLife",
        Adresse: "Museumsplatz 1/10/8, 1070 Wien",
        Mail: "office@birdlifeat",
        Öffnungszeiten: "",
        intro: "Gesellschaft für Vogelkunde",
        about: "Wir geben Vägeln eine Stimme. BirdLife Österreich ist Partner von BirdLife International, dem weltweit größten aktiven Netzwerk von Natur- und Vogelschutz-Organisationen mit über 10 Millionen Unterstützern in über 120 Ländern. BirdLife Österreich ist als gemeinnütziger Verein die einzige bundesweit tätige ornithologische Vereinigung Österreichs und verwirklicht seit der Gründung 1953 wissenschaftlich fundierte Natur- und Vogelschutzprojekte in vier Kernbereichen: Artenschutz, Schutzgebiete & Lebensräume, Nachhaltigkeit, Bewusstseinsbildung. Quelle: https://www.birdlife.at/page/unserteam",
        weblink: "https://www.birdlife.at/" ,
        lat: 48.20279043802087, 
        lng: 16.35914381979702,
    },
    {
    
        nr: 5,
        user: "Bündnis Alpenkonvention Kärnten",
        Adresse: "Proboj 2, 9113 Sittersdorf",
        Mail: "unglaub@archi-noah.at",
        Öffnungszeiten: "",
        intro: "Teil der Alpenkonvention zum Schutz und für nachhaltige Entwicklung des gesamten Alpenraumes",
        about: "Das gemeinsame Ziel unserer Mitgliedorganisationen ist die  Sicherung einer lebenswerten und intakten Umwelt für die künftigen Generationen sowie Entwicklung einer zukunftsfähigen Lebens- und Wirtschaftsweise. Dies ist auch Botschaft und Inhalt der rechtsverbindlichen Alpenkonvention. Sie bildet daher die Grundlage unserer Arbeit. Wir möchten dazu beitragen, dass in Kärnten in einem gemeinsamen gesellschaftlichen Prozess die Umsetzung der Alpenkonvention Schritt für Schritt vorangetrieben wird. Quelle: https://www.buendnisalpenkonvention.at/ueber-uns",
        weblink: "https://www.buendnisalpenkonvention.at/" ,
        lat: 46.554567127891396,
        lng: 14.598284144200157,
    },
    {
    
        nr: 6,
        user: "Climates Austria",
        Adresse: "Lindengasse 56/18-19, 1070 Wien",
        Mail: "hello@climatesaustria.org",
        Öffnungszeiten: "",
        intro: "Jugend für eine klimaverträgliche Zukunft",
        about: "CliMates Austria bringt Bewegung ins Klima. Wir nehmen Einfluss auf die Klimapolitik, bestärken junge Changemaker*innen, machen Klimabildung und schreiben über wichtige klimapolitische Themen. Wir sind junge Bürger*innen, die die Welt verändern. CliMates Austria ist eine ehrenamtliche NGO und Teil des internationalen Jugendnetzwerks CliMates. Und Du kannst jetzt als Mitglied „Mate“ Teil davon werden! Quelle: https://climatesaustria.org/",
        weblink: "https://climatesaustria.org/" ,
        lat: 48.19987970442615,
        lng: 16.346090278771765,
    },
    {
    
        nr: 7,
        user: "Die Umweltberatung Wien",
        Adresse: "Buchengasse 77/4, 1100 Wien",
        Mail: "service@umweltberatung.at",
        Öffnungszeiten: "",
        intro: "Individuelle Beratung für Privatpersonen sowie für Unternehmen.",
        about: "Seit 1988 informiert und berät DIE UMWELTBERATUNG Privathaushalte und Betriebe und arbeitet in Umweltschutz-Projekten. Von diesem Know-how profitieren unsere Kundinnen und Kunden sowie ProjektpartnerInnen. DIE UMWELTBERATUNG bereitet ökologisches Wissen gut verständlich und praxisorientiert auf. Unsere BeraterInnen beantworten Ihre Anfragen individuell und firmen-unabhängig. Wir beraten private Haushalte, Bildungseinrichtungen, Institutionen und Betriebe. DIE UMWELTBERATUNG verwirklicht zukunftsweisende Projekte. Quelle: https://www.umweltberatung.at/ueber-uns",
        weblink: "https://www.umweltberatung.at/" ,
        lat: 48.1749255624965,
        lng: 16.374404598358936,
    },
    {
    
        nr: 8,
        user: "Das Gramm",
        Adresse: "Neutorgasse 7, 8010 Graz",
        Mail: "hallo@dasgramm.at",
        Öffnungszeiten: "Mo - Fr: 9:00 - 19:00, Sa: 10:00 - 17:00",
        intro: "Regionale Bio-Greisslerei",
        about: "Das Gramm, unsere regionale Greißlerei, wurde im April 2016 in der Neutorgasse eröffnet. Seither liegt unser Fokus auf regionalen Spezialitäten, unverpackten Lebensmitteln aus kontrolliert biologischem Anbau und einer kleinen, aber feinen Auswahl an Zero Waste Artikeln in den Bereichen Haushalt und Körperpflege. Produkte, die eine Verpackung brauchen, sind in Pfandgläsern oder Papiersackerln erhältlich, um so besonders Einwegplastik bestmöglich zu vermeiden. Bei uns kannst du genau diese Menge kaufen, die du auch wirklich brauchst – so gehen wir auch bei dir zuhause gegen Lebensmittelverschwendung vor. Unser “kleines Gramm” ist mehr als nur eine Greißlerei; es ist ein Ort zum Ankommen und Wohlfühlen, an dem du dich mit unserem Experten:innen-Team austauschen oder auch einfach in Ruhe die Atmosphäre auf dich wirken lassen kannst. Quelle: https://www.dasgramm.at/das-sind-wir/#wiewir",
        weblink: "https://www.dasgramm.at/",
        lat: 47.070688574948505, 
        lng: 15.436974564704707,
    },
    {
    
        nr: 9,
        user: "E. C. O.",
        Adresse: "Lakeside B07b, 9020 Klagenfurt",
        Mail: "office@e-c-o.at",
        Öffnungszeiten: "",
        intro: "Institut für Ökologie",
        about: "Wir begeistern uns für die Vielfalt der Natur und sichern ihren Erhalt auch für zukünftige Generationen. Als Forschungs- und Beratungsunternehmen für „Naturschutz im 21. Jahrhundert“ begleiten und unterstützen wir unsere internationalen und nationalen Partner:innen dabei, natürliche Lebensräume zu bewahren und zu verbessern, außergewöhnliche Naturerlebnisse zu ermöglichen und die Lebens- und Wirtschaftsbedingungen in den jeweiligen Regionen weiterzuentwickeln. Mit unseren ökologischen Fachplanungen, naturräumlichen Erhebungen, innovativen Kommunikationskonzepten und nachhaltiger Entwicklungszusammenarbeit setzen wir uns aktiv für die Erfüllung der globalen Sustainable Development Goals ein. Quelle: https://e-c-o.at/home.html",
        weblink: "https://e-c-o.at/home.html",
        lat: 46.61445647600445,
        lng: 14.263496343802236,
    },
    {
    
        nr: 10,
        user: "EU Umweltbüro",
        Adresse: "Strozzigasse 10/8-9, 1080 Wien",
        Mail: "office@eu-umweltbuero.at",
        Öffnungszeiten: "",
        intro: "Kompetenzzentrum für Europäische Umweltpolitik und -gesetzgebung",
        about: "Das EU Umweltbüro in Wien wurde 1994 als Kompetenzzentrum für Europäische Umweltpolitik und -gesetzgebung gegründet und ist im Umweltdachverband – der größten österreichischen Dachorganisation von Umweltschutzorganisationen – angesiedelt. Die Kernkompetenzen des EU-Umweltbüros sind umfassende Kenntnisse des politischen Gesetzwerdungsprozesses auf europäischer Ebene und Informationen über derzeitige und zukünftige Entwicklungen im Bereich EU-Umweltpolitik. Das Umweltbüro vertritt die österreichischen Mitglieder im Vorstand des europäischen Dachverbands European Environmental Bureau (EEB)in Brüssel. Das Umweltbüro ist auf europäischer und  internationaler Ebene gut vernetzt und arbeitet auf Deutsch und Englisch. Quelle: https://www.eu-umweltbuero.at/ueber-uns/was-wir-tun/",
        weblink: "https://www.eu-umweltbuero.at/",
        lat: 48.20739603144972, 
        lng: 16.349451311852835,
    },
    {
    
        nr: 11,
        user: "EVAL",
        Adresse: "Rössing 311, 8972 Ramsau am Dachstein",
        Mail: "khh@evalww.com",
        Öffnungszeiten: "",
        intro: "Ehrfurcht vor allem Leben",
        about: "Gemeinnützige Gemeinschaft zur Förderung des friedlichen Zusammenlebens der Menschen und des respektvollen Umgangs mit der Natur. Vernetzungs- und Informations-Plattform für alle Initiativen, Gruppen und Vereine, die sich zum EVAL-Prinzip - Ehrfurcht Vor Allem Leben - bekennen. Die EVAL-Datenbank als Teil des EVAL-INFO-SYSTEMS (EIS) steht allen Bürgern zur Verfügung die sich frei von Lobbyisteninteressen jeglicher Art und ohne Werbung und persönliche Datenerfassung informieren möchten. Unser Ziel: Urteilsfähige und selbstkritische DemokratenInnen. Quelle: https://www.evalww.com/",
        weblink: "https://www.evalww.com/",
        lat: 47.43266380070504,  
        lng: 13.752812580751053,
    },
    {
    
        nr: 12,
        user: "Ernährungsrat Wien",
        Adresse: "nicht angegeben",
        Mail: "kontakt@ernaehrungsrat-wien.at",
        Öffnungszeiten: "",
        intro: "vernetzen - verstehen - verändern",
        about: "Wir sind ein zivilgesellschaftlicher Zusammenschluss von, derzeit ca. 30, engagierten Menschen aus den verschiedensten Bereichen des Wiener Ernährungssystems: Gastronomie und Forschung, urbane Landwirtschaft und zivilgesellschaftliche Organisationen, Beratung und Interessensvertretung, Gemeinschaftsverpflegung und Food Coops. Diese Hintergründe und die Auseinandersetzung mit der eigenen Ernährung und deren Auswirkungen - der persönliche Bezug zu den Themen Lebensmittel und Ernährung hat unsere Gruppe zusammengeführt. Uns verbindet das gemeinsame Ziel, durch den Ernährungsrat Wien zu einem ökologisch zukunftsfähigen und sozial gerechten Ernährungssystem in der Wiener Stadt-Region beizutragen. Jedes (neue) Mitglied bereichert den Ernährungsrat Wien mit neuen Perspektiven. Geben wir der Zivilgesellschaft gemeinsam eine starke Stimme für ein demokratisches, sozial gerechtes und ökologisch zukunftsfähiges Ernährungssystem! Quelle: https://ernaehrungsrat-wien.at/ueber-uns/wir/",
        weblink: "https://ernaehrungsrat-wien.at/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
    
        nr: 13,
        user: "FiBL",
        Adresse: "Doblhoffgasse 7/10, 1010 Wien",
        Mail: "info.oesterreich@fibl.org",
        Öffnungszeiten: "",
        intro: "Forschungsinstitut für biologischen Landbau",
        about: "Das FiBL verfügt über Kompetenzen in allen Belangen der biologischen Landwirtschaft: Bodenbewirtschaftung und Pflanzenbau, artgerechte Tierhaltung und ganzheitliche Tiergesundheit, sozioökonomische Belange, biologische Lebensmittelverarbeitung sowie umfassende Analysen des Biomarktes. Zudem engagiert sich das FiBL seit vielen Jahren auf internationaler Ebene für die Entwicklung des Biolandbaus zum Beispiel beim Biolandbau-Weltdachverband IFOAM – Organics International. Das FiBL ist Partner in Forschungs- und Entwicklungsprojekten der Europäischen Union (EU), der Welternährungsorganisation FAO und vieler weiterer nationaler und internationaler Institutionen. Das FiBL unterstützt die Entwicklung zukunftsfähiger Landwirtschaft in Afrika, Asien, Lateinamerika und Osteuropa in enger Zusammenarbeit mit lokalen Partnerorganisationen. FiBL-Forscher untersuchen in Langzeitversuchen lokale und biologische Anbausysteme und bieten Expertise im Bereich der Marktentwicklung an. Quelle: https://www.fibl.org/de/ueber-uns.html",
        weblink: "https://www.fibl.org/de/",
        lat: 48.2086582275331,  
        lng: 16.355933269660643,
    },
    {
    
        nr: 14,
        user: "Plattform Footprint",
        Adresse: "Jandagasse 7 Haus 1, 1210 Wien",
        Mail: "office@footprint.att",
        Öffnungszeiten: "",
        intro: "Verein zur Förderung des Bewusstseins für den Ökologischen Fußabdruck",
        about: "Die Plattform Footprint ist eine Allianz von Umwelt- und Entwicklungspolitischen Organisationen, die den „Ökologischen Fußabdruck“ als wesentliche Maßzahl für die Zukunftsfähigkeit unserer Gesellschaft verankern will. Gemeinsam mit unseren Partnerorganisationen wollen wir durch Lobbying- und Aufklärungsarbeit zum Thema Footprint Bewusstseinsbildung, Handlungseinsicht und politischen Druck für nachhaltige gesellschaftliche Veränderung erzeugen. Quelle:https://www.footprint.at/",
        weblink: "https://www.footprint.at/",
        lat: 48.2862739216721, 
        lng: 16.410748398498882, 
    },
    {
    
        nr: 15,
        user: "Forum Wissenschaft & Umwelt",
        Adresse: "Palmgasse 3/2, 1150 Wien",
        Mail: "office@fwu.at",
        Öffnungszeiten: "",
        intro: "Gemeinnütziger Verein",
        about: "Wir sind eine unabhängige Vereinigung von Wissenschaftlerinnen und Wissenschaftlern, die das Ziel verfolgt, fachübergreifende Beiträge für eine zukunftsverträgliche Entwicklung von Umwelt, Gesellschaft und Wirtschaft zu leisten. Wir wollen der gesellschaftlichen Verantwortung unserer wissenschaftlichen Tätigkeit gerecht werden und bekennen uns zu Werten wie Vielfalt des Lebens und eine zukunftsfähige, humane Gesellschaft. Quelle: https://fwu.at/impressum/",
        weblink: "https://fwu.at/",
        lat: 48.19455632077085,  
        lng: 16.338057098496236,
    },
    {
    
        nr: 16,
        user: "Future Aid",
        Adresse: "nicht angegeben",
        Mail: "future-aid@future-aid.at",
        Öffnungszeiten: "",
        intro: "Die Zukunft braucht unsere Hilfe",
        about: "Future Aid ist eine private Non-Profit Initiative mit dem Ziel unsere Zukunft zu verbessern! Future Aid will sich von anderen Initiativen durch eine einzigartig umfassende Behandlung der Zukunftsthemen (Umwelt-Wirtschaft-Gesellschaft) unterscheiden! Quelle: https://www.future-aid.at/neu-bei-future-aid/%C3%BCber-future-aid/",
        weblink: "https://www.future-aid.at/",
        lat: 48.19866389758175, 
        lng: 16.34490446542928 ,
    },
    {
    
        nr: 17,
        user: "Generation Earth",
        Adresse: "Ottakringer Straße 114-116, 1160 Wien",
        Mail: "info@generationearth.at",
        Öffnungszeiten: "",
        intro: "Das WWF Netzwerk für junge, engagierte Menschen",
        about: "Generation Earth ist ein buntes Netzwerk aus jungen Menschen, das inspiriert, bildet und in Aktion tritt – für die Zukunft unseres Planeten. Bei unserem Action Leader Training lernst du grundlegende Skills und hast die Möglichkeit, dich in verschiedenen Bereichen auszuprobieren. Im Rahmen unserer Projekte treten wir gemeinsam mit dir in Aktion. Wir inspirieren dich mit Wildnis hautnah und zeigen dir in der Natur, was andere oft übersehen. Quelle: https://www.generationearth.at/",
        weblink: "https://www.generationearth.at/",
        lat: 48.21370721583878, 
        lng: 16.323157911988677,
    },
    {
    
        nr: 18,
        user: "Global 2000",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "office@global2000.at",
        Öffnungszeiten: "",
        intro: "Österreichs unabhängige Umweltschutzorganisation",
        about: "Wir setzen alles daran, unsere Welt zum Positiven zu verändern. Das heißt, egal, um welches Umweltschutz-Thema es geht: Wir setzen uns für das Gute und das Schöne ein. Denn es ist schön, bedenkenlos in einen Bio-Apfel zu beissen, den Kindern gesunde, vielfältige Lebensmittel bieten und intakte Lebensräume nützen zu können. Genauso schön ist es auch, mit gutem Gewissen einkaufen zu gehen, weil wir für faire Bedingungen im Handel sorgen und Menschen, Tiere und Pflanzen friedvoll zusammenleben. Quelle: https://www.global2000.at/ueber-global-2000",
        weblink: "https://www.global2000.at/",
        lat: 48.20559473723108,  
        lng: 16.350895198496506,
    },
    {
    
        nr: 19,
        user: "Schwendermarkt",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "initiative-schwendermarkt@gmx.at",
        Öffnungszeiten: "",
        intro: "Initiative zur Erhaltung und Belebung des Schwendermarktes",
        about: "Der Schwendermarkt ist der kleinste Markt in Wien. Interessante Geschäfte mit Bio und regionalen Produkten von bauern aus der Umgebung von Wien und dem weinviertel. gemütliche Atmosphäre in Markt Cafés, sehr gutes Essen inkl einer Vietnamesin, die super kocht, Marktstände mit Gemüse, Käse, Obst. tolles großes Café in hippem Blumenladen,.... Quelle: https://www.facebook.com/Schwendermarkt/reviews/?ref=page_internal Review of: Karin N. York",
        weblink: "http://www.schwendermarkt.at/",
        lat: 48.19097235033396, 
        lng: 16.326267103155473,
    },
    {
    
        nr: 20,
        user: "Jane Goodall Institut - Austria",
        Adresse: "Probusgasse 3, 1190 Wien",
        Mail: "office@janegoodall.at",
        Öffnungszeiten: "",
        intro: "für Naturschutz, Umweltbildung und Erforschung wildlebender Tiere",
        about: "Wir wollen das Überleben der letzten Schimpansen sichern. Unseren Projekten legen wir eine ganz alltägliche Erfahrung zugrunde: Ein Lächeln ist der kürzeste Weg zwischen zwei Menschen. Weil sich Herausforderungen besser gemeinsam bewältigen lassen, setzen wir auf enge Zusammenarbeit mit den Menschen vor Ort. Die Folge: der beste Austausch an Wissen und Verständnis für die Bedürfnisse der Einheimischen und für die regionalen Besonderheiten der Tier- und Pflanzenwelt. Quelle: https://janegoodall.at/was-wir-tun/",
        weblink: "https://janegoodall.at/",
        lat: 48.2552212909714,   
        lng: 16.356298763578838,
    },
    {
    
        nr: 21,
        user: "KEC",
        Adresse: "Schendlingerstraße 40, 6900 Bregenz",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 47.49522925643081,   
        lng: 9.71981471752438,
    },
    {
    
        nr: 21,
        user: "KEC",
        Adresse: "Pazmanitengasse 19, 1020 Wien",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 48.22255643075428,   
        lng: 16.385441990561716,
    },
    {
    
        nr: 21,
        user: "KEC",
        Adresse: "10. Oktober Straße 17, 9560 Feldkirchen",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 46.72394604602631,   
        lng: 14.095550729078235,
    },
    {
    
        nr: 22,
        user: "Klimabündnis Tirol",
        Adresse: "Müllerstraße 7, 6020 Innsbruck",
        Mail: "tirol@klimabuendnis.at",
        Öffnungszeiten: "",
        intro: "Wir setzen uns aktiv für Klimaschutz, Klimagerechtigkeit und einen nachhaltigen Lebensstil ein.",
        about: "Der Verein Klimabündnis Tirol ist Teil des größten kommunalen Klimaschutz-Netzwerks Europas. Die globale Partnerschaft verbindet mehr als 1.700 Gemeinden aus 27 Ländern in Europa mit Indigenen Organisationen des Amazonas-Regenwaldes.In Österreich haben sich über 1000 Gemeinden und Betriebe sowie über 600 Bildungseinrichtungen dem Klimabündnis angeschlossen. Quelle: https://tirol.klimabuendnis.at/ueber-uns/das-klimabuendnis-tirol",
        weblink: "https://tirol.klimabuendnis.at/",
        lat: 47.26157355303793,   
        lng: 11.394328026778537,
    },
    {
    
        nr: 23,
        user: "Klimabündnis Österreich",
        Adresse: "Prinz-Eugen-Straße 72/1.5, 1040 Wien",
        Mail: "office@klimabuendnis.at",
        Öffnungszeiten: "",
        intro: "Wir setzen uns aktiv für Klimaschutz, Klimagerechtigkeit und einen nachhaltigen Lebensstil ein.",
        about: "Wir sind das größte kommunale Klimaschutz-Netzwerk Österreichs. Wir setzen lokale Klimaschutz-Initiativen und schützen gleichzeitig den Amazonas-Regenwald. Und das bereits seit 1990. Das Klimabündnis ist eine globale Partnerschaft zum Schutz des Klimas und verbindet mittlerweile mehr als 1.700 Gemeinden in 27 Ländern Europas mit indigenen Völkern in Südamerika. Die gemeinsamen Ziele sind: Verringerung der Treibhausgas-Emissionen und Erhalt des Amazonas-Regenwaldes. Quelle: https://www.klimabuendnis.at/ueber-uns/kb-ueber-uns",
        weblink: "https://www.klimabuendnis.at/",
        lat: 48.189552457621275,   
        lng: 16.38080932310104,
    },
    {
    
        nr: 24,
        user: "Umwelt Beauftragte",
        Adresse: "Stephansplatz 6/5, 1010 Wien",
        Mail: "office@schoepfung.at",
        Öffnungszeiten: "",
        intro: "der Katholischern & Evangelischen Kirche Österreichs",
        about: "Wir setzen alles daran, unsere Welt zum Positiven zu verändern. Das heißt, egal, um welches Umweltschutz-Thema es geht: Wir setzen uns für das Gute und das Schöne ein. Denn es ist schön, bedenkenlos in einen Bio-Apfel zu beissen, den Kindern gesunde, vielfältige Lebensmittel bieten und intakte Lebensräume nützen zu können. Genauso schön ist es auch, mit gutem Gewissen einkaufen zu gehen, weil wir für faire Bedingungen im Handel sorgen und Menschen, Tiere und Pflanzen friedvoll zusammenleben. Quelle: https://www.global2000.at/ueber-global-2000",
        weblink: "https://www.schoepfung.at/",
        lat: 48.20884827727071,  
        lng: 16.37420801384071,
    },
    {
    
        nr: 25,
        user: "Lebensart",
        Adresse: "Wiener Straße 35, 3100 St. Pölten",
        Mail: "service@lebensart.at",
        Öffnungszeiten: "",
        intro: "Verlags GmbH",
        about: "nachhaltig.gut.leben. Das ist unsere Vision. Alle Menschen sollen heute und in Zukunft ein gutes Leben führen können. Deshalb haben wir den Lebensart Verlag gegründet. Wir berichten über nachhaltige Trends und bringen Hintergrundinformationen damit Sie eine gute Entscheidung treffen können. Vor allem zeigen wir Lösungsansätze von kreativen Menschen, wie ein gutes Leben aussehen kann und erzählen Geschichten, die inspirieren und zu eigenem Handeln anregen. Das alles lesen Sie in den Print und Online-Magazinen LEBENSART, BUSINESSART und über die Reiseplattform lebensart-reisen.at. Wir veranstalten jährlich die Wahl der Nachhaltigen GestalterInnen Österreichs, sind Mitveranstalter des CSR-Circle, kooperieren mit engagierten Menschen und Organisationen und unterstützen Partner in ihrer nachhaltigen Kommunikation. Quelle: https://www.lebensart-verlag.at/was-wir-tun-werte-vision-und-mission",
        weblink: "https://www.lebensart.at/",
        lat: 48.21892335496585,   
        lng: 15.660709850085858,
    },
];

const SOZIALES = [
    {
        nr: 1,
        user: "Concordia Sozialprojekte",
        Adresse: "Hochstettergasse 6, 1020 Wien",
        Mail: "office@concordia.or.at",
        Öffnungszeiten: "",
        intro: "Gemeinnützige Privatstiftung",
        about: "CONCORDIA ist eine internationale, unabhängige Nichtregierungsorganisation, die es sich zur Aufgabe gemacht hat, Kinder, Jugendliche und Familien in Not auf dem Weg in ein unabhängiges und verantwortungsvolles Leben zu unterstützen. Wir gehen dorthin, wo die Not am größten ist. Und wo andere nicht hingehen. Quelle: https://www.concordia.or.at/de/vision",
        weblink: "https://www.concordia.or.at/",
        lat:  48.22516071255066, 
        lng: 16.388036007608115,
    },
    {
        nr: 2,
        user: "Clean Clothes Kampagne",
        Adresse: "Laudongasse 40, 1080 Wien",
        Mail: "office@cleanclothes.at",
        Öffnungszeiten: "",
        intro: "Aktiv für faire Arbeitsbedingungen in der Bekleidungs- und Schuhproduktion weltweit",
        about: "Seit 1996 verfolgt die Clean Clothes Kampagne das Ziel, Arbeitsrechte in der globalen Bekleidungsindustrie zu verbessern. Wir klären BürgerInnen auf, drängen Unternehmen, mehr Verantwortung für ihre globalen Wertschöpfungsketten zu übernehmen und rufen die Regierungen dazu auf, Gesetze zu verabschieden, die Menschenrechtsverletzungen durch Unternehmen verhindern. Wir zeigen uns solidarisch mit den ArbeiterInnen, die unsere Kleidung herstellen und unterstützen ihren Kampf für bessere Arbeitsbedingungen. Der Clean Clothes Kampagne gehören sowohl Gewerkschaften als auch Nichtregierungsorganisationen (NROs) an. Diese arbeiten zu einem breiten Spektrum an Themen wie Frauenrechte, Verbraucherschutz und Armutsbekämpfung. Die Clean Clothes Kampagne ist Teil der internationalen Clean Clothes Campaign, die in 16 europäischen Ländern vertreten ist. Global arbeiten wir mit einem Netzwerk von über 200 Partnerorganisationen und Gewerkschaften in den Produktionsländern zusammen, um lokale Gegebenheiten und Lösungsansätze besser verstehen zu können. Dies hilft uns Kampagnen zu entwickeln, die die Forderungen der ArbeiterInnen vor Ort unterstützen. Wir arbeiten auch eng mit ähnlichen Arbeitsrechtsorganisationen in den USA, Kanada und Australien zusammen. Quelle: https://www.cleanclothes.at/de/ueber-uns/",
        weblink: "https://www.cleanclothes.at/de/",
        lat: 48.213375112250546,
        lng: 16.34533636157988

    },
    {
        nr: 3,
        user: "Das Gramm",
        Adresse: "Neutorgasse 7, 8010 Graz",
        Mail: "hallo@dasgramm.at",
        Öffnungszeiten: "Mo - Fr: 9:00 - 19:00, Sa: 10:00 - 17:00",
        intro: "Regionale Bio-Greisslerei",
        about: "Das Gramm, unsere regionale Greißlerei, wurde im April 2016 in der Neutorgasse eröffnet. Seither liegt unser Fokus auf regionalen Spezialitäten, unverpackten Lebensmitteln aus kontrolliert biologischem Anbau und einer kleinen, aber feinen Auswahl an Zero Waste Artikeln in den Bereichen Haushalt und Körperpflege. Produkte, die eine Verpackung brauchen, sind in Pfandgläsern oder Papiersackerln erhältlich, um so besonders Einwegplastik bestmöglich zu vermeiden. Bei uns kannst du genau diese Menge kaufen, die du auch wirklich brauchst – so gehen wir auch bei dir zuhause gegen Lebensmittelverschwendung vor. Unser “kleines Gramm” ist mehr als nur eine Greißlerei; es ist ein Ort zum Ankommen und Wohlfühlen, an dem du dich mit unserem Experten:innen-Team austauschen oder auch einfach in Ruhe die Atmosphäre auf dich wirken lassen kannst. Quelle: https://www.dasgramm.at/das-sind-wir/#wiewir",
        weblink: "https://www.dasgramm.at/",
        lat: 47.070688574948505, 
        lng: 15.436974564704707,
    },
    {
        nr: 4,
        user: "E. C. O.",
        Adresse: "Lakeside B07b, 9020 Klagenfurt",
        Mail: "office@e-c-o.at",
        Öffnungszeiten: "",
        intro: "Institut für Ökologie",
        about: "Wir begeistern uns für die Vielfalt der Natur und sichern ihren Erhalt auch für zukünftige Generationen. Als Forschungs- und Beratungsunternehmen für „Naturschutz im 21. Jahrhundert“ begleiten und unterstützen wir unsere internationalen und nationalen Partner:innen dabei, natürliche Lebensräume zu bewahren und zu verbessern, außergewöhnliche Naturerlebnisse zu ermöglichen und die Lebens- und Wirtschaftsbedingungen in den jeweiligen Regionen weiterzuentwickeln. Mit unseren ökologischen Fachplanungen, naturräumlichen Erhebungen, innovativen Kommunikationskonzepten und nachhaltiger Entwicklungszusammenarbeit setzen wir uns aktiv für die Erfüllung der globalen Sustainable Development Goals ein. Quelle: https://e-c-o.at/home.html",
        weblink: "https://e-c-o.at/home.html",
        lat: 46.61445647600445,
        lng: 14.263496343802236,
    },
    {
        nr: 5,
        user: "European Centre for Social Welfare Policy and Research",
        Adresse: "Berggasse 17, 1090 Wien",
        Mail: "ec@euro.centre.org",
        Öffnungszeiten: "",
        intro: "Intergovernmental organisation affiliated to the United Nations",
        about: "The European Centre for Social Welfare Policy and Research (the European Centre) is an intergovernmental organisation affiliated to the United Nations. Its purpose is to foster the collaboration in social welfare between governments and organisations by providing applied social science and comparative empirical research; forging the evidence-base for social policy making and mutual learning; initiating future-oriented public policy debates by networking. Quelle: https://www.euro.centre.org/aboutus",
        weblink: "https://www.euro.centre.org/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
        nr: 6,
        user: "Frauendomäne",
        Adresse: "Leopold-Ernst-Gasse, 1170 Wien",
        Mail: "hello@frauendomaene.at",
        Öffnungszeiten: "",
        intro: "Wir machen weibliche Kompeenz sichtbar",
        about: "Durch die Expert*innendatenbank Frauendomäne machen wir seit dem Jahr 2018 weibliche Kompetenz kollektiv sichtbar. Die Frauendomäne ist die erste Datenbank in Österreich, in die sich Expert*innen aus allen Fachbereichen kostenlos eintragen können und auf die alle Menschen und Organisationen kostenlos und uneingeschränkt zugreifen können. Wir unterstützen Organisator*innen, Unternehmen und Medienvertreter*innen dabei, ihre Panels, Seminare, Teams und Interviews geschlechterausgewogen und divers zu konzipieren.Durch unsere Arbeit machen wir darauf aufmerksam, dass homogene Gremien und Panels in der Öffentlichkeit und in der Berufswelt nicht mehr zeitgemäß sind. Wir wirken darauf hin, die Rahmenbedingungen an die Lebensrealitäten von allen Menschen anzupassen. Denn wir sind der Meinung, dass viele Menschen in der Art und Weise, wie unsere Welt gebaut ist, nicht mitgedacht werden. Wir streben nach einer Welt, in der Menschen eine Expertise und Kompetenz nach ihren Stärken und nicht nach ihrem Geschlecht aufbauen. Quelle: https://www.frauendomaene.at/about/",
        weblink: "https://www.frauendomaene.at/",
        lat: 48.222721538335115,   
        lng: 16.332347798360093,
    },
    {
        nr: 7,
        user: "HeForShe Vienna",
        Adresse: "Grundsteingasse 53, 1160 Wien",
        Mail: "nicht angegeben",
        Öffnungszeiten: "",
        intro: "Verein zur Unterstützung der HeForShe-Kampagne der Vereinten Nationen",
        about: "HeForShe heißt die im Jahr 2014 von UN Women ins Leben gerufene Solidaritätsbewegung, die auf die Beseitigung von Diskriminierungen aufgrund des Geschlechts und die gesellschaftliche Gleichstellung der Geschlechter abzielt. Die Botschaft der Kampagne ist einfach: Die Gleichstellung der Geschlechter ist keine Frauensache, sondern ein Menschenrecht und betrifft uns alle: Mädchen*, Frauen*, Buben* und Männer*. Daher müssen wir alle gemeinsam an diesem Ziel arbeiten. Im Vordergrund stehen die Bewusstseinsbildung und die Mobilisierung einer breiten Masse an Unterstützer*innen. Dadurch soll Druck auf Organisationen, Regierungen und die Gesellschaft ausgeübt werden, um eine Veränderung von innen heraus zu bewirken. Wie der Name der Kampagne bereits sagt, werden vor allem Männer* aufgefordert, sich aktiv einzubringen und ihre Stimme für die Gleichberechtigung und Gleichstellung der Geschlechter zu erheben. Die Gleichstellung der Geschlechter ist im 21. Jahrhundert nicht nur längst überfällig, sondern hat positive Auswirkungen auf alle Bereiche des gesellschaftlichen Lebens. Von Geschlechtergleichstellung profitieren wir alle. Quelle: https://www.heforshe-vienna.at/ueber-uns",
        weblink: "https://www.heforshe-vienna.at/",
        lat: 48.210617370764716,    
        lng: 16.333252868978143,
    },
    {
    
        nr: 8,
        user: "KEC",
        Adresse: "Schendlingerstraße 40, 6900 Bregenz",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 47.49522925643081,   
        lng: 9.71981471752438,
    },
    {
        nr: 9,
        user: "Lebensart",
        Adresse: "Wiener Straße 35, 3100 St. Pölten",
        Mail: "service@lebensart.at",
        Öffnungszeiten: "",
        intro: "Verlags GmbH",
        about: "nachhaltig.gut.leben. Das ist unsere Vision. Alle Menschen sollen heute und in Zukunft ein gutes Leben führen können. Deshalb haben wir den Lebensart Verlag gegründet. Wir berichten über nachhaltige Trends und bringen Hintergrundinformationen damit Sie eine gute Entscheidung treffen können. Vor allem zeigen wir Lösungsansätze von kreativen Menschen, wie ein gutes Leben aussehen kann und erzählen Geschichten, die inspirieren und zu eigenem Handeln anregen. Das alles lesen Sie in den Print und Online-Magazinen LEBENSART, BUSINESSART und über die Reiseplattform lebensart-reisen.at. Wir veranstalten jährlich die Wahl der Nachhaltigen GestalterInnen Österreichs, sind Mitveranstalter des CSR-Circle, kooperieren mit engagierten Menschen und Organisationen und unterstützen Partner in ihrer nachhaltigen Kommunikation. Quelle: https://www.lebensart-verlag.at/was-wir-tun-werte-vision-und-mission",
        weblink: "https://www.lebensart.at/",
        lat: 48.21892335496585,   
        lng: 15.660709850085858,
    },
    {
        nr: 10,
        user: "Mördinger Kommunikation- und Politikberatung",
        Adresse: "Wolkersbergenstraße 164, 1130 Wien",
        Mail: "nicht angegeben",
        Öffnungszeiten: "",
        intro: "Lobby für Energiewende und Nachhaltigkeit",
        about: "Energiewende und Nachhaltigkeit brauchen Unterstützung. Obwohl unzählige engagierte Menschen, Organisationen und Unternehmen an einer nachhaltigen Zukunft arbeiten, kommen wir nur langsam vom Fleck. Mal fehlt es am rechtlichen Rahmen, mal an der Aufmerksamkeit der Medien. Und manchmal bekommt die Energiewende Probleme mit Menschen vor Ort oder dem Naturschutz. Quelle: https://www.moerdinger.at/",
        weblink: "https://www.moerdinger.at/",
        lat: 48.17657903037716,   
        lng: 16.274120095963383,
    },
    {
        nr: 11,
        user: "social city wien",
        Adresse: "Sachsenplatz 4-6, 1200 Wien",
        Mail: "office@socialcity.atn",
        Öffnungszeiten: "",
        intro: "Unabhängige Plattform für gesellschaftliche Innovation",
        about: "Die Plattform „Social City Wien“ bringt Wiens kluge Köpfe mit vielen sozialen Ideen zusammen, schafft ein Netzwerk für soziales Engagement und bildet einen nahrhaften Boden für gesellschaftliche Innovationen. Wir sind die Drehscheibe für gesellschaftliche Innovation, weil soziale Entwicklung uns alle nachhaltig weiterbringt. Wir machen soziale Innovation einfacher, optimieren Abläufe zwischen den AkteurInnen und steigern so die Effizienz der innovativen Prozesse. Quelle: http://www.socialcity.at/de/ueber-uns.html",
        weblink: "http://www.socialcity.at/de/",
        lat: 48.23219129176,    
        lng: 16.37598792480044,
    },
    {
        nr: 12,
        user: "Team CU2 SustainAgiency",
        Adresse: "Gardegasse 6/27, 10700 Wien",
        Mail: "info@cu2.team",
        Öffnungszeiten: "",
        intro: "Das Magazin der CU2 Kreativagrntur",
        about: "In über 23 Jahren an Erfahrung in der (Markt-)Kommunikation, u. a. mit den Schwerpunkten Packaging-Design & Prototyping, CI/CD Development und Location-ReDesign, in denen die CU2 Kreativagentur mannigfaltige große, kleine, spannende, fade, innovative, unterhaltsame und ernsthafte Projekte entwickeln und realisieren konnte, entstand in ihr die fixe Überzeugung: » Wir tun alles, was wir können. Und was wir können, machen wir wirklich gut. Mit NetzAmWerk realisieren wir Projekte im Teamwork – für und mit anderen. « Quelle: https://cu2.team/mission/",
        weblink: "https://cu2.team/",
        lat: 48.20500463736926,     
        lng: 16.355892035897163,
    },
    {
        nr: 13,
        user: "Torismus & Klimafit",
        Adresse: "Gärtnergasse 4c, 2103 Langenzersdorf",
        Mail: "office@tourismusklimafit.at",
        Öffnungszeiten: "",
        intro: "Mit einer klimafitten Angebots- und Produktentwicklung zum wirtschaftlich nachhaltigen Erfolg",
        about: "Der Klimawandel wirkt auf Land- Wasser- oder Forstwirtschaft und daher in vielen Bereichen, die unmittelbar mit dem Tourismus zusammenhängen. Das Reisen ist sehnsuchtsvoller Zeitvertreib und wichtiger Wirtschaftsfaktor, hat aber wiederum Auswirkungen auf Umwelt und Klima. Die Folgen des Klimawandels sind allgegenwärtig. Das Problembewusstsein in der Bevölkerung und bei den Gästen steigt, der „Reise-Klima-Fußabdruck“ avisiert zum Auswahl- und Entscheidungskriterium für eine bestimmte Region. Touristiker und Regionalentwickler sind sensibilisiert, stehen aber vor großen Herausforderungen. Verantwortungsvoller, klimafitter Tourismus bietet Chancen für eine umwelt- und sozialverträgliche wirtschaftliche Entwicklung. Wir unterstützen unsere Kunden mit nachhaltigen Mobilitätslösungen, implementieren klimafitte Angebote und kreative Produkte entlang der touristischen Dienstleistungskette, vernetzen zu klimafreundlichen Unternehmen, Institutionen sowie Förderstellen und motivieren Anbieter ebenso wie Nachfrager zu einem klimabewussten Umdenken. Quelle: https://tourismusklimafit.at/",
        weblink: "https://tourismusklimafit.at/",
        lat: 48.30210650588059,     
        lng: 16.369665141994382,
    },
    {
        nr: 14,
        user: "Transition Austria",
        Adresse: "Burgring 6/2, 8010 Graz",
        Mail: "office@transition.at",
        Öffnungszeiten: "",
        intro: "Wandelinitiativen: Überblicken – Verstehen – Mitmachen.",
        about: "Transition Austria ist eine Plattform und Vernetzung von und für Initiativen des Wandels in Österreich.  Diese Initiativen sind von der Idee der Transition Bewegung inspiriert.  Sie wurden von Einzelpersonen, Gruppen, Initiativen, NGO’s oder Wirtschaftsbetrieben initiiert. Sie suchen Lösungen im Alltag und neue Formen des Zusammenslebens auf kommunaler Ebene. Sie agieren nach dem Motto “Global Denken, Lokal handeln”. Quelle: https://transition.at/transition-austria/",
        weblink: "https://tourismusklimafit.at/",
        lat: 47.07180036574457,      
        lng: 15.444181955456818,
    },
    {
        nr: 15,
        user: "Umblick",
        Adresse: "Hartlgasse 9/13, 1200 Wien",
        Mail: "buero@umblick.at",
        Öffnungszeiten: "",
        intro: "Umweltbildung - Umwelt, Abfall, Energie, Nachhaltigkeit, Mobilität",
        about: "Umblick steht für umfassende Weiterentwicklung im Hinblick auf Themengebiete der Umwelt und Nachhaltigkeit. Wir konzentrieren uns darauf, Menschen und Organisationen bei der Mitgestaltung einer nachhaltigen Zukunft zu unterstützen. Durch unser interdisziplinäres Team erreichen wir Ihre Ziele effizient unter Einbeziehung unterschiedlicher Blickwinkel und kombinierter Ansätze.  Wir schließen die Lücke von reinem Wissen hin zum effektiven Umsetzen. Um­blick hat sich zum Ziel gesetzt Men­schen dabei zu er­mutigen ihre Selbst­­wirk­sam­keit zu be­grei­fen und ihre Hand­lun­gen als wich­tigen Bei­trag für das ge­mein­same Ge­stal­ten einer nach­hal­tig­eren Welt zu er­le­ben. Um diese Mis­sion­en zu er­fül­len be­gin­nen wir be­reits bei den Jüng­sten im Kinder­garten und bieten Umweltbildung wie z.B. Umweltworkshops bis hin zum Pen­sions­al­ter an. Quelle: https://umblick.at/bildung/ueber-uns/",
        weblink: "https://umblick.at/",
        lat: 48.23160827990701,     
        lng: 16.373425396510783 ,
    },
    {
        nr: 16,
        user: "Verband der Akademikerinnen Österreichs",
        Adresse: "Reitschulgasse 2, 1010 Wien",
        Mail: "office.vaoe@aon.at",
        Öffnungszeiten: "",
        intro: "Austrian Federation of University Women",
        about: "Der Verband der Akademikerinnen Österreichs eröffnet qualifizierten und engagierten Frauen internationale und interdisziplinäre Beziehungen und ermutigt zu Qualität, Verantwortung, Respekt und Selbstvertrauen. Der VAÖ, Verband der Akademikerinnen Österreichs, mit Verbandssitz in Wien besteht seit dem Jahr 1922. Er ist die  größte Vereinigung von akademisch gebildeten Frauen Österreichs, mit 6 Landesverbänden (NÖ und Burgenland ist dem LV Wien angegliedert, Vorarlberg ist mit dem LV Tirol vernetzt). Quelle: https://www.vaoe.at/",
        weblink: "https://www.vaoe.at/",
        lat: 48.207431780638956,      
        lng: 16.367350430894483,
    },




];


const GESUNDHEIT = [
    {
        nr: 1,
        user: "AIDS Hilfe Wien",
        Adresse: "Mariahilfer Gürtel 4, 1060 Wien",
        Mail: "office@aids-hilfe-wien.at",
        Öffnungszeiten: "",
        intro: "Test- und Beratungszentrum",
        about: "Die Aids Hilfe Wien hat ihren Sitz seit 1997 – also seit mittlerweile über 20 Jahren – im Aids Hilfe Haus am Mariahilfer Gürtel 4, 1060 Wien. Von hier aus betreuen wir unsere Angebote in Wien, Niederösterreich und dem Burgenland. In dieser Zeit hat sich die Aids Hilfe Wien zu einer der bekanntesten Anlaufstellen für sexuelle Gesundheit  entwickelt. Heute findet man Expertise zu HIV/AIDS und anderen sexuell übertragbaren Krankheiten, inklusive aller Testmöglichkeiten, unter einem Dach vereint mit psychologischer Beratung und Betreuung im Aids Hilfe Haus. Das heißt, wir mussten und konnten unser Angebot schrittweise ausweiten, von der Fokussierung auf HIV-bezogene Angebote (Test, Beratung, Therapievermittlung, Betreuung usw.) hin zu Testungen auf alle großen sexuell übertragbaren Krankheiten (STDs): HIV, Syphilis, Tripper, Chlamydien und virale Hepatitis („Big five“). Quelle: https://aids.at/ueber-uns/",
        weblink: "http://www.aids.at/",
        lat: 48.19128312611382, 
        lng: 16.338536663428904, 
    },
    {
        nr: 2,
        user: "Samariterbund",
        Adresse: "Hollergasse 2-6, 1150 Wien",
        Mail: "info@samariterbund.net",
        Öffnungszeiten: "",
        intro: "Arbeiter - Samariter - Bund Österreichs",
        about: "Seit der Gründung vor 90 Jahren ist der Arbeiter-Samariter-Bund Österreichs seiner obersten Verpflichtung treu geblieben: Die haupt- und ehrenamtlichen MitarbeiterInnen der Non-Profit-Organisation leisten für ältere Menschen, Kranke, Verletzte und in Not Geratene Hilfe von Mensch zu Mensch – unabhängig von deren ethnischer Zugehörigkeit, Religion und Weltanschauung. Das Aufgabengebiet des Samariterbundes hat sich in den vergangenen Jahren enorm erweitert – vom klassischen Rettungs- und Krankentransport hin zu Gesundheits- und sozialen Diensten wie etwa Pflege, Aslywerber- und Obdachlosenbetreuung, sowie Entwicklungszusammenarbeit, Katastrophenhilfsdienst und Jugendarbeit. Quelle: https://www.samariterbund.net/ueber-uns/",
        weblink: "https://www.samariterbund.net/",
        lat: 48.18492431149642, 
        lng: 16.32628935548441,

    },
    {
        nr: 3,
        user: "Das Gramm",
        Adresse: "Neutorgasse 7, 8010 Graz",
        Mail: "hallo@dasgramm.at",
        Öffnungszeiten: "Mo - Fr: 9:00 - 19:00, Sa: 10:00 - 17:00",
        intro: "Regionale Bio-Greisslerei",
        about: "Das Gramm, unsere regionale Greißlerei, wurde im April 2016 in der Neutorgasse eröffnet. Seither liegt unser Fokus auf regionalen Spezialitäten, unverpackten Lebensmitteln aus kontrolliert biologischem Anbau und einer kleinen, aber feinen Auswahl an Zero Waste Artikeln in den Bereichen Haushalt und Körperpflege. Produkte, die eine Verpackung brauchen, sind in Pfandgläsern oder Papiersackerln erhältlich, um so besonders Einwegplastik bestmöglich zu vermeiden. Bei uns kannst du genau diese Menge kaufen, die du auch wirklich brauchst – so gehen wir auch bei dir zuhause gegen Lebensmittelverschwendung vor. Unser “kleines Gramm” ist mehr als nur eine Greißlerei; es ist ein Ort zum Ankommen und Wohlfühlen, an dem du dich mit unserem Experten:innen-Team austauschen oder auch einfach in Ruhe die Atmosphäre auf dich wirken lassen kannst. Quelle: https://www.dasgramm.at/das-sind-wir/#wiewir",
        weblink: "https://www.dasgramm.at/",
        lat: 47.070688574948505, 
        lng: 15.436974564704707,
    },
    {
        nr: 4,
        user: "Ernährungsrat Wien",
        Adresse: "nicht angegeben",
        Mail: "kontakt@ernaehrungsrat-wien.at",
        Öffnungszeiten: "",
        intro: "vernetzen - verstehen - verändern",
        about: "Wir sind ein zivilgesellschaftlicher Zusammenschluss von, derzeit ca. 30, engagierten Menschen aus den verschiedensten Bereichen des Wiener Ernährungssystems: Gastronomie und Forschung, urbane Landwirtschaft und zivilgesellschaftliche Organisationen, Beratung und Interessensvertretung, Gemeinschaftsverpflegung und Food Coops. Diese Hintergründe und die Auseinandersetzung mit der eigenen Ernährung und deren Auswirkungen - der persönliche Bezug zu den Themen Lebensmittel und Ernährung hat unsere Gruppe zusammengeführt. Uns verbindet das gemeinsame Ziel, durch den Ernährungsrat Wien zu einem ökologisch zukunftsfähigen und sozial gerechten Ernährungssystem in der Wiener Stadt-Region beizutragen. Jedes (neue) Mitglied bereichert den Ernährungsrat Wien mit neuen Perspektiven. Geben wir der Zivilgesellschaft gemeinsam eine starke Stimme für ein demokratisches, sozial gerechtes und ökologisch zukunftsfähiges Ernährungssystem! Quelle: https://ernaehrungsrat-wien.at/ueber-uns/wir/",
        weblink: "https://ernaehrungsrat-wien.at/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
        nr: 5,
        user: "European Centre for Social Welfare Policy and Research",
        Adresse: "Berggasse 17, 1090 Wien",
        Mail: "ec@euro.centre.org",
        Öffnungszeiten: "",
        intro: "Intergovernmental organisation affiliated to the United Nations",
        about: "The European Centre for Social Welfare Policy and Research (the European Centre) is an intergovernmental organisation affiliated to the United Nations. Its purpose is to foster the collaboration in social welfare between governments and organisations by providing applied social science and comparative empirical research; forging the evidence-base for social policy making and mutual learning; initiating future-oriented public policy debates by networking. Quelle: https://www.euro.centre.org/aboutus",
        weblink: "https://www.euro.centre.org/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
        nr: 6,
        user: "Lebensart",
        Adresse: "Wiener Straße 35, 3100 St. Pölten",
        Mail: "service@lebensart.at",
        Öffnungszeiten: "",
        intro: "Verlags GmbH",
        about: "nachhaltig.gut.leben. Das ist unsere Vision. Alle Menschen sollen heute und in Zukunft ein gutes Leben führen können. Deshalb haben wir den Lebensart Verlag gegründet. Wir berichten über nachhaltige Trends und bringen Hintergrundinformationen damit Sie eine gute Entscheidung treffen können. Vor allem zeigen wir Lösungsansätze von kreativen Menschen, wie ein gutes Leben aussehen kann und erzählen Geschichten, die inspirieren und zu eigenem Handeln anregen. Das alles lesen Sie in den Print und Online-Magazinen LEBENSART, BUSINESSART und über die Reiseplattform lebensart-reisen.at. Wir veranstalten jährlich die Wahl der Nachhaltigen GestalterInnen Österreichs, sind Mitveranstalter des CSR-Circle, kooperieren mit engagierten Menschen und Organisationen und unterstützen Partner in ihrer nachhaltigen Kommunikation. Quelle: https://www.lebensart-verlag.at/was-wir-tun-werte-vision-und-mission",
        weblink: "https://www.lebensart.at/",
        lat: 48.21892335496585,   
        lng: 15.660709850085858,
    },
    {
        nr: 7,
        user: "Land schafft Leben",
        Adresse: "Erzherzog-Johann-Str. 248b, 8970 Schladming",
        Mail: "post@landschafftleben.at",
        Öffnungszeiten: "",
        intro: "ist österreichischen Lebensmitteln auf der Spur!",
        about: "Wir zeigen den Konsumentinnen und Konsumenten transparent und ohne zu werten, wie in Österreich Lebensmittel produziert werden, wie die Produktion vor Ort im Bauernhof erfolgt, wie die Verarbeitung funktioniert und wie das fertige Produkt schließlich im Lebensmittelhandel landet. Für die Konsumentinnen und Konsumenten ergibt sich durch die leicht nachvollziehbar und ausführlich aufbereiteten Informationen ein neues Verständnis für die Zusammenhänge innerhalb der Lebensmittelproduktion und damit ein höheres Wert-Bewusstsein für österreichische Lebensmittel. Quelle: https://www.landschafftleben.at/service-aktuelles/organisation/verein",
        weblink: "https://www.landschafftleben.at/",
        lat: 47.393776442137025,  
        lng: 13.687645470807377,
    },
    {
        nr: 7,
        user: "Land schafft Leben",
        Adresse: "Schwarzenbergstraße 8/1, 1010 Wien",
        Mail: "post@landschafftleben.at",
        Öffnungszeiten: "",
        intro: "ist österreichischen Lebensmitteln auf der Spur!",
        about: "Wir zeigen den Konsumentinnen und Konsumenten transparent und ohne zu werten, wie in Österreich Lebensmittel produziert werden, wie die Produktion vor Ort im Bauernhof erfolgt, wie die Verarbeitung funktioniert und wie das fertige Produkt schließlich im Lebensmittelhandel landet. Für die Konsumentinnen und Konsumenten ergibt sich durch die leicht nachvollziehbar und ausführlich aufbereiteten Informationen ein neues Verständnis für die Zusammenhänge innerhalb der Lebensmittelproduktion und damit ein höheres Wert-Bewusstsein für österreichische Lebensmittel. Quelle: https://www.landschafftleben.at/service-aktuelles/organisation/verein",
        weblink: "https://www.landschafftleben.at/",
        lat: 48.20249394560691,   
        lng: 16.37390564808664,
    },
    {
        nr: 8,
        user: "MATISSEK Innovation Consulting",
        Adresse: "Schönbrunner Straße 178/2,, 1120 Wien",
        Mail: "office@matissek.at",
        Öffnungszeiten: "",
        intro: "Michael Matissek, MSc",
        about: "MATISSEK Innovation Consulting bietet ihnen Service und Beratung im Bereich Forschungs- und Innovationsberatung. Meine Kernkompetenz ist die interdisziplinäre – wissenschaftliche, wirtschaftliche und nachhaltige – Betreuung ihres Projektes. Quelle: https://firmen.wko.at/michael-matissek%2c-msc-matissek-innovation-consulting/wien/?firmaid=017e38dd-b16b-4087-bcef-d618a98e7d68&name=michael+matissek,+msc&standort=wien+(bundesland)",
        weblink: "https://firmen.wko.at/michael-matissek%2c-msc-matissek-innovation-consulting/wien/?firmaid=017e38dd-b16b-4087-bcef-d618a98e7d68&name=michael+matissek,+msc&standort=wien+(bundesland)",
        lat: 48.18610794055923,    
        lng: 16.338176340687966,
    },
    {
        nr: 9,
        user: "Rote Nasen Clowndoctors Austria",
        Adresse: "Wattgasse 48, 1170 Wien",
        Mail: "office@rotenasen.at",
        Öffnungszeiten: "",
        intro: "Partner of RED NOSES International",
        about: "Seit 1994 bringen ROTE NASEN Clowndoctors ein Lachen dorthin, wo es vielleicht nicht vermutet, aber dringend gebraucht wird: Zu kleinen Patient*innen auf Stationen der Kinderchirurgie, der Kardiologie und auf Onkologie- und Intensivstationen, zu Kindern und Jugendlichen in sonder- und heilpädagogischen Einrichtungen und auch zu Erwachsenen und Senior*innen in Pflege- und Rehabilitationszentren. ROTE NASEN Clowndoctors sind überall, wo Menschen auch seelische Unterstützung brauchen, um wieder gesund zu werden und neue Lebensfreude zu finden. Quelle: https://www.rotenasen.at/clownbesuche/was-wir-tun/",
        weblink: "https://www.rotenasen.at/",
        lat: 48.217990405674854,     
        lng: 16.32065989041571,
    },
    {
        nr: 10,
        user: "RED NOSES Clowndoctors International",
        Adresse: "Wattgasse 48, 1170 Wien",
        Mail: "office@rotenasen.at",
        Öffnungszeiten: "",
        intro: "Partner of RED NOSES International",
        about: "Die Idee und der Erfolg von ROTE NASEN in Österreich sprachen sich auch bald international herum. Andere Länder wie Ungarn und die Tschechische Republik wollten ROTE NASEN ebenfalls etablieren. Das Interesse wurde immer größer und immer mehr Partnerorganisationen kamen hinzu. Die gemeinnützige Privatstiftung RED NOSES Clowndoctors International wurde 2003 von ROTE NASEN Österreich ins Leben gerufen. RED NOSES International umfasst neben Österreich Partnerorganisationen in Ungarn, der Tschechischen Republik, der Slowakei, Deutschland, Slowenien, Kroatien, Polen, Litauen, Palästina und Jordanien. Quelle: https://www.rotenasen.at/ueber-uns/geschichte/",
        weblink: "https://www.rotenasen.at/",
        lat: 48.217990405674854,     
        lng: 16.32065989041571,
    },
    {
        nr: 11,
        user: "Umblick",
        Adresse: "Hartlgasse 9/13, 1200 Wien",
        Mail: "buero@umblick.at",
        Öffnungszeiten: "",
        intro: "Umweltbildung - Umwelt, Abfall, Energie, Nachhaltigkeit, Mobilität",
        about: "Umblick steht für umfassende Weiterentwicklung im Hinblick auf Themengebiete der Umwelt und Nachhaltigkeit. Wir konzentrieren uns darauf, Menschen und Organisationen bei der Mitgestaltung einer nachhaltigen Zukunft zu unterstützen. Durch unser interdisziplinäres Team erreichen wir Ihre Ziele effizient unter Einbeziehung unterschiedlicher Blickwinkel und kombinierter Ansätze.  Wir schließen die Lücke von reinem Wissen hin zum effektiven Umsetzen. Um­blick hat sich zum Ziel gesetzt Men­schen dabei zu er­mutigen ihre Selbst­­wirk­sam­keit zu be­grei­fen und ihre Hand­lun­gen als wich­tigen Bei­trag für das ge­mein­same Ge­stal­ten einer nach­hal­tig­eren Welt zu er­le­ben. Um diese Mis­sion­en zu er­fül­len be­gin­nen wir be­reits bei den Jüng­sten im Kinder­garten und bieten Umweltbildung wie z.B. Umweltworkshops bis hin zum Pen­sions­al­ter an. Quelle: https://umblick.at/bildung/ueber-uns/",
        weblink: "https://umblick.at/",
        lat: 48.23160827990701,     
        lng: 16.373425396510783 ,
    },
    {
        nr: 12,
        user: "Verband der Akademikerinnen Österreichs",
        Adresse: "Reitschulgasse 2, 1010 Wien",
        Mail: "office.vaoe@aon.at",
        Öffnungszeiten: "",
        intro: "Austrian Federation of University Women",
        about: "Der Verband der Akademikerinnen Österreichs eröffnet qualifizierten und engagierten Frauen internationale und interdisziplinäre Beziehungen und ermutigt zu Qualität, Verantwortung, Respekt und Selbstvertrauen. Der VAÖ, Verband der Akademikerinnen Österreichs, mit Verbandssitz in Wien besteht seit dem Jahr 1922. Er ist die  größte Vereinigung von akademisch gebildeten Frauen Österreichs, mit 6 Landesverbänden (NÖ und Burgenland ist dem LV Wien angegliedert, Vorarlberg ist mit dem LV Tirol vernetzt). Quelle: https://www.vaoe.at/",
        weblink: "https://www.vaoe.at/",
        lat: 48.207431780638956,      
        lng: 16.367350430894483,
    },
    {
        nr: 13,
        user: "iamgood",
        Adresse: "Hirschengasse 16/2/7, 1060 Wien",
        Mail: "say@iamgood.cc",
        Öffnungszeiten: "",
        intro: "Plattform für Persönlichkeitsentwicklung",
        about: "Education & creation of a broader awareness for environmental protection. iamgood is an event series and a community for all curious minds, who want to live a more meaningful life. Once every two months, we organize iamgood events. We invite two different speakers to give inspirational talks and actionable insights on a broad range of personal development topics. Also, we love music, that’s why we invite great musicians to our events.  Each iamgood event takes place at a new location in Vienna and is free of charge. Quelle: https://iamgood.cc/",
        weblink: "hhttps://iamgood.cc/",
        lat: 48.19468386474175,      
        lng: 16.34782394068816,
    },
    {
        nr: 14,
        user: "plan:g",
        Adresse: "Belruptstraße 21, 6900 Bregenz",
        Mail: "impressum@plan-g.at",
        Öffnungszeiten: "",
        intro: "Partnerschaft für globale Gesundheit",
        about: "plan:g entstand 1958 als Leprahilfswerk. Wir sind eine Stiftung kirchlichen Rechts. Durch Hinterlegung der Errichtungsurkunde haben wir im staatlichen Bereich Rechtspersönlichkeit als Körperschaft öffentlichen Rechts (KöR). Wir verstehen uns als Menschenrechtswerk der katholischen Kirche im Gesundheitssektor und arbeiten in der Entwicklungszusammenarbeit. Quelle: https://plan-g.at/ueber-uns/wer-wir-sind",
        weblink: "https://plan-g.at/",
        lat: 47.50392033003685,      
        lng: 9.750940949918776,
    },
    {
        nr: 15,
        user: "pro mente austria",
        Adresse: "Lonstorferplatz 1, 4020 Linz",
        Mail: "office@promenteaustria.at",
        Öffnungszeiten: "",
        intro: "Österreichischer Dachverband für Vereine und Gesellschaften für psychische und soziale Gesundheit.",
        about: "Wir vertreten die gemeinsamen Ziele unserer Mitglieder sowohl in Österreich als auch im Ausland und bieten eine Plattform für den unkomplizierten Informationsaustausch. Nach außen stehen wir als Ansprechpartner für alle Stakeholder im Bereich der psychischen und sozialen Gesundheit zur Verfügung. Unser Ziel ist es, die Stellung von Menschen mit psychischen oder psycho-sozialen Problemen in der Gesellschaft zu verbessern und ihrem sozialen Umfeld beizustehen. Dafür unterstützen wir auch andere Organisationen. Ein besonderes Ziel ist die Einhaltung der Menschenrechte und im Besonderen der UN-Konvention über die Rechte von Menschen mit Behinderungen und des europäischen Mental Health Pacts. Daher fördern und fordern wir unparteilich und überkonfessionell die Inklusion und Partizipation aller Menschen und begrüßen ihre Vielfalt. Quelle: https://www.promenteaustria.at/de/pro-mente-austria/leitbild/",
        weblink: "https://www.promenteaustria.at/de/home/",
        lat: 48.29376381590077,     
        lng: 14.3140221806237 ,
    },
    {
        nr: 16,
        user: "AGU",
        Adresse: "Große Mohrengasse 39/6, 1020 Wien",
        Mail: "info@aegu.net",
        Öffnungszeiten: "",
        intro: "Ärztinnen und Ärzte für eine gesunde Umwelt",
        about: "Als österreichische Sektion der ISDE (International Society of Doctors for the Environment) sind wir eine parteipolitisch unabhängige Organisation von Ärztinnen und Ärzten, die sich für Belange des Umweltschutzes aus ärztlicher Sicht einsetzen. Quelle: https://www.aegu.net/uber-uns.html",
        weblink: "https://www.aegu.net/",
        lat: 48.21859534694276,      
        lng: 16.384384972677523,
    },
    {
        nr: 17,
        user: "Österreichisches Rotes Kreuz",
        Adresse: "Wiedner Hauptstraße 32, 1041 Wien",
        Mail: "service@roteskreuz.at",
        Öffnungszeiten: "",
        intro: "Partner of RED NOSES International",
        about: "Das Rote Kreuz ist die größte humanitäre Nonprofit-Organisation in Österreich: wir sind für Sie da. Aus Liebe zum Menschen. Quelle: https://www.roteskreuz.at/home",
        weblink: "https://www.roteskreuz.at/home/",
        lat: 48.19564257268525,     
        lng: 16.36704546342908,
    },
];
