const STADTENTWICKLUNG = [
    {
      nr: 1,
      user: "Das Gramm",
      Adresse: "Neutorgasse 7, 8010 Graz",
      Mail: "hallo@dasgramm.at",
      Öffnungszeiten: "Mo - Fr: 9:00 - 19:00, Sa: 10:00 - 17:00",
      intro: "Regionale Bio-Greisslerei",
      about: "Das Gramm, unsere regionale Greißlerei, wurde im April 2016 in der Neutorgasse eröffnet. Seither liegt unser Fokus auf regionalen Spezialitäten, unverpackten Lebensmitteln aus kontrolliert biologischem Anbau und einer kleinen, aber feinen Auswahl an Zero Waste Artikeln in den Bereichen Haushalt und Körperpflege. Produkte, die eine Verpackung brauchen, sind in Pfandgläsern oder Papiersackerln erhältlich, um so besonders Einwegplastik bestmöglich zu vermeiden. Bei uns kannst du genau diese Menge kaufen, die du auch wirklich brauchst – so gehen wir auch bei dir zuhause gegen Lebensmittelverschwendung vor. Unser “kleines Gramm” ist mehr als nur eine Greißlerei; es ist ein Ort zum Ankommen und Wohlfühlen, an dem du dich mit unserem Experten:innen-Team austauschen oder auch einfach in Ruhe die Atmosphäre auf dich wirken lassen kannst. Quelle: https://www.dasgramm.at/das-sind-wir/#wiewir",
      weblink: "https://www.dasgramm.at/",
      lat: 47.070688574948505, 
      lng: 15.436974564704707,
    }
   ];

const UMWELT = [
    {
        nr: 1,
        user: "ARGE Abfallvermeidung",
        Adresse: "Puchstraße 41, 8010 Graz",
        Mail: "office@arge.at",
        Öffnungszeiten: "",
        intro: "Umweltschutzunternehmen",
        about: "Die ARGE konzipiert und implementiert Projekte in den Bereichen Abfallvermeidung, Ressourcenschonung und nachhaltige Entwicklung. Die ARGE ist eine Non-Profit Organisation, die im Jahr 1982 gegründet wurde. Wir konzipieren und organisieren regionale, nationale und internationale Projekte im Bereich nachhaltige Entwicklung und kommunale Abfallwirtschaft. Unsere erste Priorität ist -wie unser Name schon sagt- die Abfallvermeidung. Der schonende Umgang mit Ressourcen und der Schutz unserer Umwelt ist Fokus unserer Arbeit. Wir betrachten die Abfall- und Ressourcenwirtschaft im sozialen, ökologischen und ökonomischen Kontext. Ein wesentlicher Teil unserer Aktivitäten ist daher die Kooperation mit sozialwirtschaftlichen Einrichtungen und die Schaffung von Arbeitsplätzen im Umweltbereich. Quelle: https://www.facebook.com/ArgeAbfallvermeidung/",
        weblink: "https://www.arge.at/",
        lat:  47.05001107528067, 
        lng: 15.436887611278067,
    },
    {
        nr: 2,
        user: "ARGE Schöpfungsveranstaltung",
        Adresse: "Petersplatz 1, 1010 Wien",
        Mail: "office@argeschoepfung.at",
        Öffnungszeiten: "",
        intro: "Kirchliche Umweltarbeit",
        about: "Seit über 25 Jahren ist die ARGE Schöpfungsverantwortung in Kirche und Gesellschaft aktiv. Sie ist Initiator der kirchlichen Umweltarbeit in Österreich und Mitbegründer des EUROPEAN CHRISTIAN ENVIRONMENTAL NETWORKS (ECEN). Im Rahmen der Initiative zur Einführung der SCHÖPFUNGSZEIT agiert sie international. Die Umsetzung erfolgt projektbezogen mit einem Team von engagierten Mitarbeitern, Experten aus Natur- und Geisteswissenschaften. Mit einem laufenden Bildungsprogramm und ökosozialen Handlungsmodellen begleitet und unterstützt sie engagierte Personen und Institutionen sowie einschlägige Netzwerke. Als Gründungsmitglied des EUROPÄISCHEN CHRISTLICHEN UMWELTNETZWERKES (ECEN) bietet sie Partizipation am internationalen kirchlichen Umweltgeschehen. Zahlreiche Initiativen erfolgen in Kooperation mit Umwelt- und Entwicklungsorganisationen. Für Ihre Tätigkeit wurde die ARGE Schöpfungsverantwortung mit dem Staatspreis der Republik Österreich, dem Konrad-Lorenz-Preis ausgezeichnet und erhielt für die Wahrnehmung der Trias des „Konziliaren Prozesses für Gerechtigkeit – Frieden – Bewahrung der Schöpfung“ die Europäische Friedensrose Waldhausen. Quelle: https://www.argeschoepfung.at/ueber-uns/ueberblick.html",
        weblink: "https://www.argeschoepfung.at/",
        lat: 48.209195875185195, 
        lng: 16.370094671021324

    },
    {
        nr: 3,
        user: "ARCHE NOAH",
        Adresse: "Obere Straße 40, 3553 Schiltern",
        Mail: "info@arche-noah.at",
        Öffnungszeiten: "",
        intro: "Verein für Erhalt und Entwicklung der Kulturpflanzenvielfalt",
        about: "Seit über 30 Jahren setzen sich Menschen im Verein ARCHE NOAH für den Erhalt und die Entwicklung der Kulturpflanzenvielfalt ein. Der Verein ARCHE NOAH entstand 1989 (Geschichte des Vereins) auf Initiative von GärtnerInnen, BäuerInnen und JournalistInnen, die das Saatgut als Grundlage der Ernährung buchstäblich wieder in die eigenen Hände nehmen wollten. Denn: Seit 1900 ist die Vielfalt unserer Kulturpflanzen durch die Industrialisierung der Landwirtschaft weltweit dramatisch – um 75% – zurückgegangen (Details zum Verlust der Vielfalt)! Heute gefährden Gentechnik, Saatgut-Monopole, Klimawandel und Kriege dieses kostbare Erbe. ARCHE NOAH hält dem eine positive Vision (Leitbild des Vereins) und zahlreiche Aktivitäten entgegen: ARCHE NOAH bewahrt und pflegt tausende gefährdete Gemüse-, Obst- und Getreidesorten. Erfolgreich arbeiten wir daran, traditionelle und seltene Sorten wieder in die Gärten und auf den Markt zu bringen – dank der Unterstützung von über 17.000 engagierten Mitgliedern und Förderern. Quelle: https://www.arche-noah.at/ueber-uns",
        weblink: "https://www.arche-noah.at/",
        lat: 48.51896771558353, 
        lng: 15.618738735905062,

    },
    {
    
        nr: 4,
        user: "BirdLife",
        Adresse: "Museumsplatz 1/10/8, 1070 Wien",
        Mail: "office@birdlifeat",
        Öffnungszeiten: "",
        intro: "Gesellschaft für Vogelkunde",
        about: "Wir geben Vägeln eine Stimme. BirdLife Österreich ist Partner von BirdLife International, dem weltweit größten aktiven Netzwerk von Natur- und Vogelschutz-Organisationen mit über 10 Millionen Unterstützern in über 120 Ländern. BirdLife Österreich ist als gemeinnütziger Verein die einzige bundesweit tätige ornithologische Vereinigung Österreichs und verwirklicht seit der Gründung 1953 wissenschaftlich fundierte Natur- und Vogelschutzprojekte in vier Kernbereichen: Artenschutz, Schutzgebiete & Lebensräume, Nachhaltigkeit, Bewusstseinsbildung. Quelle: https://www.birdlife.at/page/unserteam",
        weblink: "https://www.birdlife.at/" ,
        lat: 48.20279043802087, 
        lng: 16.35914381979702,
    },
    {
    
        nr: 5,
        user: "Bündnis Alpenkonvention Kärnten",
        Adresse: "Proboj 2, 9113 Sittersdorf",
        Mail: "unglaub@archi-noah.at",
        Öffnungszeiten: "",
        intro: "Teil der Alpenkonvention zum Schutz und für nachhaltige Entwicklung des gesamten Alpenraumes",
        about: "Das gemeinsame Ziel unserer Mitgliedorganisationen ist die  Sicherung einer lebenswerten und intakten Umwelt für die künftigen Generationen sowie Entwicklung einer zukunftsfähigen Lebens- und Wirtschaftsweise. Dies ist auch Botschaft und Inhalt der rechtsverbindlichen Alpenkonvention. Sie bildet daher die Grundlage unserer Arbeit. Wir möchten dazu beitragen, dass in Kärnten in einem gemeinsamen gesellschaftlichen Prozess die Umsetzung der Alpenkonvention Schritt für Schritt vorangetrieben wird. Quelle: https://www.buendnisalpenkonvention.at/ueber-uns",
        weblink: "https://www.buendnisalpenkonvention.at/" ,
        lat: 46.554567127891396,
        lng: 14.598284144200157,
    },
    {
    
        nr: 6,
        user: "Climates Austria",
        Adresse: "Lindengasse 56/18-19, 1070 Wien",
        Mail: "hello@climatesaustria.org",
        Öffnungszeiten: "",
        intro: "Jugend für eine klimaverträgliche Zukunft",
        about: "CliMates Austria bringt Bewegung ins Klima. Wir nehmen Einfluss auf die Klimapolitik, bestärken junge Changemaker*innen, machen Klimabildung und schreiben über wichtige klimapolitische Themen. Wir sind junge Bürger*innen, die die Welt verändern. CliMates Austria ist eine ehrenamtliche NGO und Teil des internationalen Jugendnetzwerks CliMates. Und Du kannst jetzt als Mitglied „Mate“ Teil davon werden! Quelle: https://climatesaustria.org/",
        weblink: "https://climatesaustria.org/" ,
        lat: 48.19987970442615,
        lng: 16.346090278771765,
    },
    {
    
        nr: 7,
        user: "Die Umweltberatung Wien",
        Adresse: "Buchengasse 77/4, 1100 Wien",
        Mail: "service@umweltberatung.at",
        Öffnungszeiten: "",
        intro: "Individuelle Beratung für Privatpersonen sowie für Unternehmen.",
        about: "Seit 1988 informiert und berät DIE UMWELTBERATUNG Privathaushalte und Betriebe und arbeitet in Umweltschutz-Projekten. Von diesem Know-how profitieren unsere Kundinnen und Kunden sowie ProjektpartnerInnen. DIE UMWELTBERATUNG bereitet ökologisches Wissen gut verständlich und praxisorientiert auf. Unsere BeraterInnen beantworten Ihre Anfragen individuell und firmen-unabhängig. Wir beraten private Haushalte, Bildungseinrichtungen, Institutionen und Betriebe. DIE UMWELTBERATUNG verwirklicht zukunftsweisende Projekte. Quelle: https://www.umweltberatung.at/ueber-uns",
        weblink: "https://www.umweltberatung.at/" ,
        lat: 48.1749255624965,
        lng: 16.374404598358936,
    },
    {
    
        nr: 8,
        user: "Das Gramm",
        Adresse: "Neutorgasse 7, 8010 Graz",
        Mail: "hallo@dasgramm.at",
        Öffnungszeiten: "Mo - Fr: 9:00 - 19:00, Sa: 10:00 - 17:00",
        intro: "Regionale Bio-Greisslerei",
        about: "Das Gramm, unsere regionale Greißlerei, wurde im April 2016 in der Neutorgasse eröffnet. Seither liegt unser Fokus auf regionalen Spezialitäten, unverpackten Lebensmitteln aus kontrolliert biologischem Anbau und einer kleinen, aber feinen Auswahl an Zero Waste Artikeln in den Bereichen Haushalt und Körperpflege. Produkte, die eine Verpackung brauchen, sind in Pfandgläsern oder Papiersackerln erhältlich, um so besonders Einwegplastik bestmöglich zu vermeiden. Bei uns kannst du genau diese Menge kaufen, die du auch wirklich brauchst – so gehen wir auch bei dir zuhause gegen Lebensmittelverschwendung vor. Unser “kleines Gramm” ist mehr als nur eine Greißlerei; es ist ein Ort zum Ankommen und Wohlfühlen, an dem du dich mit unserem Experten:innen-Team austauschen oder auch einfach in Ruhe die Atmosphäre auf dich wirken lassen kannst. Quelle: https://www.dasgramm.at/das-sind-wir/#wiewir",
        weblink: "https://www.dasgramm.at/",
        lat: 47.070688574948505, 
        lng: 15.436974564704707,
    },
    {
    
        nr: 9,
        user: "E. C. O.",
        Adresse: "Lakeside B07b, 9020 Klagenfurt",
        Mail: "office@e-c-o.at",
        Öffnungszeiten: "",
        intro: "Institut für Ökologie",
        about: "Wir begeistern uns für die Vielfalt der Natur und sichern ihren Erhalt auch für zukünftige Generationen. Als Forschungs- und Beratungsunternehmen für „Naturschutz im 21. Jahrhundert“ begleiten und unterstützen wir unsere internationalen und nationalen Partner:innen dabei, natürliche Lebensräume zu bewahren und zu verbessern, außergewöhnliche Naturerlebnisse zu ermöglichen und die Lebens- und Wirtschaftsbedingungen in den jeweiligen Regionen weiterzuentwickeln. Mit unseren ökologischen Fachplanungen, naturräumlichen Erhebungen, innovativen Kommunikationskonzepten und nachhaltiger Entwicklungszusammenarbeit setzen wir uns aktiv für die Erfüllung der globalen Sustainable Development Goals ein. Quelle: https://e-c-o.at/home.html",
        weblink: "https://e-c-o.at/home.html",
        lat: 46.61445647600445,
        lng: 14.263496343802236,
    },
    {
    
        nr: 10,
        user: "EU Umweltbüro",
        Adresse: "Strozzigasse 10/8-9, 1080 Wien",
        Mail: "office@eu-umweltbuero.at",
        Öffnungszeiten: "",
        intro: "Kompetenzzentrum für Europäische Umweltpolitik und -gesetzgebung",
        about: "Das EU Umweltbüro in Wien wurde 1994 als Kompetenzzentrum für Europäische Umweltpolitik und -gesetzgebung gegründet und ist im Umweltdachverband – der größten österreichischen Dachorganisation von Umweltschutzorganisationen – angesiedelt. Die Kernkompetenzen des EU-Umweltbüros sind umfassende Kenntnisse des politischen Gesetzwerdungsprozesses auf europäischer Ebene und Informationen über derzeitige und zukünftige Entwicklungen im Bereich EU-Umweltpolitik. Das Umweltbüro vertritt die österreichischen Mitglieder im Vorstand des europäischen Dachverbands European Environmental Bureau (EEB)in Brüssel. Das Umweltbüro ist auf europäischer und  internationaler Ebene gut vernetzt und arbeitet auf Deutsch und Englisch. Quelle: https://www.eu-umweltbuero.at/ueber-uns/was-wir-tun/",
        weblink: "https://www.eu-umweltbuero.at/",
        lat: 48.20739603144972, 
        lng: 16.349451311852835,
    },
    {
    
        nr: 11,
        user: "EVAL",
        Adresse: "Rössing 311, 8972 Ramsau am Dachstein",
        Mail: "khh@evalww.com",
        Öffnungszeiten: "",
        intro: "Ehrfurcht vor allem Leben",
        about: "Gemeinnützige Gemeinschaft zur Förderung des friedlichen Zusammenlebens der Menschen und des respektvollen Umgangs mit der Natur. Vernetzungs- und Informations-Plattform für alle Initiativen, Gruppen und Vereine, die sich zum EVAL-Prinzip - Ehrfurcht Vor Allem Leben - bekennen. Die EVAL-Datenbank als Teil des EVAL-INFO-SYSTEMS (EIS) steht allen Bürgern zur Verfügung die sich frei von Lobbyisteninteressen jeglicher Art und ohne Werbung und persönliche Datenerfassung informieren möchten. Unser Ziel: Urteilsfähige und selbstkritische DemokratenInnen. Quelle: https://www.evalww.com/",
        weblink: "https://www.evalww.com/",
        lat: 47.43266380070504,  
        lng: 13.752812580751053,
    },
    {
    
        nr: 12,
        user: "Ernährungsrat Wien",
        Adresse: "nicht angegeben",
        Mail: "kontakt@ernaehrungsrat-wien.at",
        Öffnungszeiten: "",
        intro: "vernetzen - verstehen - verändern",
        about: "Wir sind ein zivilgesellschaftlicher Zusammenschluss von, derzeit ca. 30, engagierten Menschen aus den verschiedensten Bereichen des Wiener Ernährungssystems: Gastronomie und Forschung, urbane Landwirtschaft und zivilgesellschaftliche Organisationen, Beratung und Interessensvertretung, Gemeinschaftsverpflegung und Food Coops. Diese Hintergründe und die Auseinandersetzung mit der eigenen Ernährung und deren Auswirkungen - der persönliche Bezug zu den Themen Lebensmittel und Ernährung hat unsere Gruppe zusammengeführt. Uns verbindet das gemeinsame Ziel, durch den Ernährungsrat Wien zu einem ökologisch zukunftsfähigen und sozial gerechten Ernährungssystem in der Wiener Stadt-Region beizutragen. Jedes (neue) Mitglied bereichert den Ernährungsrat Wien mit neuen Perspektiven. Geben wir der Zivilgesellschaft gemeinsam eine starke Stimme für ein demokratisches, sozial gerechtes und ökologisch zukunftsfähiges Ernährungssystem! Quelle: https://ernaehrungsrat-wien.at/ueber-uns/wir/",
        weblink: "https://ernaehrungsrat-wien.at/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
    
        nr: 13,
        user: "FiBL",
        Adresse: "Doblhoffgasse 7/10, 1010 Wien",
        Mail: "info.oesterreich@fibl.org",
        Öffnungszeiten: "",
        intro: "Forschungsinstitut für biologischen Landbau",
        about: "Das FiBL verfügt über Kompetenzen in allen Belangen der biologischen Landwirtschaft: Bodenbewirtschaftung und Pflanzenbau, artgerechte Tierhaltung und ganzheitliche Tiergesundheit, sozioökonomische Belange, biologische Lebensmittelverarbeitung sowie umfassende Analysen des Biomarktes. Zudem engagiert sich das FiBL seit vielen Jahren auf internationaler Ebene für die Entwicklung des Biolandbaus zum Beispiel beim Biolandbau-Weltdachverband IFOAM – Organics International. Das FiBL ist Partner in Forschungs- und Entwicklungsprojekten der Europäischen Union (EU), der Welternährungsorganisation FAO und vieler weiterer nationaler und internationaler Institutionen. Das FiBL unterstützt die Entwicklung zukunftsfähiger Landwirtschaft in Afrika, Asien, Lateinamerika und Osteuropa in enger Zusammenarbeit mit lokalen Partnerorganisationen. FiBL-Forscher untersuchen in Langzeitversuchen lokale und biologische Anbausysteme und bieten Expertise im Bereich der Marktentwicklung an. Quelle: https://www.fibl.org/de/ueber-uns.html",
        weblink: "https://www.fibl.org/de/",
        lat: 48.2086582275331,  
        lng: 16.355933269660643,
    },
    {
    
        nr: 14,
        user: "Plattform Footprint",
        Adresse: "Jandagasse 7 Haus 1, 1210 Wien",
        Mail: "office@footprint.att",
        Öffnungszeiten: "",
        intro: "Verein zur Förderung des Bewusstseins für den Ökologischen Fußabdruck",
        about: "Die Plattform Footprint ist eine Allianz von Umwelt- und Entwicklungspolitischen Organisationen, die den „Ökologischen Fußabdruck“ als wesentliche Maßzahl für die Zukunftsfähigkeit unserer Gesellschaft verankern will. Gemeinsam mit unseren Partnerorganisationen wollen wir durch Lobbying- und Aufklärungsarbeit zum Thema Footprint Bewusstseinsbildung, Handlungseinsicht und politischen Druck für nachhaltige gesellschaftliche Veränderung erzeugen. Quelle:https://www.footprint.at/",
        weblink: "https://www.footprint.at/",
        lat: 48.2862739216721, 
        lng: 16.410748398498882, 
    },
    {
    
        nr: 15,
        user: "Forum Wissenschaft & Umwelt",
        Adresse: "Palmgasse 3/2, 1150 Wien",
        Mail: "office@fwu.at",
        Öffnungszeiten: "",
        intro: "Gemeinnütziger Verein",
        about: "Wir sind eine unabhängige Vereinigung von Wissenschaftlerinnen und Wissenschaftlern, die das Ziel verfolgt, fachübergreifende Beiträge für eine zukunftsverträgliche Entwicklung von Umwelt, Gesellschaft und Wirtschaft zu leisten. Wir wollen der gesellschaftlichen Verantwortung unserer wissenschaftlichen Tätigkeit gerecht werden und bekennen uns zu Werten wie Vielfalt des Lebens und eine zukunftsfähige, humane Gesellschaft. Quelle: https://fwu.at/impressum/",
        weblink: "https://fwu.at/",
        lat: 48.19455632077085,  
        lng: 16.338057098496236,
    },
    {
    
        nr: 16,
        user: "Future Aid",
        Adresse: "nicht angegeben",
        Mail: "future-aid@future-aid.at",
        Öffnungszeiten: "",
        intro: "Die Zukunft braucht unsere Hilfe",
        about: "Future Aid ist eine private Non-Profit Initiative mit dem Ziel unsere Zukunft zu verbessern! Future Aid will sich von anderen Initiativen durch eine einzigartig umfassende Behandlung der Zukunftsthemen (Umwelt-Wirtschaft-Gesellschaft) unterscheiden! Quelle: https://www.future-aid.at/neu-bei-future-aid/%C3%BCber-future-aid/",
        weblink: "https://www.future-aid.at/",
        lat: 48.19866389758175, 
        lng: 16.34490446542928 ,
    },
    {
    
        nr: 17,
        user: "eneration Earth",
        Adresse: "Ottakringer Straße 114-116, 1160 Wien",
        Mail: "info@generationearth.at",
        Öffnungszeiten: "",
        intro: "Das WWF Netzwerk für junge, engagierte Menschen",
        about: "Generation Earth ist ein buntes Netzwerk aus jungen Menschen, das inspiriert, bildet und in Aktion tritt – für die Zukunft unseres Planeten. Bei unserem Action Leader Training lernst du grundlegende Skills und hast die Möglichkeit, dich in verschiedenen Bereichen auszuprobieren. Im Rahmen unserer Projekte treten wir gemeinsam mit dir in Aktion. Wir inspirieren dich mit Wildnis hautnah und zeigen dir in der Natur, was andere oft übersehen. Quelle: https://www.generationearth.at/",
        weblink: "https://www.generationearth.at/",
        lat: 48.21370721583878, 
        lng: 16.323157911988677,
    },
    {
    
        nr: 18,
        user: "Global 2000",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "office@global2000.at",
        Öffnungszeiten: "",
        intro: "Österreichs unabhängige Umweltschutzorganisation",
        about: "Wir setzen alles daran, unsere Welt zum Positiven zu verändern. Das heißt, egal, um welches Umweltschutz-Thema es geht: Wir setzen uns für das Gute und das Schöne ein. Denn es ist schön, bedenkenlos in einen Bio-Apfel zu beissen, den Kindern gesunde, vielfältige Lebensmittel bieten und intakte Lebensräume nützen zu können. Genauso schön ist es auch, mit gutem Gewissen einkaufen zu gehen, weil wir für faire Bedingungen im Handel sorgen und Menschen, Tiere und Pflanzen friedvoll zusammenleben. Quelle: https://www.global2000.at/ueber-global-2000",
        weblink: "https://www.global2000.at/",
        lat: 48.20559473723108,  
        lng: 16.350895198496506,
    },
    {
    
        nr: 19,
        user: "Schwendermarkt",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "initiative-schwendermarkt@gmx.at",
        Öffnungszeiten: "",
        intro: "Initiative zur Erhaltung und Belebung des Schwendermarktes",
        about: "Der Schwendermarkt ist der kleinste Markt in Wien. Interessante Geschäfte mit Bio und regionalen Produkten von bauern aus der Umgebung von Wien und dem weinviertel. gemütliche Atmosphäre in Markt Cafés, sehr gutes Essen inkl einer Vietnamesin, die super kocht, Marktstände mit Gemüse, Käse, Obst. tolles großes Café in hippem Blumenladen,.... Quelle: https://www.facebook.com/Schwendermarkt/reviews/?ref=page_internal Review of: Karin N. York",
        weblink: "http://www.schwendermarkt.at/",
        lat: 48.19097235033396, 
        lng: 16.326267103155473,
    },
    {
    
        nr: 20,
        user: "Jane Goodall Institut - Austria",
        Adresse: "Probusgasse 3, 1190 Wien",
        Mail: "office@janegoodall.at",
        Öffnungszeiten: "",
        intro: "für Naturschutz, Umweltbildung und Erforschung wildlebender Tiere",
        about: "Wir wollen das Überleben der letzten Schimpansen sichern. Unseren Projekten legen wir eine ganz alltägliche Erfahrung zugrunde: Ein Lächeln ist der kürzeste Weg zwischen zwei Menschen. Weil sich Herausforderungen besser gemeinsam bewältigen lassen, setzen wir auf enge Zusammenarbeit mit den Menschen vor Ort. Die Folge: der beste Austausch an Wissen und Verständnis für die Bedürfnisse der Einheimischen und für die regionalen Besonderheiten der Tier- und Pflanzenwelt. Quelle: https://janegoodall.at/was-wir-tun/",
        weblink: "https://janegoodall.at/",
        lat: 48.2552212909714,   
        lng: 16.356298763578838,
    },
    {
    
        nr: 21,
        user: "KEC",
        Adresse: "Schendlingerstraße 40, 6900 Bregenz",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 47.49522925643081,   
        lng: 9.71981471752438,
    },
    {
    
        nr: 21,
        user: "KEC",
        Adresse: "Pazmanitengasse 19, 1020 Wien",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 48.22255643075428,   
        lng: 16.385441990561716,
    },
    {
    
        nr: 21,
        user: "KEC",
        Adresse: "10. Oktober Straße 17, 9560 Feldkirchen",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 46.72394604602631,   
        lng: 14.095550729078235,
    },
    {
    
        nr: 22,
        user: "Klimabündnis Tirol",
        Adresse: "Müllerstraße 7, 6020 Innsbruck",
        Mail: "tirol@klimabuendnis.at",
        Öffnungszeiten: "",
        intro: "Wir setzen uns aktiv für Klimaschutz, Klimagerechtigkeit und einen nachhaltigen Lebensstil ein.",
        about: "Der Verein Klimabündnis Tirol ist Teil des größten kommunalen Klimaschutz-Netzwerks Europas. Die globale Partnerschaft verbindet mehr als 1.700 Gemeinden aus 27 Ländern in Europa mit Indigenen Organisationen des Amazonas-Regenwaldes.In Österreich haben sich über 1000 Gemeinden und Betriebe sowie über 600 Bildungseinrichtungen dem Klimabündnis angeschlossen. Quelle: https://tirol.klimabuendnis.at/ueber-uns/das-klimabuendnis-tirol",
        weblink: "https://tirol.klimabuendnis.at/",
        lat: 47.26157355303793,   
        lng: 11.394328026778537,
    },
    {
    
        nr: 18,
        user: "Global 2000",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "office@global2000.at",
        Öffnungszeiten: "",
        intro: "Österreichs unabhängige Umweltschutzorganisation",
        about: "Wir setzen alles daran, unsere Welt zum Positiven zu verändern. Das heißt, egal, um welches Umweltschutz-Thema es geht: Wir setzen uns für das Gute und das Schöne ein. Denn es ist schön, bedenkenlos in einen Bio-Apfel zu beissen, den Kindern gesunde, vielfältige Lebensmittel bieten und intakte Lebensräume nützen zu können. Genauso schön ist es auch, mit gutem Gewissen einkaufen zu gehen, weil wir für faire Bedingungen im Handel sorgen und Menschen, Tiere und Pflanzen friedvoll zusammenleben. Quelle: https://www.global2000.at/ueber-global-2000",
        weblink: "https://www.global2000.at/",
        lat: 48.20559473723108,  
        lng: 16.350895198496506,
    },
    {
    
        nr: 18,
        user: "Global 2000",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "office@global2000.at",
        Öffnungszeiten: "",
        intro: "Österreichs unabhängige Umweltschutzorganisation",
        about: "Wir setzen alles daran, unsere Welt zum Positiven zu verändern. Das heißt, egal, um welches Umweltschutz-Thema es geht: Wir setzen uns für das Gute und das Schöne ein. Denn es ist schön, bedenkenlos in einen Bio-Apfel zu beissen, den Kindern gesunde, vielfältige Lebensmittel bieten und intakte Lebensräume nützen zu können. Genauso schön ist es auch, mit gutem Gewissen einkaufen zu gehen, weil wir für faire Bedingungen im Handel sorgen und Menschen, Tiere und Pflanzen friedvoll zusammenleben. Quelle: https://www.global2000.at/ueber-global-2000",
        weblink: "https://www.global2000.at/",
        lat: 48.20559473723108,  
        lng: 16.350895198496506,
    },
    {
    
        nr: 18,
        user: "Global 2000",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "office@global2000.at",
        Öffnungszeiten: "",
        intro: "Österreichs unabhängige Umweltschutzorganisation",
        about: "Wir setzen alles daran, unsere Welt zum Positiven zu verändern. Das heißt, egal, um welches Umweltschutz-Thema es geht: Wir setzen uns für das Gute und das Schöne ein. Denn es ist schön, bedenkenlos in einen Bio-Apfel zu beissen, den Kindern gesunde, vielfältige Lebensmittel bieten und intakte Lebensräume nützen zu können. Genauso schön ist es auch, mit gutem Gewissen einkaufen zu gehen, weil wir für faire Bedingungen im Handel sorgen und Menschen, Tiere und Pflanzen friedvoll zusammenleben. Quelle: https://www.global2000.at/ueber-global-2000",
        weblink: "https://www.global2000.at/",
        lat: 48.20559473723108,  
        lng: 16.350895198496506,
    },
];

const SOZIALES = [
    {
        nr: 1,
        user: "Concordia Sozialprojekte",
        Adresse: "Hochstettergasse 6, 1020 Wien",
        Mail: "office@concordia.or.at",
        Öffnungszeiten: "",
        intro: "Gemeinnützige Privatstiftung",
        about: "CONCORDIA ist eine internationale, unabhängige Nichtregierungsorganisation, die es sich zur Aufgabe gemacht hat, Kinder, Jugendliche und Familien in Not auf dem Weg in ein unabhängiges und verantwortungsvolles Leben zu unterstützen. Wir gehen dorthin, wo die Not am größten ist. Und wo andere nicht hingehen. Quelle: https://www.concordia.or.at/de/vision",
        weblink: "https://www.concordia.or.at/",
        lat:  48.22516071255066, 
        lng: 16.388036007608115,
    },
    {
        nr: 2,
        user: "Clean Clothes Kampagne",
        Adresse: "Laudongasse 40, 1080 Wien",
        Mail: "office@cleanclothes.at",
        Öffnungszeiten: "",
        intro: "Aktiv für faire Arbeitsbedingungen in der Bekleidungs- und Schuhproduktion weltweit",
        about: "Seit 1996 verfolgt die Clean Clothes Kampagne das Ziel, Arbeitsrechte in der globalen Bekleidungsindustrie zu verbessern. Wir klären BürgerInnen auf, drängen Unternehmen, mehr Verantwortung für ihre globalen Wertschöpfungsketten zu übernehmen und rufen die Regierungen dazu auf, Gesetze zu verabschieden, die Menschenrechtsverletzungen durch Unternehmen verhindern. Wir zeigen uns solidarisch mit den ArbeiterInnen, die unsere Kleidung herstellen und unterstützen ihren Kampf für bessere Arbeitsbedingungen. Der Clean Clothes Kampagne gehören sowohl Gewerkschaften als auch Nichtregierungsorganisationen (NROs) an. Diese arbeiten zu einem breiten Spektrum an Themen wie Frauenrechte, Verbraucherschutz und Armutsbekämpfung. Die Clean Clothes Kampagne ist Teil der internationalen Clean Clothes Campaign, die in 16 europäischen Ländern vertreten ist. Global arbeiten wir mit einem Netzwerk von über 200 Partnerorganisationen und Gewerkschaften in den Produktionsländern zusammen, um lokale Gegebenheiten und Lösungsansätze besser verstehen zu können. Dies hilft uns Kampagnen zu entwickeln, die die Forderungen der ArbeiterInnen vor Ort unterstützen. Wir arbeiten auch eng mit ähnlichen Arbeitsrechtsorganisationen in den USA, Kanada und Australien zusammen. Quelle: https://www.cleanclothes.at/de/ueber-uns/",
        weblink: "https://www.cleanclothes.at/de/",
        lat: 48.213375112250546,
        lng: 16.34533636157988

    },
    {
        nr: 3,
        user: "Das Gramm",
        Adresse: "Neutorgasse 7, 8010 Graz",
        Mail: "hallo@dasgramm.at",
        Öffnungszeiten: "Mo - Fr: 9:00 - 19:00, Sa: 10:00 - 17:00",
        intro: "Regionale Bio-Greisslerei",
        about: "Das Gramm, unsere regionale Greißlerei, wurde im April 2016 in der Neutorgasse eröffnet. Seither liegt unser Fokus auf regionalen Spezialitäten, unverpackten Lebensmitteln aus kontrolliert biologischem Anbau und einer kleinen, aber feinen Auswahl an Zero Waste Artikeln in den Bereichen Haushalt und Körperpflege. Produkte, die eine Verpackung brauchen, sind in Pfandgläsern oder Papiersackerln erhältlich, um so besonders Einwegplastik bestmöglich zu vermeiden. Bei uns kannst du genau diese Menge kaufen, die du auch wirklich brauchst – so gehen wir auch bei dir zuhause gegen Lebensmittelverschwendung vor. Unser “kleines Gramm” ist mehr als nur eine Greißlerei; es ist ein Ort zum Ankommen und Wohlfühlen, an dem du dich mit unserem Experten:innen-Team austauschen oder auch einfach in Ruhe die Atmosphäre auf dich wirken lassen kannst. Quelle: https://www.dasgramm.at/das-sind-wir/#wiewir",
        weblink: "https://www.dasgramm.at/",
        lat: 47.070688574948505, 
        lng: 15.436974564704707,
    },
    {
        nr: 4,
        user: "E. C. O.",
        Adresse: "Lakeside B07b, 9020 Klagenfurt",
        Mail: "office@e-c-o.at",
        Öffnungszeiten: "",
        intro: "Institut für Ökologie",
        about: "Wir begeistern uns für die Vielfalt der Natur und sichern ihren Erhalt auch für zukünftige Generationen. Als Forschungs- und Beratungsunternehmen für „Naturschutz im 21. Jahrhundert“ begleiten und unterstützen wir unsere internationalen und nationalen Partner:innen dabei, natürliche Lebensräume zu bewahren und zu verbessern, außergewöhnliche Naturerlebnisse zu ermöglichen und die Lebens- und Wirtschaftsbedingungen in den jeweiligen Regionen weiterzuentwickeln. Mit unseren ökologischen Fachplanungen, naturräumlichen Erhebungen, innovativen Kommunikationskonzepten und nachhaltiger Entwicklungszusammenarbeit setzen wir uns aktiv für die Erfüllung der globalen Sustainable Development Goals ein. Quelle: https://e-c-o.at/home.html",
        weblink: "https://e-c-o.at/home.html",
        lat: 46.61445647600445,
        lng: 14.263496343802236,
    },


];


const GESUNDHEIT = [
    {
        nr: 1,
        user: "ARGE Abfallvermeidung",
        Adresse: "Puchstraße 41, 8010 Graz",
        Mail: "office@arge.at",
        Öffnungszeiten: "",
        intro: "Umweltschutzunternehmen",
        about: "Die ARGE konzipiert und implementiert Projekte in den Bereichen Abfallvermeidung, Ressourcenschonung und nachhaltige Entwicklung. Die ARGE ist eine Non-Profit Organisation, die im Jahr 1982 gegründet wurde. Wir konzipieren und organisieren regionale, nationale und internationale Projekte im Bereich nachhaltige Entwicklung und kommunale Abfallwirtschaft. Unsere erste Priorität ist -wie unser Name schon sagt- die Abfallvermeidung. Der schonende Umgang mit Ressourcen und der Schutz unserer Umwelt ist Fokus unserer Arbeit. Wir betrachten die Abfall- und Ressourcenwirtschaft im sozialen, ökologischen und ökonomischen Kontext. Ein wesentlicher Teil unserer Aktivitäten ist daher die Kooperation mit sozialwirtschaftlichen Einrichtungen und die Schaffung von Arbeitsplätzen im Umweltbereich. Quelle: https://www.facebook.com/ArgeAbfallvermeidung/",
        weblink: "https://www.arge.at/",
        lat:  47.05001107528067, 
        lng: 15.436887611278067,
    },
    {
        nr: 2,
        user: "ARGE Schöpfungsveranstaltung",
        Adresse: "Petersplatz 1, 1010 Wien",
        Mail: "office@argeschoepfung.at",
        Öffnungszeiten: "",
        intro: "Kirchliche Umweltarbeit",
        about: "Seit über 25 Jahren ist die ARGE Schöpfungsverantwortung in Kirche und Gesellschaft aktiv. Sie ist Initiator der kirchlichen Umweltarbeit in Österreich und Mitbegründer des EUROPEAN CHRISTIAN ENVIRONMENTAL NETWORKS (ECEN). Im Rahmen der Initiative zur Einführung der SCHÖPFUNGSZEIT agiert sie international. Die Umsetzung erfolgt projektbezogen mit einem Team von engagierten Mitarbeitern, Experten aus Natur- und Geisteswissenschaften. Mit einem laufenden Bildungsprogramm und ökosozialen Handlungsmodellen begleitet und unterstützt sie engagierte Personen und Institutionen sowie einschlägige Netzwerke. Als Gründungsmitglied des EUROPÄISCHEN CHRISTLICHEN UMWELTNETZWERKES (ECEN) bietet sie Partizipation am internationalen kirchlichen Umweltgeschehen. Zahlreiche Initiativen erfolgen in Kooperation mit Umwelt- und Entwicklungsorganisationen. Für Ihre Tätigkeit wurde die ARGE Schöpfungsverantwortung mit dem Staatspreis der Republik Österreich, dem Konrad-Lorenz-Preis ausgezeichnet und erhielt für die Wahrnehmung der Trias des „Konziliaren Prozesses für Gerechtigkeit – Frieden – Bewahrung der Schöpfung“ die Europäische Friedensrose Waldhausen. Quelle: https://www.argeschoepfung.at/ueber-uns/ueberblick.html",
        weblink: "https://www.argeschoepfung.at/",
        lat: 48.209195875185195, 
        lng: 16.370094671021324

    },
];
