const SOZIALES = [
    {
        nr: 1,
        user: "Concordia Sozialprojekte",
        Adresse: "Hochstettergasse 6, 1020 Wien",
        Mail: "office@concordia.or.at",
        Öffnungszeiten: "",
        intro: "Gemeinnützige Privatstiftung",
        about: "CONCORDIA ist eine internationale, unabhängige Nichtregierungsorganisation, die es sich zur Aufgabe gemacht hat, Kinder, Jugendliche und Familien in Not auf dem Weg in ein unabhängiges und verantwortungsvolles Leben zu unterstützen. Wir gehen dorthin, wo die Not am größten ist. Und wo andere nicht hingehen. Quelle: https://www.concordia.or.at/de/vision",
        weblink: "https://www.concordia.or.at/",
        lat:  48.22516071255066, 
        lng: 16.388036007608115,
    },
    {
        nr: 2,
        user: "Clean Clothes Kampagne",
        Adresse: "Laudongasse 40, 1080 Wien",
        Mail: "office@cleanclothes.at",
        Öffnungszeiten: "",
        intro: "Aktiv für faire Arbeitsbedingungen in der Bekleidungs- und Schuhproduktion weltweit",
        about: "Seit 1996 verfolgt die Clean Clothes Kampagne das Ziel, Arbeitsrechte in der globalen Bekleidungsindustrie zu verbessern. Wir klären BürgerInnen auf, drängen Unternehmen, mehr Verantwortung für ihre globalen Wertschöpfungsketten zu übernehmen und rufen die Regierungen dazu auf, Gesetze zu verabschieden, die Menschenrechtsverletzungen durch Unternehmen verhindern. Wir zeigen uns solidarisch mit den ArbeiterInnen, die unsere Kleidung herstellen und unterstützen ihren Kampf für bessere Arbeitsbedingungen. Der Clean Clothes Kampagne gehören sowohl Gewerkschaften als auch Nichtregierungsorganisationen (NROs) an. Diese arbeiten zu einem breiten Spektrum an Themen wie Frauenrechte, Verbraucherschutz und Armutsbekämpfung. Die Clean Clothes Kampagne ist Teil der internationalen Clean Clothes Campaign, die in 16 europäischen Ländern vertreten ist. Global arbeiten wir mit einem Netzwerk von über 200 Partnerorganisationen und Gewerkschaften in den Produktionsländern zusammen, um lokale Gegebenheiten und Lösungsansätze besser verstehen zu können. Dies hilft uns Kampagnen zu entwickeln, die die Forderungen der ArbeiterInnen vor Ort unterstützen. Wir arbeiten auch eng mit ähnlichen Arbeitsrechtsorganisationen in den USA, Kanada und Australien zusammen. Quelle: https://www.cleanclothes.at/de/ueber-uns/",
        weblink: "https://www.cleanclothes.at/de/",
        lat: 48.213375112250546,
        lng: 16.34533636157988

    },
    {
        nr: 4,
        user: "E. C. O.",
        Adresse: "Lakeside B07b, 9020 Klagenfurt",
        Mail: "office@e-c-o.at",
        Öffnungszeiten: "",
        intro: "Institut für Ökologie",
        about: "Wir begeistern uns für die Vielfalt der Natur und sichern ihren Erhalt auch für zukünftige Generationen. Als Forschungs- und Beratungsunternehmen für „Naturschutz im 21. Jahrhundert“ begleiten und unterstützen wir unsere internationalen und nationalen Partner:innen dabei, natürliche Lebensräume zu bewahren und zu verbessern, außergewöhnliche Naturerlebnisse zu ermöglichen und die Lebens- und Wirtschaftsbedingungen in den jeweiligen Regionen weiterzuentwickeln. Mit unseren ökologischen Fachplanungen, naturräumlichen Erhebungen, innovativen Kommunikationskonzepten und nachhaltiger Entwicklungszusammenarbeit setzen wir uns aktiv für die Erfüllung der globalen Sustainable Development Goals ein. Quelle: https://e-c-o.at/home.html",
        weblink: "https://e-c-o.at/home.html",
        lat: 46.61445647600445,
        lng: 14.263496343802236,
    },
    {
        nr: 5,
        user: "European Centre for Social Welfare Policy and Research",
        Adresse: "Berggasse 17, 1090 Wien",
        Mail: "ec@euro.centre.org",
        Öffnungszeiten: "",
        intro: "Intergovernmental organisation affiliated to the United Nations",
        about: "The European Centre for Social Welfare Policy and Research (the European Centre) is an intergovernmental organisation affiliated to the United Nations. Its purpose is to foster the collaboration in social welfare between governments and organisations by providing applied social science and comparative empirical research; forging the evidence-base for social policy making and mutual learning; initiating future-oriented public policy debates by networking. Quelle: https://www.euro.centre.org/aboutus",
        weblink: "https://www.euro.centre.org/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
        nr: 6,
        user: "Frauendomäne",
        Adresse: "Leopold-Ernst-Gasse, 1170 Wien",
        Mail: "hello@frauendomaene.at",
        Öffnungszeiten: "",
        intro: "Wir machen weibliche Kompeenz sichtbar",
        about: "Durch die Expert*innendatenbank Frauendomäne machen wir seit dem Jahr 2018 weibliche Kompetenz kollektiv sichtbar. Die Frauendomäne ist die erste Datenbank in Österreich, in die sich Expert*innen aus allen Fachbereichen kostenlos eintragen können und auf die alle Menschen und Organisationen kostenlos und uneingeschränkt zugreifen können. Wir unterstützen Organisator*innen, Unternehmen und Medienvertreter*innen dabei, ihre Panels, Seminare, Teams und Interviews geschlechterausgewogen und divers zu konzipieren.Durch unsere Arbeit machen wir darauf aufmerksam, dass homogene Gremien und Panels in der Öffentlichkeit und in der Berufswelt nicht mehr zeitgemäß sind. Wir wirken darauf hin, die Rahmenbedingungen an die Lebensrealitäten von allen Menschen anzupassen. Denn wir sind der Meinung, dass viele Menschen in der Art und Weise, wie unsere Welt gebaut ist, nicht mitgedacht werden. Wir streben nach einer Welt, in der Menschen eine Expertise und Kompetenz nach ihren Stärken und nicht nach ihrem Geschlecht aufbauen. Quelle: https://www.frauendomaene.at/about/",
        weblink: "https://www.frauendomaene.at/",
        lat: 48.222721538335115,   
        lng: 16.332347798360093,
    },
    {
        nr: 7,
        user: "HeForShe Vienna",
        Adresse: "Grundsteingasse 53, 1160 Wien",
        Mail: "nicht angegeben",
        Öffnungszeiten: "",
        intro: "Verein zur Unterstützung der HeForShe-Kampagne der Vereinten Nationen",
        about: "HeForShe heißt die im Jahr 2014 von UN Women ins Leben gerufene Solidaritätsbewegung, die auf die Beseitigung von Diskriminierungen aufgrund des Geschlechts und die gesellschaftliche Gleichstellung der Geschlechter abzielt. Die Botschaft der Kampagne ist einfach: Die Gleichstellung der Geschlechter ist keine Frauensache, sondern ein Menschenrecht und betrifft uns alle: Mädchen*, Frauen*, Buben* und Männer*. Daher müssen wir alle gemeinsam an diesem Ziel arbeiten. Im Vordergrund stehen die Bewusstseinsbildung und die Mobilisierung einer breiten Masse an Unterstützer*innen. Dadurch soll Druck auf Organisationen, Regierungen und die Gesellschaft ausgeübt werden, um eine Veränderung von innen heraus zu bewirken. Wie der Name der Kampagne bereits sagt, werden vor allem Männer* aufgefordert, sich aktiv einzubringen und ihre Stimme für die Gleichberechtigung und Gleichstellung der Geschlechter zu erheben. Die Gleichstellung der Geschlechter ist im 21. Jahrhundert nicht nur längst überfällig, sondern hat positive Auswirkungen auf alle Bereiche des gesellschaftlichen Lebens. Von Geschlechtergleichstellung profitieren wir alle. Quelle: https://www.heforshe-vienna.at/ueber-uns",
        weblink: "https://www.heforshe-vienna.at/",
        lat: 48.210617370764716,    
        lng: 16.333252868978143,
    },
    {
    
        nr: 8,
        user: "KEC",
        Adresse: "Schendlingerstraße 40, 6900 Bregenz",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 47.49522925643081,   
        lng: 9.71981471752438,
    },
    {
        nr: 9,
        user: "Lebensart",
        Adresse: "Wiener Straße 35, 3100 St. Pölten",
        Mail: "service@lebensart.at",
        Öffnungszeiten: "",
        intro: "Verlags GmbH",
        about: "nachhaltig.gut.leben. Das ist unsere Vision. Alle Menschen sollen heute und in Zukunft ein gutes Leben führen können. Deshalb haben wir den Lebensart Verlag gegründet. Wir berichten über nachhaltige Trends und bringen Hintergrundinformationen damit Sie eine gute Entscheidung treffen können. Vor allem zeigen wir Lösungsansätze von kreativen Menschen, wie ein gutes Leben aussehen kann und erzählen Geschichten, die inspirieren und zu eigenem Handeln anregen. Das alles lesen Sie in den Print und Online-Magazinen LEBENSART, BUSINESSART und über die Reiseplattform lebensart-reisen.at. Wir veranstalten jährlich die Wahl der Nachhaltigen GestalterInnen Österreichs, sind Mitveranstalter des CSR-Circle, kooperieren mit engagierten Menschen und Organisationen und unterstützen Partner in ihrer nachhaltigen Kommunikation. Quelle: https://www.lebensart-verlag.at/was-wir-tun-werte-vision-und-mission",
        weblink: "https://www.lebensart.at/",
        lat: 48.21892335496585,   
        lng: 15.660709850085858,
    },
    {
        nr: 10,
        user: "Mördinger Kommunikation- und Politikberatung",
        Adresse: "Wolkersbergenstraße 164, 1130 Wien",
        Mail: "nicht angegeben",
        Öffnungszeiten: "",
        intro: "Lobby für Energiewende und Nachhaltigkeit",
        about: "Energiewende und Nachhaltigkeit brauchen Unterstützung. Obwohl unzählige engagierte Menschen, Organisationen und Unternehmen an einer nachhaltigen Zukunft arbeiten, kommen wir nur langsam vom Fleck. Mal fehlt es am rechtlichen Rahmen, mal an der Aufmerksamkeit der Medien. Und manchmal bekommt die Energiewende Probleme mit Menschen vor Ort oder dem Naturschutz. Quelle: https://www.moerdinger.at/",
        weblink: "https://www.moerdinger.at/",
        lat: 48.17657903037716,   
        lng: 16.274120095963383,
    },
    {
        nr: 11,
        user: "social city wien",
        Adresse: "Sachsenplatz 4-6, 1200 Wien",
        Mail: "office@socialcity.atn",
        Öffnungszeiten: "",
        intro: "Unabhängige Plattform für gesellschaftliche Innovation",
        about: "Die Plattform „Social City Wien“ bringt Wiens kluge Köpfe mit vielen sozialen Ideen zusammen, schafft ein Netzwerk für soziales Engagement und bildet einen nahrhaften Boden für gesellschaftliche Innovationen. Wir sind die Drehscheibe für gesellschaftliche Innovation, weil soziale Entwicklung uns alle nachhaltig weiterbringt. Wir machen soziale Innovation einfacher, optimieren Abläufe zwischen den AkteurInnen und steigern so die Effizienz der innovativen Prozesse. Quelle: http://www.socialcity.at/de/ueber-uns.html",
        weblink: "http://www.socialcity.at/de/",
        lat: 48.23219129176,    
        lng: 16.37598792480044,
    },
    {
        nr: 12,
        user: "Team CU2 SustainAgiency",
        Adresse: "Gardegasse 6/27, 1070 Wien",
        Mail: "info@cu2.team",
        Öffnungszeiten: "",
        intro: "Das Magazin der CU2 Kreativagrntur",
        about: "In über 23 Jahren an Erfahrung in der (Markt-)Kommunikation, u. a. mit den Schwerpunkten Packaging-Design & Prototyping, CI/CD Development und Location-ReDesign, in denen die CU2 Kreativagentur mannigfaltige große, kleine, spannende, fade, innovative, unterhaltsame und ernsthafte Projekte entwickeln und realisieren konnte, entstand in ihr die fixe Überzeugung: » Wir tun alles, was wir können. Und was wir können, machen wir wirklich gut. Mit NetzAmWerk realisieren wir Projekte im Teamwork – für und mit anderen. « Quelle: https://cu2.team/mission/",
        weblink: "https://cu2.team/",
        lat: 48.20500463736926,     
        lng: 16.355892035897163,
    },
    {
        nr: 13,
        user: "Torismus & Klimafit",
        Adresse: "Gärtnergasse 4c, 2103 Langenzersdorf",
        Mail: "office@tourismusklimafit.at",
        Öffnungszeiten: "",
        intro: "Mit einer klimafitten Angebots- und Produktentwicklung zum wirtschaftlich nachhaltigen Erfolg",
        about: "Der Klimawandel wirkt auf Land- Wasser- oder Forstwirtschaft und daher in vielen Bereichen, die unmittelbar mit dem Tourismus zusammenhängen. Das Reisen ist sehnsuchtsvoller Zeitvertreib und wichtiger Wirtschaftsfaktor, hat aber wiederum Auswirkungen auf Umwelt und Klima. Die Folgen des Klimawandels sind allgegenwärtig. Das Problembewusstsein in der Bevölkerung und bei den Gästen steigt, der „Reise-Klima-Fußabdruck“ avisiert zum Auswahl- und Entscheidungskriterium für eine bestimmte Region. Touristiker und Regionalentwickler sind sensibilisiert, stehen aber vor großen Herausforderungen. Verantwortungsvoller, klimafitter Tourismus bietet Chancen für eine umwelt- und sozialverträgliche wirtschaftliche Entwicklung. Wir unterstützen unsere Kunden mit nachhaltigen Mobilitätslösungen, implementieren klimafitte Angebote und kreative Produkte entlang der touristischen Dienstleistungskette, vernetzen zu klimafreundlichen Unternehmen, Institutionen sowie Förderstellen und motivieren Anbieter ebenso wie Nachfrager zu einem klimabewussten Umdenken. Quelle: https://tourismusklimafit.at/",
        weblink: "https://tourismusklimafit.at/",
        lat: 48.30210650588059,     
        lng: 16.369665141994382,
    },
    {
        nr: 14,
        user: "Transition Austria",
        Adresse: "Burgring 6/2, 8010 Graz",
        Mail: "office@transition.at",
        Öffnungszeiten: "",
        intro: "Wandelinitiativen: Überblicken – Verstehen – Mitmachen.",
        about: "Transition Austria ist eine Plattform und Vernetzung von und für Initiativen des Wandels in Österreich.  Diese Initiativen sind von der Idee der Transition Bewegung inspiriert.  Sie wurden von Einzelpersonen, Gruppen, Initiativen, NGO’s oder Wirtschaftsbetrieben initiiert. Sie suchen Lösungen im Alltag und neue Formen des Zusammenslebens auf kommunaler Ebene. Sie agieren nach dem Motto “Global Denken, Lokal handeln”. Quelle: https://transition.at/transition-austria/",
        weblink: "https://tourismusklimafit.at/",
        lat: 47.07180036574457,      
        lng: 15.444181955456818,
    },
    {
        nr: 15,
        user: "Umblick",
        Adresse: "Hartlgasse 9/13, 1200 Wien",
        Mail: "buero@umblick.at",
        Öffnungszeiten: "",
        intro: "Umweltbildung - Umwelt, Abfall, Energie, Nachhaltigkeit, Mobilität",
        about: "Umblick steht für umfassende Weiterentwicklung im Hinblick auf Themengebiete der Umwelt und Nachhaltigkeit. Wir konzentrieren uns darauf, Menschen und Organisationen bei der Mitgestaltung einer nachhaltigen Zukunft zu unterstützen. Durch unser interdisziplinäres Team erreichen wir Ihre Ziele effizient unter Einbeziehung unterschiedlicher Blickwinkel und kombinierter Ansätze.  Wir schließen die Lücke von reinem Wissen hin zum effektiven Umsetzen. Um­blick hat sich zum Ziel gesetzt Men­schen dabei zu er­mutigen ihre Selbst­­wirk­sam­keit zu be­grei­fen und ihre Hand­lun­gen als wich­tigen Bei­trag für das ge­mein­same Ge­stal­ten einer nach­hal­tig­eren Welt zu er­le­ben. Um diese Mis­sion­en zu er­fül­len be­gin­nen wir be­reits bei den Jüng­sten im Kinder­garten und bieten Umweltbildung wie z.B. Umweltworkshops bis hin zum Pen­sions­al­ter an. Quelle: https://umblick.at/bildung/ueber-uns/",
        weblink: "https://umblick.at/",
        lat: 48.23160827990701,     
        lng: 16.373425396510783 ,
    },
    {
        nr: 16,
        user: "Verband der Akademikerinnen Österreichs",
        Adresse: "Reitschulgasse 2, 1010 Wien",
        Mail: "office.vaoe@aon.at",
        Öffnungszeiten: "",
        intro: "Austrian Federation of University Women",
        about: "Der Verband der Akademikerinnen Österreichs eröffnet qualifizierten und engagierten Frauen internationale und interdisziplinäre Beziehungen und ermutigt zu Qualität, Verantwortung, Respekt und Selbstvertrauen. Der VAÖ, Verband der Akademikerinnen Österreichs, mit Verbandssitz in Wien besteht seit dem Jahr 1922. Er ist die  größte Vereinigung von akademisch gebildeten Frauen Österreichs, mit 6 Landesverbänden (NÖ und Burgenland ist dem LV Wien angegliedert, Vorarlberg ist mit dem LV Tirol vernetzt). Quelle: https://www.vaoe.at/",
        weblink: "https://www.vaoe.at/",
        lat: 48.207431780638956,      
        lng: 16.367350430894483,
    },
    {
        nr: 17,
        user: "Volkshilfe Wien",
        Adresse: "Weinberggasse 77, 1190 Wien",
        Mail: "volkshilfe@volkshilfe-wien.at",
        Öffnungszeiten: "",
        intro: "Gemeinnützige Betriebs-GmbH",
        about: "“Benachteiligungen beseitigen – Erfolge ermöglichen” ist nicht nur kommunikativer Leitsatz der Volkshilfe Wien, sondern seit dem Jahr 1947 integrierter Bestandteil der täglichen Arbeit und des Einsatzes für Menschen in Not. In Not geratene oder hilfsbedürftige Menschen zu versorgen und zu betreuen, ist nach wie vor das zentrale Aufgabengebiet der Volkshilfe Wien. Sie erfüllt aber nicht nur humanitäre Hilfe, sondern ist auch Dienstleister im Auftrag der Gemeinde Wien für die Bereiche Pflege und Betreuung, Wohnungslosenhilfe, Delogierungsprävention, Arbeitsintegration, Flüchtlingsbetreuung sowie Kinder- und Jugendbetreuung. In 23 Bezirksvereinen unterstützen mehr als 200 Funktionär*innen Wiener*innen in Not durch Beratungen, Nothilfe oder Sachleistungen. Die Unterstützung durch Freiwillige und Ehrenamtliche ist ein unverzichtbarer Bestandteil unserer Arbeit innerhalb der Volkshilfe Wien. Mehr als 400 Freiwillige engagieren sich das ganze Jahr über und werden seit 2017 von der Stabstelle Freiwilligenmanagement professionell betreut. Quelle: https://www.volkshilfe-wien.at/uber-uns/uber-uns/",
        weblink: "https://www.volkshilfe-wien.at/",
        lat: 48.243974013967104,       
        lng: 16.33089553274507,
    },
    {
        nr: 18,
        user: "Volkshilfe Österreich",
        Adresse: "Auerspergstraße 4, 1010 Wien",
        Mail: "office@volkshilfe.at",
        Öffnungszeiten: "",
        intro: "Gemeinnützige, überparteiliche und überkonfessionelle Wohlfahrtsorganisation",
        about: "Mit ihren neun Landesorganisationen unterstützt die Volkshilfe Menschen durch ihre sozialen Dienstleistungen. Als soziale Bewegung setzt sie sich auch für die Interessen von sozial Benachteiligten ein. Als soziale Dienstleisterin unterstützen wir Menschen in Notlagen. Als soziale Bewegung erheben wir unsere Stimme für Benachteiligte. Wir bringen ExpertInnenwissen ein und nehmen aktiv an der gesellschaftlichen Entwicklung teil. Quelle: https://www.volkshilfe.at/wer-wir-sind/",
        weblink: "https://www.volkshilfe.at/",
        lat: 48.208322828433054,       
        lng: 16.35587408062162,
    },
    {
        nr: 19,
        user: "Wiener Tafel",
        Adresse: "Laxenburger Straße 365/A6, 123 Wien",
        Mail: "office@wienertafel.at",
        Öffnungszeiten: "",
        intro: "Versorgen statt entsorgen!",
        about: "Die Wiener Tafel - der Verein für sozialen Transfer - rettet bis zu vier Tonnen Lebensmittel pro Tag vor dem Müll und versorgt mit den wertvollen Warenspenden von Handel, Industrie und Landwirtschaft 19.000 Armutsbetroffene in rund 100 Sozialeinrichtungen im Großraum Wien. Die ca. 350 ehrenamtlichen MitarbeiterInnen der Wiener Tafel bringen die Lebensmittel von über 200 Warenspenderunternehmen mit den fünf Wiener Tafel-Hilfslieferfahrzeugen auf kürzestem Weg zu den Armutsbetroffenen in Frauenhäusern, Mutterkindwohnheimen, Obdachlosenbetreuungseinrichtungen und Flüchtlingsherbergen! Quelle: https://www.wienertafel.at/index.php?id=136",
        weblink: "https://www.wienertafel.at/index.php?id=399",
        lat: 48.1362478795239,       
        lng: 16.36022586952234,
    },
    {
        nr: 20,
        user: "ZSI - Zentrum für Soziale Innovation",
        Adresse: "Linke Wienzeile 246, 1150 Wien",
        Mail: "institut@zsi.at",
        Öffnungszeiten: "",
        intro: "Privates non-profit Institut für angewandte Sozialwissenschaften",
        about: "ZSI führt Projekte in Forschung und Anwendung durch und untersucht die gesellschaftliche Einbettung und Wirkung von Innovation und trägt zur Gestaltung und Verbreitung von sozialverträglichen und nachhaltigen Innovationen zur Bewältigung von globalen Herausforderungen bei. Quelle: https://www.zsi.at/de/about_zsi/profile",
        weblink: "https://www.zsi.at/",
        lat: 48.1842582323916,       
        lng: 16.33153067877136,
    },
    {
        nr: 21,
        user: "Arbeit Plus",
        Adresse: "Herklotzgasse 21/3, 1150 Wien",
        Mail: "office@arbeitplus.at",
        Öffnungszeiten: "",
        intro: "Soziale Unternehmen Österreich",
        about: "Soziale Unternehmen, Social Businesses und Social Entrepreneurship sind die Unternehmensformen der Zukunft, daran glauben wir fest. Gerade in Zeiten von Wirtschaftskrisen, der Einsicht, dass unbegrenztes Wirtschaftswachstum in einer Welt endlicher Ressourcen unmöglich ist und einer zunehmenden Verschärfung von Ungleichheit zwischen Reichen und Armen ist es höchst an der Zeit aufzuzeigen, dass es Unternehmen gibt, die einen Unterschied machen: in ihrem Anspruch wirtschaftlich erfolgreich zu sein, in ihrem Bemühen darum, ihren sozialen Integrationsauftrag durch qualitätsvolle und existenzsichernde Beschäftigung und Beratung zu erfüllen und – wie bereits in vielen unserer Mitgliedsorganisationen umgesetzt – einen nachhaltigen Beitrag zu einem ressourcenschonenden und ökologischen Gleichgewicht zu leisten. Quelle: https://arbeitplus.at/willkommen-bei-arbeit-plus/",
        weblink: "https://arbeitplus.at/",
        lat: 48.18990264526622,       
        lng: 16.334350227194964,
    },
    {
        nr: 22,
        user: "BOJA",
        Adresse: "Lilienbrunngasse 18/2/47, 1020 Wien",
        Mail: "boja@boja.at",
        Öffnungszeiten: "",
        intro: "Bundesweites Netzwerk Offene Jugendarbeit",
        about: "bOJA ist das Kompetenzzentrum für Offene Jugendarbeit in Österreich. bOJA vertritt das Handlungsfeld der Offenen Jugendarbeit in Österreich und versteht sich als Kompetenzzentrum für Offene Jugendarbeit, als Service- bzw. Vernetzungsstelle, als Plattform für Wissens- und Informationsaustausch sowie als Fachstelle für Qualitätsweiterentwicklung im Bereich Offene Jugendarbeit. Quelle: https://www.boja.at/ueber-uns",
        weblink: "https://www.boja.at/",
        lat: 48.21540206080334,       
        lng: 16.378622556031257,
    },
    {
        nr: 23,
        user: "ksoe - Katholische Sozialakademie Österreichs",
        Adresse: "Schottenring 35, 1010 Wien",
        Mail: "office@ksoe.at",
        Öffnungszeiten: "",
        intro: "Bildung und Beratung für den gesellschaftlichen Wandel",
        about: "Die ksoe - Katholische Sozialakademie Österreichs - ist eine Akademie für Bildung und Beratung. Sozialethisches Denken und Handeln ist für uns leitend. Unsere Angebote haben zum Ziel, Menschen und Organisationen zu unterstützen, die den gesellschaftlichen Wandel aktiv mitgestalten. In vielfältigen Kooperationen arbeiten wir an einem guten Leben für alle. Quelle: https://www.ksoe.at/ueber-uns",
        weblink: "https://www.ksoe.at/",
        lat: 48.21772494694819,       
        lng: 16.37003558062188,
    },
    {
        nr: 24,
        user: "pro mente austria",
        Adresse: "Lonstorferplatz 1, 4020 Linz",
        Mail: "office@promenteaustria.at",
        Öffnungszeiten: "",
        intro: "Österreichischer Dachverband für Vereine und Gesellschaften für psychische und soziale Gesundheit.",
        about: "Wir vertreten die gemeinsamen Ziele unserer Mitglieder sowohl in Österreich als auch im Ausland und bieten eine Plattform für den unkomplizierten Informationsaustausch. Nach außen stehen wir als Ansprechpartner für alle Stakeholder im Bereich der psychischen und sozialen Gesundheit zur Verfügung. Unser Ziel ist es, die Stellung von Menschen mit psychischen oder psycho-sozialen Problemen in der Gesellschaft zu verbessern und ihrem sozialen Umfeld beizustehen. Dafür unterstützen wir auch andere Organisationen. Ein besonderes Ziel ist die Einhaltung der Menschenrechte und im Besonderen der UN-Konvention über die Rechte von Menschen mit Behinderungen und des europäischen Mental Health Pacts. Daher fördern und fordern wir unparteilich und überkonfessionell die Inklusion und Partizipation aller Menschen und begrüßen ihre Vielfalt. Quelle: https://www.promenteaustria.at/de/pro-mente-austria/leitbild/",
        weblink: "https://www.promenteaustria.at/de/home/",
        lat: 48.29376381590077,     
        lng: 14.3140221806237,
    },
];
