const STADTENTWICKLUNG = [
    {
      nr: 1,
      user: "Das Gramm",
      Adresse: "Neutorgasse 7, 8010 Graz",
      Mail: "hallo@dasgramm.at",
      Öffnungszeiten: "Mo - Fr: 9:00 - 19:00, Sa: 10:00 - 17:00",
      intro: "Regionale Bio-Greisslerei",
      about: "Das Gramm, unsere regionale Greißlerei, wurde im April 2016 in der Neutorgasse eröffnet. Seither liegt unser Fokus auf regionalen Spezialitäten, unverpackten Lebensmitteln aus kontrolliert biologischem Anbau und einer kleinen, aber feinen Auswahl an Zero Waste Artikeln in den Bereichen Haushalt und Körperpflege. Produkte, die eine Verpackung brauchen, sind in Pfandgläsern oder Papiersackerln erhältlich, um so besonders Einwegplastik bestmöglich zu vermeiden. Bei uns kannst du genau diese Menge kaufen, die du auch wirklich brauchst – so gehen wir auch bei dir zuhause gegen Lebensmittelverschwendung vor. Unser “kleines Gramm” ist mehr als nur eine Greißlerei; es ist ein Ort zum Ankommen und Wohlfühlen, an dem du dich mit unserem Experten:innen-Team austauschen oder auch einfach in Ruhe die Atmosphäre auf dich wirken lassen kannst. Quelle: https://www.dasgramm.at/das-sind-wir/#wiewir",
      weblink: "https://www.dasgramm.at/",
      lat: 47.070688574948505, 
      lng: 15.436974564704707,
    },
    {
        nr: 2,
        user: "Ernährungsrat Wien",
        Adresse: "nicht angegeben",
        Mail: "kontakt@ernaehrungsrat-wien.at",
        Öffnungszeiten: "",
        intro: "vernetzen - verstehen - verändern",
        about: "Wir sind ein zivilgesellschaftlicher Zusammenschluss von, derzeit ca. 30, engagierten Menschen aus den verschiedensten Bereichen des Wiener Ernährungssystems: Gastronomie und Forschung, urbane Landwirtschaft und zivilgesellschaftliche Organisationen, Beratung und Interessensvertretung, Gemeinschaftsverpflegung und Food Coops. Diese Hintergründe und die Auseinandersetzung mit der eigenen Ernährung und deren Auswirkungen - der persönliche Bezug zu den Themen Lebensmittel und Ernährung hat unsere Gruppe zusammengeführt. Uns verbindet das gemeinsame Ziel, durch den Ernährungsrat Wien zu einem ökologisch zukunftsfähigen und sozial gerechten Ernährungssystem in der Wiener Stadt-Region beizutragen. Jedes (neue) Mitglied bereichert den Ernährungsrat Wien mit neuen Perspektiven. Geben wir der Zivilgesellschaft gemeinsam eine starke Stimme für ein demokratisches, sozial gerechtes und ökologisch zukunftsfähiges Ernährungssystem! Quelle: https://ernaehrungsrat-wien.at/ueber-uns/wir/",
        weblink: "https://ernaehrungsrat-wien.at/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
        nr: 3,
        user: "Initiative gemeinsam bauen & wohnen",
        Adresse: "Bloch-Bauer-Promenade 28/2/15, 1100 Wien",
        Mail: "kontakt@inigbw.org",
        Öffnungszeiten: "",
        intro: "Verein, um gemeinschaftliches Bauen und Wohnen in Wien und in ganz Österreich in Schwung zu bringen",
        about: "Die Initiative bietet die Plattform, um all diejenigen zusammen zu führen, die das Thema des gemeinschaftlichen Bauens und Wohnens weiter voran bringen wollen. Sie richtet sich dabei sowohl an Professionist*innen wie Architekt*innen, Bauträger*innen und Politiker*innen als auch an Private, die das Bauen und Wohnen in Gemeinschaft für sich in Betracht ziehen. Ziel ist, die Entstehungsbedingungen für gemeinschaftliche Wohnformen zu verbessern und die Umsetzung konkreter Projekte zu unterstützen. Dazu bedarf es insbesondere politischer Entscheidungen und des Engagements durch die öffentliche Hand. Quelle: https://www.inigbw.org/die-initiative",
        weblink: "https://www.inigbw.org/",
        lat: 48.17857206159186,   
        lng: 16.387274156030298,
    },
    {
        nr: 4,
        user: "Schwendermarkt",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "initiative-schwendermarkt@gmx.at",
        Öffnungszeiten: "",
        intro: "Initiative zur Erhaltung und Belebung des Schwendermarktes",
        about: "Der Schwendermarkt ist der kleinste Markt in Wien. Interessante Geschäfte mit Bio und regionalen Produkten von bauern aus der Umgebung von Wien und dem weinviertel. gemütliche Atmosphäre in Markt Cafés, sehr gutes Essen inkl einer Vietnamesin, die super kocht, Marktstände mit Gemüse, Käse, Obst. tolles großes Café in hippem Blumenladen,.... Quelle: https://www.facebook.com/Schwendermarkt/reviews/?ref=page_internal Review of: Karin N. York",
        weblink: "http://www.schwendermarkt.at/",
        lat: 48.19097235033396, 
        lng: 16.326267103155473,
    },
    {
        nr: 5,
        user: "Institut für ökologische Stadtentwicklung",
        Adresse: "Seidengasse 13 / 3, 1070 Wien",
        Mail: "office@oekostadt.at",
        Öffnungszeiten: "",
        intro: "Ökostadt - Lebenswerte Stadt",
        about: "Im Institut für ökologische Stadtentwicklung hat sich ein interdisziplinäres Team von mehr als 20 Fachleuten mit dem Ziel der Errichtung sowie fachlichen Unterstützung der Planung und Errichtung von nachhaltigen und ökologischen Modellsiedlungen („Ökostadt“) zusammengefunden. Durch Integration ökologischer Einzelmaßnahmen für alle Sektoren wie Raumordnung und Siedlungsplanung, Verkehr, Energie, Wasserversorgung und Abwasserbehandlung, Abfallwirtschaft, Landschaftsplanung oder Produktion und Handel von Gütern wird eine flächensparende städtische Bauweise und eine umwelt- und sozialverträgliche Gestaltung der technischen und wirtschaftlichen Einrichtungen erreicht. Kompakte Siedlungseinheiten mit ausgewogener Nutzungsmischung ermöglichen kurze Wege für Fußgänger und erleichtern damit den Verzicht auf individuelle motorisierte Verkehrsmittel (Kfz). Niedrigenergiebauweise oder Passivhausstandard ist durch weitgehende Südorientierung der Gebäude erreichbar. Die Anordnung der Siedlungseinheiten entlang von Achsen begünstigt die Erschließung durch Linien des öffentlichen Verkehrs.Die „Ökostadt“ bietet eine Alternative zu dem durch Umweltbelastungen vielfach beeinträchtigten Stadtleben, dient aber auch als Vorbild für die Umgestaltung bestehender Städte. Da wie dort erhöht sich die Lebensqualität. Quelle: http://www.oekostadt.at/de/info.htm",
        weblink: "http://www.oekostadt.at/",
        lat: 48.200430955975506,    
        lng: 16.345775136443077,
    },
    {
        nr: 6,
        user: "K4DP",
        Adresse: "Gersthofer Strasse 162, 1180 Wien",
        Mail: "info@k4dp.org",
        Öffnungszeiten: "",
        intro: "Knowledge for Development Parthnership",
        about: "The Knowledge for Development Partnership, which was founded under Austrian law at the Palais des Nations, Geneva, on 3 April 2017 during the “Knowledge for Development: Global Partnership Conference”. We are a non-profit organisation (NGO) promoting the global advancement of peaceful, wealthy, sustainable, and inclusive knowledge societies, fostering global knowledge partnerships for achieving the Sustainable Development Goals of the United Nations and implementing the Agenda 2030. With partners from all over the world, K4DP aims to localize and implement the global Agenda Knowledge for Development. Quelle: https://www.k4dp.org/",
        weblink: "https://www.k4dp.org/",
        lat: 48.23876941918626,     
        lng: 16.320031740143154,
    },
    {
        nr: 7,
        user: "Landentwicklung Steiermark",
        Adresse: "Hans-Sachs-Gasse 5, 8010 Graz",
        Mail: "office@landentwicklung-steiermark.at",
        Öffnungszeiten: "",
        intro: "BETEILIGUNG ALS MOTOR FÜR EINE STARKE GEMEINSCHAFT",
        about: "Eine Gemeinde. Eine Region. Das sind keine Flächen, das sind immer Menschen. Was Gemeinden und Regionen brauchen, um zukunftsfähig zu sein, ist eine wertschätzende Beziehungskultur. Eine Kultur, in der jeder spürt, dass er gebraucht wird, dass alle voneinander lernen und miteinander wachsen können. Die Landentwicklung Steiermark schafft Beteiligung, und damit ein „Wir“ für die Zukunft. Quelle: https://www.landentwicklung-steiermark.at/",
        weblink: "https://www.landentwicklung-steiermark.at/",
        lat: 47.06921522378337,     
        lng: 15.442635180346967 ,
    },
    {
        nr: 8,
        user: "OKIDROM",
        Adresse: "Lindengasse 32/10, 1070 Wien",
        Mail: "richard.pfeifer@oikodrom.org",
        Öffnungszeiten: "",
        intro: "the Vienna Institute for Urban Sustainability",
        about: "We are a private research institute following our goal to open spaces and opportunities in creating a sustainable future. We empower human actors through participatory processes, starting from local real-life situations. In a multicultural research network we use trans- and interdisciplinary approaches to generate theses and theories and connect scientific and non scientific knowledge. Quelle: https://oikodrom.org/",
        weblink: "http://www.oikodrom.org/",
        lat: 48.20026388356145,      
        lng: 16.35043715603093,
    },
    {
        nr: 9,
        user: "Passivhaus Austria",
        Adresse: "Anichstraße 29/54, 6020 Innsbruck",
        Mail: "office@passivhaus-austria.org",
        Öffnungszeiten: "",
        intro: "Alle Informationen rund ums Passivhaus",
        about: "Das Passivhaus-Experten-Netzwerk setzt sich aus Architekten, Planern, Bauphysikern, Haustechnikplanern, Bauträgern, Bauherren, Bauausführenden, Komponentenherstellern, Baustoffindustrie, Energieberatern, Weiterbildungsinstitutionen, Universitäten und Kommunen zusammen und wird aktiv vom Passivhaus Institut unterstützt. Quelle: https://passivhaus-austria.org/content/passivhaus-austria",
        weblink: "https://passivhaus-austria.org/",
        lat: 47.26400420409408,      
        lng: 11.390211605734585,
    },
    {
        nr: 10,
        user: "SDG Botschaftr:innen",
        Adresse: "8010 Graz",
        Mail: "info@sdg-botschafterinnen.at",
        Öffnungszeiten: "",
        intro: "Verein für nachhaltige Entwicklung und zur Umsetzung der Agenda 2030",
        about: "Wir sind eine Gruppe junger und engagierter Erwachsener, die sich seit 2018 für die Sustainable Development Goals (SDGs) der Vereinten Nationen einsetzt. Wir wollen das Wissen um die Agenda 2030 und die 17 Ziele für nachhaltige Entwicklung in die Welt tragen und einen Beitrag zu ihrer Erreichung leisten! Seit Sommer 2019 werden wir vom Europäischen Solidaritätskorps gefördert und können uns damit noch besser für unser Anliegen einsetzen. Quelle: https://sdg-botschafterinnen.at/",
        weblink: "https://sdg-botschafterinnen.at/",
        lat: 47.077815439093854,      
        lng: 15.449824505730058,
    },
    {
        nr: 11,
        user: "SPES",
        Adresse: "Panoramaweg 1, 4553 Schlierbach",
        Mail: "hotel@spes.co.at",
        Öffnungszeiten: "",
        intro: "Zukunftsakademie",
        about: "Die SPES Zukunftsakademie ist eine überparteiliche Bildungseinrichtung, die vom gemeinnützigen SPES Verein und mehr als 100 privaten Teilhaber/inne/n getragen wird. Die Aktivitäten dienen dem Gemeinwohl gegenwärtiger und künftiger Generationen und sind nicht auf Gewinn ausgerichtet. Quelle: https://www.spes.co.at/das-ist-spes/",
        weblink: "https://www.spes.co.at/",
        lat: 47.932847657702126,      
        lng: 14.125984801505963,
    },
    {
        nr: 12,
        user: "Stadt Labor",
        Adresse: "Griesgasse 40, 8020 Graz",
        Mail: "office@stadtlaborgraz.at",
        Öffnungszeiten: "",
        intro: "Stadt gemeinsam entwickeln",
        about: "Das StadtLABOR ist ein Innovationslabor für nachhaltige und lebenswerte Städte und Gemeinden. Wir verstehen die Transformation von Stadtteilen, Quartieren und Standorten als offenen und kooperativen Entwicklungsprozess, der Räume für Inspiration, Kreativität, gemeinsames Lernen und Innovation schafft. Quelle: https://www.stadtlaborgraz.at/de/ueber-uns",
        weblink: "https://www.stadtlaborgraz.at/de",
        lat: 47.06801624167627,      
        lng: 15.43396770093853,
    },
    {
        nr: 13,
        user: "STRATECO",
        Adresse: "Ruckerlberggasse 13, 8020 Graz",
        Mail: "office@strat.eco",
        Öffnungszeiten: "",
        intro: "Information über Prozessoptimierung und Ökologische Bewertung",
        about: "Wir wollen die Welt ein Stückchen nachhaltiger machen – und glauben daran, dass wir gemeinsam mit Ihnen Ihre Produkte, Dienstleistungen, Prozesse und Ressourcennutzung ökologisch und oft auch ökonomisch nachhaltiger gestalten können, um dadurch Ihr Unternehmen und die regionale Wertschöpfung zu stärken. Das bedeutet für uns: Wir unterstützen Wirtschafts- und Lebensweisen in ihrem Ziel, allen eine stabile Zukunft zu bescheren. Quelle: https://www.strat.eco/",
        weblink: "https://www.strat.eco/",
        lat: 47.06880837066728,       
        lng: 15.464438743813336,
    },
    {
        nr: 14,
        user: "Transition Austria",
        Adresse: "Burgring 6/2, 8010 Graz",
        Mail: "office@transition.at",
        Öffnungszeiten: "",
        intro: "Wandelinitiativen: Überblicken – Verstehen – Mitmachen.",
        about: "Transition Austria ist eine Plattform und Vernetzung von und für Initiativen des Wandels in Österreich.  Diese Initiativen sind von der Idee der Transition Bewegung inspiriert.  Sie wurden von Einzelpersonen, Gruppen, Initiativen, NGO’s oder Wirtschaftsbetrieben initiiert. Sie suchen Lösungen im Alltag und neue Formen des Zusammenslebens auf kommunaler Ebene. Sie agieren nach dem Motto “Global Denken, Lokal handeln”. Quelle: https://transition.at/transition-austria/",
        weblink: "https://tourismusklimafit.at/",
        lat: 47.07180036574457,      
        lng: 15.444181955456818,
    },
    {
        nr: 15,
        user: "Urban Forum",
        Adresse: "Neunkirchner Straße 15/7, 2700 Wiener Neustadt",
        Mail: "office@urbanforum.at",
        Öffnungszeiten: "",
        intro: "Egon Matzner-Institut für Stadtforschung",
        about: "Nach wie vor steht die zentrale Forderung nach einem aufgabenorientierten Finanzausgleich im Raum, wurde bis dato aber noch immer nicht erfüllt. Aus diesem Grund befinden sich zahlreiche große Kommunen im finanziellen Abseits, müssen auf einen drastischen Sparkurs setzen und können kaum noch Investitionen tätigen. Es kann aber nicht angehen, dass Gelder die nach EU Definition in den ländlichen Raum fließen sollen, in Österreich fast ausschließlich dem Landwirtschaftssektor zu Gute kommen. Insbesondere auch die kleineren urbanen Zentren in den Regionen sollen von diesen Förderungen profitieren. Darüber hinaus wird es aber auch wichtig sein, die großen Ballungsräume mit ihren Herausforderungen des Bevölkerungszuwachses und der Integration von Zuwanderern nicht alleine zu lassen. Diesem bedeutenden Thema will sich unser neu gegründeter, überparteilicher Verein Urban Forum verstärkt widmen. Zudem gilt es, Bewusstsein zu schaffen für stadtpolitische Anliegen und die Notwendigkeit von Strukturreformen. Wir wollen grundsätzlich als Interessensvertretung für Städte auftreten und dem urbanen Raum ein funktionierendes Netzwerk bieten. Weiters werden wir mit regelmäßigen Veranstaltungen zu Urbanitätsthemen und der Herausgabe von Fachpublikationen aufhorchen lassen. Quelle: https://www.urbanforum.at/index.php",
        weblink: "https://www.urbanforum.at/",
        lat: 47.811765487523424,       
        lng: 16.243947140678504,
    },
    {
        nr: 16,
        user: "Verband der Akademikerinnen Österreichs",
        Adresse: "Reitschulgasse 2, 1010 Wien",
        Mail: "office.vaoe@aon.at",
        Öffnungszeiten: "",
        intro: "Austrian Federation of University Women",
        about: "Der Verband der Akademikerinnen Österreichs eröffnet qualifizierten und engagierten Frauen internationale und interdisziplinäre Beziehungen und ermutigt zu Qualität, Verantwortung, Respekt und Selbstvertrauen. Der VAÖ, Verband der Akademikerinnen Österreichs, mit Verbandssitz in Wien besteht seit dem Jahr 1922. Er ist die  größte Vereinigung von akademisch gebildeten Frauen Österreichs, mit 6 Landesverbänden (NÖ und Burgenland ist dem LV Wien angegliedert, Vorarlberg ist mit dem LV Tirol vernetzt). Quelle: https://www.vaoe.at/",
        weblink: "https://www.vaoe.at/",
        lat: 48.207431780638956,      
        lng: 16.367350430894483,
    },
    {
        nr: 17,
        user: "virtual vehicle",
        Adresse: "Inffeldgasse 21a, 8010 Graz",
        Mail: "info@v2c2.at",
        Öffnungszeiten: "",
        intro: "Leidenschaft für elekrifizierte, autonome und vernetzte Fahrzeuge",
        about: "Virtual Vehicle ist ein führendes internationales F&E Zentrum für die Automobil-und Bahnindustrie. Das Zentrum konzentriert sich auf die konsequente Virtualisierung der Fahrzeugentwicklung. Diese Verknüpfung von numerischen Simulationen und Hardware-Tests führt zu einem umfassenden Hardware-Software-System-Design. Quelle: https://www.v2c2.at/deu/",
        weblink: "https://www.v2c2.at/deu/",
        lat: 47.058310296863084,       
        lng: 15.463768138264388,
    },
    {
        nr: 18,
        user: "Ökosoziales Formun Wien",
        Adresse: "Stadiongasse 6-8, 1010 Wien",
        Mail: "wien@oekosozial.at",
        Öffnungszeiten: "",
        intro: "Für die Menschen in unserer Stadt und unsere städtische Umwelt – für eine lebenswerte Gegenwart und Zukunft!",
        about: "Mit unseren Projekten und Aktivitäten fördern wir einen respektvollen Umgang mit der Natur unserer Lebensgrundlage und ein friedliches und solidarisches Miteinander der Menschen in unserer Stadt. Wir beziehen uns dabei auf die Agenda 2030 und ihre 17 Ziele für Nachhaltige Entwicklung (Sustainable Development Goals, kurz: „SDGs“) – den weltweiten UNO-Aktionsplan für Nachhaltige Entwicklung. Quelle: https://oekosozial.at/wien/was-wir-tun/",
        weblink: "https://oekosozial.at/wien/",
        lat: 48.20940797658662,       
        lng: 16.356514269524183,
    },
   ];