const UMWELT = [
    {
        nr: 1,
        user: "ARGE Abfallvermeidung",
        Adresse: "Puchstraße 41, 8010 Graz",
        Mail: "office@arge.at",
        Öffnungszeiten: "",
        intro: "Umweltschutzunternehmen",
        about: "Die ARGE konzipiert und implementiert Projekte in den Bereichen Abfallvermeidung, Ressourcenschonung und nachhaltige Entwicklung. Die ARGE ist eine Non-Profit Organisation, die im Jahr 1982 gegründet wurde. Wir konzipieren und organisieren regionale, nationale und internationale Projekte im Bereich nachhaltige Entwicklung und kommunale Abfallwirtschaft. Unsere erste Priorität ist -wie unser Name schon sagt- die Abfallvermeidung. Der schonende Umgang mit Ressourcen und der Schutz unserer Umwelt ist Fokus unserer Arbeit. Wir betrachten die Abfall- und Ressourcenwirtschaft im sozialen, ökologischen und ökonomischen Kontext. Ein wesentlicher Teil unserer Aktivitäten ist daher die Kooperation mit sozialwirtschaftlichen Einrichtungen und die Schaffung von Arbeitsplätzen im Umweltbereich. Quelle: https://www.facebook.com/ArgeAbfallvermeidung/",
        weblink: "https://www.arge.at/",
        lat:  47.05001107528067, 
        lng: 15.436887611278067,
    },
    {
        nr: 2,
        user: "ARGE Schöpfungsveranstaltung",
        Adresse: "Petersplatz 1, 1010 Wien",
        Mail: "office@argeschoepfung.at",
        Öffnungszeiten: "",
        intro: "Kirchliche Umweltarbeit",
        about: "Seit über 25 Jahren ist die ARGE Schöpfungsverantwortung in Kirche und Gesellschaft aktiv. Sie ist Initiator der kirchlichen Umweltarbeit in Österreich und Mitbegründer des EUROPEAN CHRISTIAN ENVIRONMENTAL NETWORKS (ECEN). Im Rahmen der Initiative zur Einführung der SCHÖPFUNGSZEIT agiert sie international. Die Umsetzung erfolgt projektbezogen mit einem Team von engagierten Mitarbeitern, Experten aus Natur- und Geisteswissenschaften. Mit einem laufenden Bildungsprogramm und ökosozialen Handlungsmodellen begleitet und unterstützt sie engagierte Personen und Institutionen sowie einschlägige Netzwerke. Als Gründungsmitglied des EUROPÄISCHEN CHRISTLICHEN UMWELTNETZWERKES (ECEN) bietet sie Partizipation am internationalen kirchlichen Umweltgeschehen. Zahlreiche Initiativen erfolgen in Kooperation mit Umwelt- und Entwicklungsorganisationen. Für Ihre Tätigkeit wurde die ARGE Schöpfungsverantwortung mit dem Staatspreis der Republik Österreich, dem Konrad-Lorenz-Preis ausgezeichnet und erhielt für die Wahrnehmung der Trias des „Konziliaren Prozesses für Gerechtigkeit – Frieden – Bewahrung der Schöpfung“ die Europäische Friedensrose Waldhausen. Quelle: https://www.argeschoepfung.at/ueber-uns/ueberblick.html",
        weblink: "https://www.argeschoepfung.at/",
        lat: 48.209195875185195, 
        lng: 16.370094671021324

    },
    {
        nr: 3,
        user: "ARCHE NOAH",
        Adresse: "Obere Straße 40, 3553 Schiltern",
        Mail: "info@arche-noah.at",
        Öffnungszeiten: "",
        intro: "Verein für Erhalt und Entwicklung der Kulturpflanzenvielfalt",
        about: "Seit über 30 Jahren setzen sich Menschen im Verein ARCHE NOAH für den Erhalt und die Entwicklung der Kulturpflanzenvielfalt ein. Der Verein ARCHE NOAH entstand 1989 (Geschichte des Vereins) auf Initiative von GärtnerInnen, BäuerInnen und JournalistInnen, die das Saatgut als Grundlage der Ernährung buchstäblich wieder in die eigenen Hände nehmen wollten. Denn: Seit 1900 ist die Vielfalt unserer Kulturpflanzen durch die Industrialisierung der Landwirtschaft weltweit dramatisch – um 75% – zurückgegangen (Details zum Verlust der Vielfalt)! Heute gefährden Gentechnik, Saatgut-Monopole, Klimawandel und Kriege dieses kostbare Erbe. ARCHE NOAH hält dem eine positive Vision (Leitbild des Vereins) und zahlreiche Aktivitäten entgegen: ARCHE NOAH bewahrt und pflegt tausende gefährdete Gemüse-, Obst- und Getreidesorten. Erfolgreich arbeiten wir daran, traditionelle und seltene Sorten wieder in die Gärten und auf den Markt zu bringen – dank der Unterstützung von über 17.000 engagierten Mitgliedern und Förderern. Quelle: https://www.arche-noah.at/ueber-uns",
        weblink: "https://www.arche-noah.at/",
        lat: 48.51896771558353, 
        lng: 15.618738735905062,

    },
    {
    
        nr: 4,
        user: "BirdLife",
        Adresse: "Museumsplatz 1/10/8, 1070 Wien",
        Mail: "office@birdlifeat",
        Öffnungszeiten: "",
        intro: "Gesellschaft für Vogelkunde",
        about: "Wir geben Vägeln eine Stimme. BirdLife Österreich ist Partner von BirdLife International, dem weltweit größten aktiven Netzwerk von Natur- und Vogelschutz-Organisationen mit über 10 Millionen Unterstützern in über 120 Ländern. BirdLife Österreich ist als gemeinnütziger Verein die einzige bundesweit tätige ornithologische Vereinigung Österreichs und verwirklicht seit der Gründung 1953 wissenschaftlich fundierte Natur- und Vogelschutzprojekte in vier Kernbereichen: Artenschutz, Schutzgebiete & Lebensräume, Nachhaltigkeit, Bewusstseinsbildung. Quelle: https://www.birdlife.at/page/unserteam",
        weblink: "https://www.birdlife.at/" ,
        lat: 48.20279043802087, 
        lng: 16.35914381979702,
    },
    {
    
        nr: 5,
        user: "Bündnis Alpenkonvention Kärnten",
        Adresse: "Proboj 2, 9113 Sittersdorf",
        Mail: "unglaub@archi-noah.at",
        Öffnungszeiten: "",
        intro: "Teil der Alpenkonvention zum Schutz und für nachhaltige Entwicklung des gesamten Alpenraumes",
        about: "Das gemeinsame Ziel unserer Mitgliedorganisationen ist die  Sicherung einer lebenswerten und intakten Umwelt für die künftigen Generationen sowie Entwicklung einer zukunftsfähigen Lebens- und Wirtschaftsweise. Dies ist auch Botschaft und Inhalt der rechtsverbindlichen Alpenkonvention. Sie bildet daher die Grundlage unserer Arbeit. Wir möchten dazu beitragen, dass in Kärnten in einem gemeinsamen gesellschaftlichen Prozess die Umsetzung der Alpenkonvention Schritt für Schritt vorangetrieben wird. Quelle: https://www.buendnisalpenkonvention.at/ueber-uns",
        weblink: "https://www.buendnisalpenkonvention.at/" ,
        lat: 46.554567127891396,
        lng: 14.598284144200157,
    },
    {
    
        nr: 6,
        user: "Climates Austria",
        Adresse: "Lindengasse 56/18-19, 1070 Wien",
        Mail: "hello@climatesaustria.org",
        Öffnungszeiten: "",
        intro: "Jugend für eine klimaverträgliche Zukunft",
        about: "CliMates Austria bringt Bewegung ins Klima. Wir nehmen Einfluss auf die Klimapolitik, bestärken junge Changemaker*innen, machen Klimabildung und schreiben über wichtige klimapolitische Themen. Wir sind junge Bürger*innen, die die Welt verändern. CliMates Austria ist eine ehrenamtliche NGO und Teil des internationalen Jugendnetzwerks CliMates. Und Du kannst jetzt als Mitglied „Mate“ Teil davon werden! Quelle: https://climatesaustria.org/",
        weblink: "https://climatesaustria.org/" ,
        lat: 48.19987970442615,
        lng: 16.346090278771765,
    },
    {
    
        nr: 7,
        user: "Die Umweltberatung Wien",
        Adresse: "Buchengasse 77/4, 1100 Wien",
        Mail: "service@umweltberatung.at",
        Öffnungszeiten: "",
        intro: "Individuelle Beratung für Privatpersonen sowie für Unternehmen.",
        about: "Seit 1988 informiert und berät DIE UMWELTBERATUNG Privathaushalte und Betriebe und arbeitet in Umweltschutz-Projekten. Von diesem Know-how profitieren unsere Kundinnen und Kunden sowie ProjektpartnerInnen. DIE UMWELTBERATUNG bereitet ökologisches Wissen gut verständlich und praxisorientiert auf. Unsere BeraterInnen beantworten Ihre Anfragen individuell und firmen-unabhängig. Wir beraten private Haushalte, Bildungseinrichtungen, Institutionen und Betriebe. DIE UMWELTBERATUNG verwirklicht zukunftsweisende Projekte. Quelle: https://www.umweltberatung.at/ueber-uns",
        weblink: "https://www.umweltberatung.at/" ,
        lat: 48.1749255624965,
        lng: 16.374404598358936,
    },
    {
    
        nr: 9,
        user: "E. C. O.",
        Adresse: "Lakeside B07b, 9020 Klagenfurt",
        Mail: "office@e-c-o.at",
        Öffnungszeiten: "",
        intro: "Institut für Ökologie",
        about: "Wir begeistern uns für die Vielfalt der Natur und sichern ihren Erhalt auch für zukünftige Generationen. Als Forschungs- und Beratungsunternehmen für „Naturschutz im 21. Jahrhundert“ begleiten und unterstützen wir unsere internationalen und nationalen Partner:innen dabei, natürliche Lebensräume zu bewahren und zu verbessern, außergewöhnliche Naturerlebnisse zu ermöglichen und die Lebens- und Wirtschaftsbedingungen in den jeweiligen Regionen weiterzuentwickeln. Mit unseren ökologischen Fachplanungen, naturräumlichen Erhebungen, innovativen Kommunikationskonzepten und nachhaltiger Entwicklungszusammenarbeit setzen wir uns aktiv für die Erfüllung der globalen Sustainable Development Goals ein. Quelle: https://e-c-o.at/home.html",
        weblink: "https://e-c-o.at/home.html",
        lat: 46.61445647600445,
        lng: 14.263496343802236,
    },
    {
    
        nr: 10,
        user: "EU Umweltbüro",
        Adresse: "Strozzigasse 10/8-9, 1080 Wien",
        Mail: "office@eu-umweltbuero.at",
        Öffnungszeiten: "",
        intro: "Kompetenzzentrum für Europäische Umweltpolitik und -gesetzgebung",
        about: "Das EU Umweltbüro in Wien wurde 1994 als Kompetenzzentrum für Europäische Umweltpolitik und -gesetzgebung gegründet und ist im Umweltdachverband – der größten österreichischen Dachorganisation von Umweltschutzorganisationen – angesiedelt. Die Kernkompetenzen des EU-Umweltbüros sind umfassende Kenntnisse des politischen Gesetzwerdungsprozesses auf europäischer Ebene und Informationen über derzeitige und zukünftige Entwicklungen im Bereich EU-Umweltpolitik. Das Umweltbüro vertritt die österreichischen Mitglieder im Vorstand des europäischen Dachverbands European Environmental Bureau (EEB)in Brüssel. Das Umweltbüro ist auf europäischer und  internationaler Ebene gut vernetzt und arbeitet auf Deutsch und Englisch. Quelle: https://www.eu-umweltbuero.at/ueber-uns/was-wir-tun/",
        weblink: "https://www.eu-umweltbuero.at/",
        lat: 48.20739603144972, 
        lng: 16.349451311852835,
    },
    {
    
        nr: 11,
        user: "EVAL",
        Adresse: "Rössing 311, 8972 Ramsau am Dachstein",
        Mail: "khh@evalww.com",
        Öffnungszeiten: "",
        intro: "Ehrfurcht vor allem Leben",
        about: "Gemeinnützige Gemeinschaft zur Förderung des friedlichen Zusammenlebens der Menschen und des respektvollen Umgangs mit der Natur. Vernetzungs- und Informations-Plattform für alle Initiativen, Gruppen und Vereine, die sich zum EVAL-Prinzip - Ehrfurcht Vor Allem Leben - bekennen. Die EVAL-Datenbank als Teil des EVAL-INFO-SYSTEMS (EIS) steht allen Bürgern zur Verfügung die sich frei von Lobbyisteninteressen jeglicher Art und ohne Werbung und persönliche Datenerfassung informieren möchten. Unser Ziel: Urteilsfähige und selbstkritische DemokratenInnen. Quelle: https://www.evalww.com/",
        weblink: "https://www.evalww.com/",
        lat: 47.43266380070504,  
        lng: 13.752812580751053,
    },
    {
    
        nr: 12,
        user: "Ernährungsrat Wien",
        Adresse: "nicht angegeben",
        Mail: "kontakt@ernaehrungsrat-wien.at",
        Öffnungszeiten: "",
        intro: "vernetzen - verstehen - verändern",
        about: "Wir sind ein zivilgesellschaftlicher Zusammenschluss von, derzeit ca. 30, engagierten Menschen aus den verschiedensten Bereichen des Wiener Ernährungssystems: Gastronomie und Forschung, urbane Landwirtschaft und zivilgesellschaftliche Organisationen, Beratung und Interessensvertretung, Gemeinschaftsverpflegung und Food Coops. Diese Hintergründe und die Auseinandersetzung mit der eigenen Ernährung und deren Auswirkungen - der persönliche Bezug zu den Themen Lebensmittel und Ernährung hat unsere Gruppe zusammengeführt. Uns verbindet das gemeinsame Ziel, durch den Ernährungsrat Wien zu einem ökologisch zukunftsfähigen und sozial gerechten Ernährungssystem in der Wiener Stadt-Region beizutragen. Jedes (neue) Mitglied bereichert den Ernährungsrat Wien mit neuen Perspektiven. Geben wir der Zivilgesellschaft gemeinsam eine starke Stimme für ein demokratisches, sozial gerechtes und ökologisch zukunftsfähiges Ernährungssystem! Quelle: https://ernaehrungsrat-wien.at/ueber-uns/wir/",
        weblink: "https://ernaehrungsrat-wien.at/",
        lat: 48.20452907220192,  
        lng: 16.37985817011294,
    },
    {
    
        nr: 13,
        user: "FiBL",
        Adresse: "Doblhoffgasse 7/10, 1010 Wien",
        Mail: "info.oesterreich@fibl.org",
        Öffnungszeiten: "",
        intro: "Forschungsinstitut für biologischen Landbau",
        about: "Das FiBL verfügt über Kompetenzen in allen Belangen der biologischen Landwirtschaft: Bodenbewirtschaftung und Pflanzenbau, artgerechte Tierhaltung und ganzheitliche Tiergesundheit, sozioökonomische Belange, biologische Lebensmittelverarbeitung sowie umfassende Analysen des Biomarktes. Zudem engagiert sich das FiBL seit vielen Jahren auf internationaler Ebene für die Entwicklung des Biolandbaus zum Beispiel beim Biolandbau-Weltdachverband IFOAM – Organics International. Das FiBL ist Partner in Forschungs- und Entwicklungsprojekten der Europäischen Union (EU), der Welternährungsorganisation FAO und vieler weiterer nationaler und internationaler Institutionen. Das FiBL unterstützt die Entwicklung zukunftsfähiger Landwirtschaft in Afrika, Asien, Lateinamerika und Osteuropa in enger Zusammenarbeit mit lokalen Partnerorganisationen. FiBL-Forscher untersuchen in Langzeitversuchen lokale und biologische Anbausysteme und bieten Expertise im Bereich der Marktentwicklung an. Quelle: https://www.fibl.org/de/ueber-uns.html",
        weblink: "https://www.fibl.org/de/",
        lat: 48.2086582275331,  
        lng: 16.355933269660643,
    },
    {
    
        nr: 14,
        user: "Plattform Footprint",
        Adresse: "Jandagasse 7 Haus 1, 1210 Wien",
        Mail: "office@footprint.att",
        Öffnungszeiten: "",
        intro: "Verein zur Förderung des Bewusstseins für den Ökologischen Fußabdruck",
        about: "Die Plattform Footprint ist eine Allianz von Umwelt- und Entwicklungspolitischen Organisationen, die den „Ökologischen Fußabdruck“ als wesentliche Maßzahl für die Zukunftsfähigkeit unserer Gesellschaft verankern will. Gemeinsam mit unseren Partnerorganisationen wollen wir durch Lobbying- und Aufklärungsarbeit zum Thema Footprint Bewusstseinsbildung, Handlungseinsicht und politischen Druck für nachhaltige gesellschaftliche Veränderung erzeugen. Quelle:https://www.footprint.at/",
        weblink: "https://www.footprint.at/",
        lat: 48.2862739216721, 
        lng: 16.410748398498882, 
    },
    {
    
        nr: 15,
        user: "Forum Wissenschaft & Umwelt",
        Adresse: "Palmgasse 3/2, 1150 Wien",
        Mail: "office@fwu.at",
        Öffnungszeiten: "",
        intro: "Gemeinnütziger Verein",
        about: "Wir sind eine unabhängige Vereinigung von Wissenschaftlerinnen und Wissenschaftlern, die das Ziel verfolgt, fachübergreifende Beiträge für eine zukunftsverträgliche Entwicklung von Umwelt, Gesellschaft und Wirtschaft zu leisten. Wir wollen der gesellschaftlichen Verantwortung unserer wissenschaftlichen Tätigkeit gerecht werden und bekennen uns zu Werten wie Vielfalt des Lebens und eine zukunftsfähige, humane Gesellschaft. Quelle: https://fwu.at/impressum/",
        weblink: "https://fwu.at/",
        lat: 48.19455632077085,  
        lng: 16.338057098496236,
    },
    {
    
        nr: 16,
        user: "Future Aid",
        Adresse: "nicht angegeben",
        Mail: "future-aid@future-aid.at",
        Öffnungszeiten: "",
        intro: "Die Zukunft braucht unsere Hilfe",
        about: "Future Aid ist eine private Non-Profit Initiative mit dem Ziel unsere Zukunft zu verbessern! Future Aid will sich von anderen Initiativen durch eine einzigartig umfassende Behandlung der Zukunftsthemen (Umwelt-Wirtschaft-Gesellschaft) unterscheiden! Quelle: https://www.future-aid.at/neu-bei-future-aid/%C3%BCber-future-aid/",
        weblink: "https://www.future-aid.at/",
        lat: 48.19866389758175, 
        lng: 16.34490446542928 ,
    },
    {
    
        nr: 17,
        user: "Generation Earth",
        Adresse: "Ottakringer Straße 114-116, 1160 Wien",
        Mail: "info@generationearth.at",
        Öffnungszeiten: "",
        intro: "Das WWF Netzwerk für junge, engagierte Menschen",
        about: "Generation Earth ist ein buntes Netzwerk aus jungen Menschen, das inspiriert, bildet und in Aktion tritt – für die Zukunft unseres Planeten. Bei unserem Action Leader Training lernst du grundlegende Skills und hast die Möglichkeit, dich in verschiedenen Bereichen auszuprobieren. Im Rahmen unserer Projekte treten wir gemeinsam mit dir in Aktion. Wir inspirieren dich mit Wildnis hautnah und zeigen dir in der Natur, was andere oft übersehen. Quelle: https://www.generationearth.at/",
        weblink: "https://www.generationearth.at/",
        lat: 48.21370721583878, 
        lng: 16.323157911988677,
    },
    {
    
        nr: 18,
        user: "Global 2000",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "office@global2000.at",
        Öffnungszeiten: "",
        intro: "Österreichs unabhängige Umweltschutzorganisation",
        about: "Wir setzen alles daran, unsere Welt zum Positiven zu verändern. Das heißt, egal, um welches Umweltschutz-Thema es geht: Wir setzen uns für das Gute und das Schöne ein. Denn es ist schön, bedenkenlos in einen Bio-Apfel zu beissen, den Kindern gesunde, vielfältige Lebensmittel bieten und intakte Lebensräume nützen zu können. Genauso schön ist es auch, mit gutem Gewissen einkaufen zu gehen, weil wir für faire Bedingungen im Handel sorgen und Menschen, Tiere und Pflanzen friedvoll zusammenleben. Quelle: https://www.global2000.at/ueber-global-2000",
        weblink: "https://www.global2000.at/",
        lat: 48.20559473723108,  
        lng: 16.350895198496506,
    },
    {
    
        nr: 19,
        user: "Schwendermarkt",
        Adresse: "Neustiftgasse 36, 1070 Wien",
        Mail: "initiative-schwendermarkt@gmx.at",
        Öffnungszeiten: "",
        intro: "Initiative zur Erhaltung und Belebung des Schwendermarktes",
        about: "Der Schwendermarkt ist der kleinste Markt in Wien. Interessante Geschäfte mit Bio und regionalen Produkten von bauern aus der Umgebung von Wien und dem weinviertel. gemütliche Atmosphäre in Markt Cafés, sehr gutes Essen inkl einer Vietnamesin, die super kocht, Marktstände mit Gemüse, Käse, Obst. tolles großes Café in hippem Blumenladen,.... Quelle: https://www.facebook.com/Schwendermarkt/reviews/?ref=page_internal Review of: Karin N. York",
        weblink: "http://www.schwendermarkt.at/",
        lat: 48.19097235033396, 
        lng: 16.326267103155473,
    },
    {
    
        nr: 20,
        user: "Jane Goodall Institut - Austria",
        Adresse: "Probusgasse 3, 1190 Wien",
        Mail: "office@janegoodall.at",
        Öffnungszeiten: "",
        intro: "für Naturschutz, Umweltbildung und Erforschung wildlebender Tiere",
        about: "Wir wollen das Überleben der letzten Schimpansen sichern. Unseren Projekten legen wir eine ganz alltägliche Erfahrung zugrunde: Ein Lächeln ist der kürzeste Weg zwischen zwei Menschen. Weil sich Herausforderungen besser gemeinsam bewältigen lassen, setzen wir auf enge Zusammenarbeit mit den Menschen vor Ort. Die Folge: der beste Austausch an Wissen und Verständnis für die Bedürfnisse der Einheimischen und für die regionalen Besonderheiten der Tier- und Pflanzenwelt. Quelle: https://janegoodall.at/was-wir-tun/",
        weblink: "https://janegoodall.at/",
        lat: 48.2552212909714,   
        lng: 16.356298763578838,
    },
    {
    
        nr: 21,
        user: "KEC",
        Adresse: "Schendlingerstraße 40, 6900 Bregenz",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 47.49522925643081,   
        lng: 9.71981471752438,
    },
    {
    
        nr: 21,
        user: "KEC",
        Adresse: "Pazmanitengasse 19, 1020 Wien",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 48.22255643075428,   
        lng: 16.385441990561716,
    },
    {
    
        nr: 21,
        user: "KEC",
        Adresse: "10. Oktober Straße 17, 9560 Feldkirchen",
        Mail: "office@kec.at",
        Öffnungszeiten: "",
        intro: "Kanzian Engineering & Consulting GmbH",
        about: "KEC – KANZIAN ENGINEERING & CONSULTING GmbH ist ein stabiler Partner für Unternehmen und zählt zu den erfolgreichsten Unternehmensberatern im Bereich Managementsysteme. Das Produktportfolio spannt sich von Beratungen, Audits oder Trainings in den Bereichen Umwelt, Energie, Qualität und Arbeitssicherheit mit Softwareunterstützung bis hin zu Legal Compliance mit Softwarelösungen. Quelle: https://kec.at/ueber-uns/",
        weblink: "https://kec.at/",
        lat: 46.72394604602631,   
        lng: 14.095550729078235,
    },
    {
    
        nr: 22,
        user: "Klimabündnis Tirol",
        Adresse: "Müllerstraße 7, 6020 Innsbruck",
        Mail: "tirol@klimabuendnis.at",
        Öffnungszeiten: "",
        intro: "Wir setzen uns aktiv für Klimaschutz, Klimagerechtigkeit und einen nachhaltigen Lebensstil ein.",
        about: "Der Verein Klimabündnis Tirol ist Teil des größten kommunalen Klimaschutz-Netzwerks Europas. Die globale Partnerschaft verbindet mehr als 1.700 Gemeinden aus 27 Ländern in Europa mit Indigenen Organisationen des Amazonas-Regenwaldes.In Österreich haben sich über 1000 Gemeinden und Betriebe sowie über 600 Bildungseinrichtungen dem Klimabündnis angeschlossen. Quelle: https://tirol.klimabuendnis.at/ueber-uns/das-klimabuendnis-tirol",
        weblink: "https://tirol.klimabuendnis.at/",
        lat: 47.26157355303793,   
        lng: 11.394328026778537,
    },
    {
    
        nr: 23,
        user: "Klimabündnis Österreich",
        Adresse: "Prinz-Eugen-Straße 72/1.5, 1040 Wien",
        Mail: "office@klimabuendnis.at",
        Öffnungszeiten: "",
        intro: "Wir setzen uns aktiv für Klimaschutz, Klimagerechtigkeit und einen nachhaltigen Lebensstil ein.",
        about: "Wir sind das größte kommunale Klimaschutz-Netzwerk Österreichs. Wir setzen lokale Klimaschutz-Initiativen und schützen gleichzeitig den Amazonas-Regenwald. Und das bereits seit 1990. Das Klimabündnis ist eine globale Partnerschaft zum Schutz des Klimas und verbindet mittlerweile mehr als 1.700 Gemeinden in 27 Ländern Europas mit indigenen Völkern in Südamerika. Die gemeinsamen Ziele sind: Verringerung der Treibhausgas-Emissionen und Erhalt des Amazonas-Regenwaldes. Quelle: https://www.klimabuendnis.at/ueber-uns/kb-ueber-uns",
        weblink: "https://www.klimabuendnis.at/",
        lat: 48.189552457621275,   
        lng: 16.38080932310104,
    },
    {
    
        nr: 24,
        user: "Umwelt Beauftragte",
        Adresse: "Stephansplatz 6/5, 1010 Wien",
        Mail: "office@schoepfung.at",
        Öffnungszeiten: "",
        intro: "der Katholischern & Evangelischen Kirche Österreichs",
        about: "Wir setzen alles daran, unsere Welt zum Positiven zu verändern. Das heißt, egal, um welches Umweltschutz-Thema es geht: Wir setzen uns für das Gute und das Schöne ein. Denn es ist schön, bedenkenlos in einen Bio-Apfel zu beissen, den Kindern gesunde, vielfältige Lebensmittel bieten und intakte Lebensräume nützen zu können. Genauso schön ist es auch, mit gutem Gewissen einkaufen zu gehen, weil wir für faire Bedingungen im Handel sorgen und Menschen, Tiere und Pflanzen friedvoll zusammenleben. Quelle: https://www.global2000.at/ueber-global-2000",
        weblink: "https://www.schoepfung.at/",
        lat: 48.20884827727071,  
        lng: 16.37420801384071,
    },
    {
        nr: 25,
        user: "Lebensart",
        Adresse: "Wiener Straße 35, 3100 St. Pölten",
        Mail: "service@lebensart.at",
        Öffnungszeiten: "",
        intro: "Verlags GmbH",
        about: "nachhaltig.gut.leben. Das ist unsere Vision. Alle Menschen sollen heute und in Zukunft ein gutes Leben führen können. Deshalb haben wir den Lebensart Verlag gegründet. Wir berichten über nachhaltige Trends und bringen Hintergrundinformationen damit Sie eine gute Entscheidung treffen können. Vor allem zeigen wir Lösungsansätze von kreativen Menschen, wie ein gutes Leben aussehen kann und erzählen Geschichten, die inspirieren und zu eigenem Handeln anregen. Das alles lesen Sie in den Print und Online-Magazinen LEBENSART, BUSINESSART und über die Reiseplattform lebensart-reisen.at. Wir veranstalten jährlich die Wahl der Nachhaltigen GestalterInnen Österreichs, sind Mitveranstalter des CSR-Circle, kooperieren mit engagierten Menschen und Organisationen und unterstützen Partner in ihrer nachhaltigen Kommunikation. Quelle: https://www.lebensart-verlag.at/was-wir-tun-werte-vision-und-mission",
        weblink: "https://www.lebensart.at/",
        lat: 48.21892335496585,   
        lng: 15.660709850085858,
    },
    {
        nr: 25,
        user: "Lebensart",
        Adresse: "Wiener Straße 35, 3100 St. Pölten",
        Mail: "service@lebensart.at",
        Öffnungszeiten: "",
        intro: "Verlags GmbH",
        about: "nachhaltig.gut.leben. Das ist unsere Vision. Alle Menschen sollen heute und in Zukunft ein gutes Leben führen können. Deshalb haben wir den Lebensart Verlag gegründet. Wir berichten über nachhaltige Trends und bringen Hintergrundinformationen damit Sie eine gute Entscheidung treffen können. Vor allem zeigen wir Lösungsansätze von kreativen Menschen, wie ein gutes Leben aussehen kann und erzählen Geschichten, die inspirieren und zu eigenem Handeln anregen. Das alles lesen Sie in den Print und Online-Magazinen LEBENSART, BUSINESSART und über die Reiseplattform lebensart-reisen.at. Wir veranstalten jährlich die Wahl der Nachhaltigen GestalterInnen Österreichs, sind Mitveranstalter des CSR-Circle, kooperieren mit engagierten Menschen und Organisationen und unterstützen Partner in ihrer nachhaltigen Kommunikation. Quelle: https://www.lebensart-verlag.at/was-wir-tun-werte-vision-und-mission",
        weblink: "https://www.lebensart.at/",
        lat: 48.21892335496585,   
        lng: 15.660709850085858,
    },
    {
        nr: 26,
        user: "Land schafft Leben",
        Adresse: "Erzherzog-Johann-Str. 248b, 8970 Schladming",
        Mail: "post@landschafftleben.at",
        Öffnungszeiten: "",
        intro: "ist österreichischen Lebensmitteln auf der Spur!",
        about: "Wir zeigen den Konsumentinnen und Konsumenten transparent und ohne zu werten, wie in Österreich Lebensmittel produziert werden, wie die Produktion vor Ort im Bauernhof erfolgt, wie die Verarbeitung funktioniert und wie das fertige Produkt schließlich im Lebensmittelhandel landet. Für die Konsumentinnen und Konsumenten ergibt sich durch die leicht nachvollziehbar und ausführlich aufbereiteten Informationen ein neues Verständnis für die Zusammenhänge innerhalb der Lebensmittelproduktion und damit ein höheres Wert-Bewusstsein für österreichische Lebensmittel. Quelle: https://www.landschafftleben.at/service-aktuelles/organisation/verein",
        weblink: "https://www.landschafftleben.at/",
        lat: 47.393776442137025,  
        lng: 13.687645470807377,
    },
    {
        nr: 27,
        user: "MATISSEK Innovation Consulting",
        Adresse: "Schönbrunner Straße 178/2, 1120 Wien",
        Mail: "office@matissek.at",
        Öffnungszeiten: "",
        intro: "Michael Matissek, MSc",
        about: "MATISSEK Innovation Consulting bietet ihnen Service und Beratung im Bereich Forschungs- und Innovationsberatung. Meine Kernkompetenz ist die interdisziplinäre – wissenschaftliche, wirtschaftliche und nachhaltige – Betreuung ihres Projektes. Quelle: https://firmen.wko.at/michael-matissek%2c-msc-matissek-innovation-consulting/wien/?firmaid=017e38dd-b16b-4087-bcef-d618a98e7d68&name=michael+matissek,+msc&standort=wien+(bundesland)",
        weblink: "https://firmen.wko.at/michael-matissek%2c-msc-matissek-innovation-consulting/wien/?firmaid=017e38dd-b16b-4087-bcef-d618a98e7d68&name=michael+matissek,+msc&standort=wien+(bundesland)",
        lat: 48.18610794055923,    
        lng: 16.338176340687966,
    },
    {
        nr: 28,
        user: "Mördinger Kommunikation- und Politikberatung",
        Adresse: "Wolkersbergenstraße 164, 1130 Wien",
        Mail: "nicht angegeben",
        Öffnungszeiten: "",
        intro: "Lobby für Energiewende und Nachhaltigkeit",
        about: "Energiewende und Nachhaltigkeit brauchen Unterstützung. Obwohl unzählige engagierte Menschen, Organisationen und Unternehmen an einer nachhaltigen Zukunft arbeiten, kommen wir nur langsam vom Fleck. Mal fehlt es am rechtlichen Rahmen, mal an der Aufmerksamkeit der Medien. Und manchmal bekommt die Energiewende Probleme mit Menschen vor Ort oder dem Naturschutz. Quelle: https://www.moerdinger.at/",
        weblink: "https://www.moerdinger.at/",
        lat: 48.17657903037716,   
        lng: 16.274120095963383,
    },
    {
        nr: 29,
        user: "Naturschutzbund",
        Adresse: "Museumsplatz 2, 5020 Salzburg",
        Mail: "bundesverband@naturschutzbund.at",
        Öffnungszeiten: "",
        intro: "Bundesverband",
        about: "Wer kann sich heute ein Wien ohne Wienerwald, ein Österreich mit Atomkraft, Alpen ohne Nationalpark Hohe Tauern oder trockene Krimmler Wasserfälle vorstellen? Viele unserer Naturjuwele sind nur durch den beharrlichen Einsatz und die unermüdliche Arbeit des Naturschutzbundes erhalten geblieben. Seit über 100 Jahren kämpfen seine ehrenamtlichen Mitarbeiter um die Erhaltung von Österreichs Naturjuwelen. Unterstützt werden sie dabei von einer professionellen Bundesgeschäftsstelle und Geschäftsstellen in allen Bundesländern. Quelle: https://naturschutzbund.at/naturschutzbund-oesterreich.html",
        weblink: "https://naturschutzbund.at/startseite.html",
        lat: 47.801349824481825,     
        lng: 13.039932940132278,
    },
    {
        nr: 30,
        user: "Verein Plastic Planet",
        Adresse: "Wielandplatz 8/28, 1100 Wien",
        Mail: "vppaustria@gmail.com",
        Öffnungszeiten: "",
        intro: "Wir arbeiten an vielen spannenden Projekten, um das Leben anderer zu verbessern.",
        about: "Es sind nicht die Worte, die zählen, sondern es ist das Handeln und es sind die Taten. Deshalb haben wir Verein ::: Plastic Planet Austria ins Leben gerufen.Nachdem wir die Dokumentation Plastic Planet von Werner Boote 2009 gesehen hatten und nach fünf Jahren sahen, dass man als Einzelperson nicht viel erreichen kann, haben wir uns im Februar 2018 entschlossen unsere Kräfte zu bündeln und einen Verein zur Plastikreduktion zu gründen! Quelle: https://vereinplasticplanet.wixsite.com/website",
        weblink: "https://vereinplasticplanet.wixsite.com/website",
        lat: 48.17711586565596,      
        lng: 16.379764427194658,
    },
    {
        nr: 31,
        user: "STRATECO",
        Adresse: "Ruckerlberggasse 13, 8020 Graz",
        Mail: "office@strat.eco",
        Öffnungszeiten: "",
        intro: "Information über Prozessoptimierung und Ökologische Bewertung",
        about: "Wir wollen die Welt ein Stückchen nachhaltiger machen – und glauben daran, dass wir gemeinsam mit Ihnen Ihre Produkte, Dienstleistungen, Prozesse und Ressourcennutzung ökologisch und oft auch ökonomisch nachhaltiger gestalten können, um dadurch Ihr Unternehmen und die regionale Wertschöpfung zu stärken. Das bedeutet für uns: Wir unterstützen Wirtschafts- und Lebensweisen in ihrem Ziel, allen eine stabile Zukunft zu bescheren. Quelle: https://www.strat.eco/",
        weblink: "https://www.strat.eco/",
        lat: 47.06880837066728,       
        lng: 15.464438743813336,
    },
    {
        nr: 32,
        user: "Team CU2 SustainAgiency",
        Adresse: "Gardegasse 6/27, 1070 Wien",
        Mail: "info@cu2.team",
        Öffnungszeiten: "",
        intro: "Das Magazin der CU2 Kreativagrntur",
        about: "In über 23 Jahren an Erfahrung in der (Markt-)Kommunikation, u. a. mit den Schwerpunkten Packaging-Design & Prototyping, CI/CD Development und Location-ReDesign, in denen die CU2 Kreativagentur mannigfaltige große, kleine, spannende, fade, innovative, unterhaltsame und ernsthafte Projekte entwickeln und realisieren konnte, entstand in ihr die fixe Überzeugung: » Wir tun alles, was wir können. Und was wir können, machen wir wirklich gut. Mit NetzAmWerk realisieren wir Projekte im Teamwork – für und mit anderen. « Quelle: https://cu2.team/mission/",
        weblink: "https://cu2.team/",
        lat: 48.20500463736926,     
        lng: 16.355892035897163,
    },
    {
        nr: 33,
        user: "To Good To Go",
        Adresse: "Leopold-Ungar-Platz 2, 1190 Wien",
        Mail: "info@toogoodtogo.at",
        Öffnungszeiten: "",
        intro: "Rette Essen - Hilf unserem Planeten",
        about: "Wir träumen von einem Planeten ohne Lebensmittelverschwendung und engagieren uns täglich dafür, diesen Traum zu verwirklichen. Mit unserer App kannst auch du dazu beitragen - herunterladen, anmelden und köstliches, zu viel produziertes Essen retten. Was dich erwartet, ist immer eine Überraschung zu tollem Preis und gleichzeitig tust du Gutes für unseren Planeten. Jetzt Essen retten! Quelle: https://toogoodtogo.at/de-at",
        weblink: "https://toogoodtogo.at/de-at",
        lat: 48.24831724440653,      
        lng: 16.36777621130777,
    },
    {
        nr: 34,
        user: "Torismus & Klimafit",
        Adresse: "Gärtnergasse 4c, 2103 Langenzersdorf",
        Mail: "office@tourismusklimafit.at",
        Öffnungszeiten: "",
        intro: "Mit einer klimafitten Angebots- und Produktentwicklung zum wirtschaftlich nachhaltigen Erfolg",
        about: "Der Klimawandel wirkt auf Land- Wasser- oder Forstwirtschaft und daher in vielen Bereichen, die unmittelbar mit dem Tourismus zusammenhängen. Das Reisen ist sehnsuchtsvoller Zeitvertreib und wichtiger Wirtschaftsfaktor, hat aber wiederum Auswirkungen auf Umwelt und Klima. Die Folgen des Klimawandels sind allgegenwärtig. Das Problembewusstsein in der Bevölkerung und bei den Gästen steigt, der „Reise-Klima-Fußabdruck“ avisiert zum Auswahl- und Entscheidungskriterium für eine bestimmte Region. Touristiker und Regionalentwickler sind sensibilisiert, stehen aber vor großen Herausforderungen. Verantwortungsvoller, klimafitter Tourismus bietet Chancen für eine umwelt- und sozialverträgliche wirtschaftliche Entwicklung. Wir unterstützen unsere Kunden mit nachhaltigen Mobilitätslösungen, implementieren klimafitte Angebote und kreative Produkte entlang der touristischen Dienstleistungskette, vernetzen zu klimafreundlichen Unternehmen, Institutionen sowie Förderstellen und motivieren Anbieter ebenso wie Nachfrager zu einem klimabewussten Umdenken. Quelle: https://tourismusklimafit.at/",
        weblink: "https://tourismusklimafit.at/",
        lat: 48.30210650588059,     
        lng: 16.369665141994382,
    },
    {
        nr: 35,
        user: "Transition Austria",
        Adresse: "Burgring 6/2, 8010 Graz",
        Mail: "office@transition.at",
        Öffnungszeiten: "",
        intro: "Wandelinitiativen: Überblicken – Verstehen – Mitmachen.",
        about: "Transition Austria ist eine Plattform und Vernetzung von und für Initiativen des Wandels in Österreich.  Diese Initiativen sind von der Idee der Transition Bewegung inspiriert.  Sie wurden von Einzelpersonen, Gruppen, Initiativen, NGO’s oder Wirtschaftsbetrieben initiiert. Sie suchen Lösungen im Alltag und neue Formen des Zusammenslebens auf kommunaler Ebene. Sie agieren nach dem Motto “Global Denken, Lokal handeln”. Quelle: https://transition.at/transition-austria/",
        weblink: "https://tourismusklimafit.at/",
        lat: 47.07180036574457,      
        lng: 15.444181955456818,
    },
    {
        nr: 36,
        user: "Umblick",
        Adresse: "Hartlgasse 9/13, 1200 Wien",
        Mail: "buero@umblick.at",
        Öffnungszeiten: "",
        intro: "Umweltbildung - Umwelt, Abfall, Energie, Nachhaltigkeit, Mobilität",
        about: "Umblick steht für umfassende Weiterentwicklung im Hinblick auf Themengebiete der Umwelt und Nachhaltigkeit. Wir konzentrieren uns darauf, Menschen und Organisationen bei der Mitgestaltung einer nachhaltigen Zukunft zu unterstützen. Durch unser interdisziplinäres Team erreichen wir Ihre Ziele effizient unter Einbeziehung unterschiedlicher Blickwinkel und kombinierter Ansätze.  Wir schließen die Lücke von reinem Wissen hin zum effektiven Umsetzen. Um­blick hat sich zum Ziel gesetzt Men­schen dabei zu er­mutigen ihre Selbst­­wirk­sam­keit zu be­grei­fen und ihre Hand­lun­gen als wich­tigen Bei­trag für das ge­mein­same Ge­stal­ten einer nach­hal­tig­eren Welt zu er­le­ben. Um diese Mis­sion­en zu er­fül­len be­gin­nen wir be­reits bei den Jüng­sten im Kinder­garten und bieten Umweltbildung wie z.B. Umweltworkshops bis hin zum Pen­sions­al­ter an. Quelle: https://umblick.at/bildung/ueber-uns/",
        weblink: "https://umblick.at/",
        lat: 48.23160827990701,     
        lng: 16.373425396510783,
    },
    {
        nr: 37,
        user: "UMA - Umwelt Management Austria",
        Adresse: "Palmgasse 3/2, 1150 Wien",
        Mail: "office@uma.or.at",
        Öffnungszeiten: "",
        intro: "Ihr Partner für Erfolg mit Umweltschutz",
        about: "Umwelt Management Austria ist ein gemeinnütziger Verein mit den Zielen Umweltschutz zielorientiert und nutzenstiftend in Unternehmen und öffentlichen Einrichtungen zu verankern sowie die Rahmenbedingungen für Umweltschutz und eine zukunftsfähige Entwicklung in Österreich zu verbessern. Umwelt Management Austria fordert dabei nicht „Umweltschutz um jeden Preis“ sondern zeigt, dass Umweltschutz Vorteile, wie Kosteneinsparungen, Rechtssicherheit, Risikominderung und Imageverbesserung bringen kann. Quelle: https://www.uma.or.at/ueber-uns/",
        weblink: "https://www.uma.or.at/",
        lat: 48.1945491688956,      
        lng: 16.338100013702068,
    },
    {
        nr: 38,
        user: "Umwelt Dachverband",
        Adresse: "Strozzigasse 10/8-9, 1080 Wien",
        Mail: "office@umweltdachverband.at",
        Öffnungszeiten: "",
        intro: "& Naturschutzbund zum GAP-Strategieplan: Lob und Kritik für geplanten Biodiversitätsschutz",
        about: "Durch Projekt-, Lobbying- und Öffentlichkeitsarbeit, das Angebot von Umweltbildungsmaßnahmen, Gesetzesbegutachtungen sowie die Mitarbeit in verschiedenen nationalen und internationalen Beiräten und Kommissionen vertritt der Umweltdachverband die Umweltinteressen seiner 36 Mitgliedsorganisationen und fungiert damit als zentrale Informations- und Netzwerkplattform im Bereich Umweltpolitik, Umweltrecht und Umweltbildung. Quelle: https://www.umweltdachverband.at/ueber-uns/was-wir-tun/",
        weblink: "https://www.umweltdachverband.at/",
        lat: 48.207338830738024,       
        lng: 16.349440583017184,
    },
    {
        nr: 39,
        user: "United Against Waste",
        Adresse: "Haberlgasse 56/3, 1160 Wien",
        Mail: "united-against-waste@tatwort.at",
        Öffnungszeiten: "",
        intro: "Lebensmittel Wert:Voll:Nutzen",
        about: "Das gemeinsame Ziel: Reduktion von vermeidbaren Lebensmittelabfällen. United Against Waste wurde im Jahr 2014 in Form einer branchenübergreifenden Plattform ins Leben gerufen. Gemeinsam verfolgen Unternehmen aus dem Food Service Markt sowie Bund, Länder, Wissenschaft und NGOs ein ambitioniertes Ziel: Die vermeidbaren Lebensmittelabfälle in Küchenbetrieben sollen bis zum Jahr 2030 um die Hälfte reduziert werden. Quelle: https://united-against-waste.at/die-initiative/",
        weblink: "https://united-against-waste.at/",
        lat: 48.21049702280069,        
        lng: 16.3305577830173,
    },
    {
        nr: 40,
        user: "virtual vehicle",
        Adresse: "Inffeldgasse 21a, 8010 Graz",
        Mail: "info@v2c2.at",
        Öffnungszeiten: "",
        intro: "Leidenschaft für elekrifizierte, autonome und vernetzte Fahrzeuge",
        about: "Virtual Vehicle ist ein führendes internationales F&E Zentrum für die Automobil-und Bahnindustrie. Das Zentrum konzentriert sich auf die konsequente Virtualisierung der Fahrzeugentwicklung. Diese Verknüpfung von numerischen Simulationen und Hardware-Tests führt zu einem umfassenden Hardware-Software-System-Design. Quelle: https://www.v2c2.at/deu/",
        weblink: "https://www.v2c2.at/deu/",
        lat: 47.058310296863084,       
        lng: 15.463768138264388,
    },
    {
        nr: 41,
        user: "WWF Österreich",
        Adresse: "Ottakringer Straße 114 - 116, 1160 Wien",
        Mail: "wwf@wwf.at",
        Öffnungszeiten: "",
        intro: "Teil des globalen Netzwerks des WWF",
        about: "Wir wollen der weltweiten Naturzerstörung Einhalt gebieten und eine Zukunft gestalten, in der Mensch und Natur in Harmonie leben. Der Schutz der Umwelt ist heute mehr denn je ein Thema. Es geht dabei nicht nur um exotische Tierarten, die vom Aussterben bedroht sind – wir wollen uns auch immer mit den sozialen Umständen befassen, die mit der weltweiten Naturzerstörung in Zusammenhang stehen. Der WWF bietet Lösungen für Mensch und Natur – und zwar auf allen Ebenen. Quelle: https://www.wwf.at/de/ueber-uns/",
        weblink: "https://www.wwf.at/",
        lat: 48.21366432060026,        
        lng: 16.323683624799894,
    },
    {
        nr: 42,
        user: "Tierschutz Austria",
        Adresse: "Triester Straße 8, 2331 Vösendorf",
        Mail: "office@tierschutz-austria.at",
        Öffnungszeiten: "",
        intro: "Eine zweite Chance",
        about: "Wir streben nach einer Welt, in der Tiere als empfindsame Lebewesen anerkannt werden. Daher setzen wir uns auf den Ebenen Tier, Mensch und Gesellschaft für das Lebensrecht aller Tiere sowie den Schutz und Erhalt ihrer Habitate und Rechte ein. Wir suchen uns nicht aus , wen wir schützen. Wir packen selbst an. In unserem Tierschutzhaus kümmern wir uns um Tiere, die sonst keine Chance haben. Quelle: https://www.tierschutz-austria.at/ueber-uns/",
        weblink: "https://www.tierschutz-austria.at/",
        lat: 48.1222246427573,         
        lng: 16.316048719248958,
    },
    {
        nr: 43,
        user: "iamgood",
        Adresse: "Hirschengasse 16/2/7, 1060 Wien",
        Mail: "say@iamgood.cc",
        Öffnungszeiten: "",
        intro: "Plattform für Persönlichkeitsentwicklung",
        about: "Education & creation of a broader awareness for environmental protection. iamgood is an event series and a community for all curious minds, who want to live a more meaningful life. Once every two months, we organize iamgood events. We invite two different speakers to give inspirational talks and actionable insights on a broad range of personal development topics. Also, we love music, that’s why we invite great musicians to our events.  Each iamgood event takes place at a new location in Vienna and is free of charge. Quelle: https://iamgood.cc/",
        weblink: "hhttps://iamgood.cc/",
        lat: 48.19468386474175,      
        lng: 16.34782394068816,
    },
    {
        nr: 44,
        user: "AGU",
        Adresse: "Große Mohrengasse 39/6, 1020 Wien",
        Mail: "info@aegu.net",
        Öffnungszeiten: "",
        intro: "Ärztinnen und Ärzte für eine gesunde Umwelt",
        about: "Als österreichische Sektion der ISDE (International Society of Doctors for the Environment) sind wir eine parteipolitisch unabhängige Organisation von Ärztinnen und Ärzten, die sich für Belange des Umweltschutzes aus ärztlicher Sicht einsetzen. Quelle: https://www.aegu.net/uber-uns.html",
        weblink: "https://www.aegu.net/",
        lat: 48.21859534694276,      
        lng: 16.384384972677523,
    },
    {
        nr: 45,
        user: "ÖKF FishLife",
        Adresse: "Breitenfurterstraße 335, 1230 Wien",
        Mail: "oekf@fishlife.at",
        Öffnungszeiten: "",
        intro: "Österreichisches Kuratorium für Fischerei und Gewässerschutz",
        about: "ÖKF FishLife vertritt als ANERKANNTER UMWELTVERBAND die Interessen seiner Mitglieder in allen Belangen des waid- und hegegerechten Angelns und setzt sich auf österreichischer und internationaler Ebene dafür ein, die Ausübung der Angelfischerei zu unterstützen, zu sichern und zu fördern. Ein Angler geht ans Wasser, sucht Erholung und möchte Fische fangen. Doch für erfolgreiches Angeln braucht man intakte Gewässer mit einem gesunden Fischbestand. Immer wieder sind wir am am Wasser konfrontiert mit Staumauern von der Energiewirtschaft, die jedes Gewässer zur Stromerzeugung (miss)brauchen möchte bzw. Fischfressern, die durch einseitigem Artenschutz so lange schützen werden bis Ihnen auch der letzte Fisch zum Opfer gefallen ist. Quelle: https://www.fishlife.at/ueber-fishlife/unser-leitbild/",
        weblink: "https://www.fishlife.at/",
        lat: 48.1422647036987,       
        lng: 16.29290108801815,
    },
    {
        nr: 46,
        user: "Ökobüro",
        Adresse: "Neustiftgasse 36/3a, 1070 Wien",
        Mail: "office@oekobuero.at",
        Öffnungszeiten: "",
        intro: "Allianz der Umweltbewegung",
        about: "ÖKOBÜRO kämpft als von Staat, Parteien und Unternehmen unabhängige Allianz für die Rechte der Umweltbewegung. Gemeinsam engagieren wir uns für einen zukunftsfähigen Umgang mit unserer Umwelt, eine starke Zivilgesellschaft und einen demokratischen Rechtsstaat. In der Allianz unserer Mitgliedsorganisationen vereinen wir Kraft und Kompetenzen. ÖKOBÜRO kämpft als von Staat, Parteien und Unternehmen unabhängige Allianz für die Rechte der Umweltbewegung. Gemeinsam engagieren wir uns für einen zukunftsfähigen Umgang mit unserer Umwelt, eine starke Zivilgesellschaft und einen demokratischen Rechtsstaat. In der Allianz unserer Mitgliedsorganisationen vereinen wir Kraft und Kompetenzen. Quelle: https://www.oekobuero.at/de/ueber-uns/vision-und-mission/",
        weblink: "https://www.oekobuero.at/de/",
        lat: 48.20563048890318,        
        lng: 16.350916656031018,
    },
    {
        nr: 47,
        user: "Ökosoziales Formun Wien",
        Adresse: "Stadiongasse 6-8, 1010 Wien",
        Mail: "wien@oekosozial.at",
        Öffnungszeiten: "",
        intro: "Für die Menschen in unserer Stadt und unsere städtische Umwelt – für eine lebenswerte Gegenwart und Zukunft!",
        about: "Mit unseren Projekten und Aktivitäten fördern wir einen respektvollen Umgang mit der Natur unserer Lebensgrundlage und ein friedliches und solidarisches Miteinander der Menschen in unserer Stadt. Wir beziehen uns dabei auf die Agenda 2030 und ihre 17 Ziele für Nachhaltige Entwicklung (Sustainable Development Goals, kurz: „SDGs“) – den weltweiten UNO-Aktionsplan für Nachhaltige Entwicklung. Quelle: https://oekosozial.at/wien/was-wir-tun/",
        weblink: "https://oekosozial.at/wien/",
        lat: 48.20940797658662,       
        lng: 16.356514269524183,
    },
    {
        nr: 48,
        user: "Öko Vernetzung",
        Adresse: "Herbststraße 21 / 24-27, 1160 Wien",
        Mail: "kontakt@oekovernetzung.at",
        Öffnungszeiten: "",
        intro: "Sei Teil eines nachhaltigen Gesellschaftswandels!",
        about: "Unser Zugang basiert auf gegenseitigem Respekt und gelebtem Respekt vor der Natur sowie auf dem gemeinsamen Interesse, ein kritisches Bewusstsein für eigene Wirkfelder im Nachhaltigkeitsbereich zu erleben. Das Hinterfragen des eigenen Lebensstils, ein Bewusstsein über die eigene Selbstwirksamkeit im Rahmen gesellschaftlicher und politischer (Partizipations-)Prozesse, die kritische Auseinandersetzung mit strukturellen Merkmalen von Politik, Wirtschaft und Gesellschaft haben dabei genauso Platz wie die Vermittlung praxisorientierter Methoden zur Organisation von Meetings und Projekten. Auch Teambuilding, Persönlichkeitsbildung und ein gelebtes, respektvolles und achtsames Miteinander haben in unserer Arbeit einen besonderen Stellenwert. Der Ökovernetzungsförderverein möchte durch seine Angebote einen lebendigen Zugang zu nachhaltiger Entwicklung für „Hirn, Herz und Hände“ der Teilnehmer*innen anbieten und erfahrbar machen. Wir bestärken uns nicht nur gegenseitig in unserem Tun, sondern wollen auch gemeinsam Initiativen und Projekte weiterentwickeln und fördern. Quelle: https://oekovernetzung.at/ueber-uns/unsere-ziele-und-beweggruende/",
        weblink: "https://oekovernetzung.at/",
        lat: 48.20563653361367,        
        lng: 16.331510627195456,
    },
    {
        nr: 49,
        user: "Österreichisches Ökologie Institut",
        Adresse: "Seidengasse 13, 1070 Wien",
        Mail: "office@ecology.at",
        Öffnungszeiten: "",
        intro: "Forschungsverein",
        about: "Das Österreichische Ökologie-Institut wurde 1985 als unabhängiger, gemeinnütziger Forschungsverein gegründet und setzt sich für den Wandel zu einer nachhaltigen Gesellschaft ein. Der Verein bezweckt mit all seinen Aktivitäten die Eindämmung des durch den Menschen verursachten Klimawandels und unterstützt die Dekarbonisierung Österreichs. Quelle: http://www.ecology.at/institut.htm",
        weblink: "http://www.ecology.at/",
        lat: 48.200416653858916,        
        lng: 16.345764407607426 ,
    },
    {
        nr: 50,
        user: "Österreichisches Ökologie Institut",
        Adresse: "Kirchstraße 9/2, 6900 Bregenz",
        Mail: "oekoinstitut.vlbg@ecology.at",
        Öffnungszeiten: "",
        intro: "Forschungsverein",
        about: "Das Österreichische Ökologie-Institut wurde 1985 als unabhängiger, gemeinnütziger Forschungsverein gegründet und setzt sich für den Wandel zu einer nachhaltigen Gesellschaft ein. Der Verein bezweckt mit all seinen Aktivitäten die Eindämmung des durch den Menschen verursachten Klimawandels und unterstützt die Dekarbonisierung Österreichs. Quelle: http://www.ecology.at/institut.htm",
        weblink: "http://www.ecology.at/",
        lat: 47.501922343901335,         
        lng: 9.747872730330908,
    },
];